### ISSUE TITLE
Creating snapshot of running container then copying snapshot to new host fails

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdMosaic#101]
**Describe the bug**
Host1 has a **running** container named CN1
I take a snapshot of CN1 and call it CN1-snap0 and CN1-snap0 is created.
I then click on  CN1-snap0 and enter Host2 as target and CN1 for new container name on Host2

A red box appears with a Server error Post Internal Server error ... unable to perform live migration CRIU isn't installed on Source Server.   

However, doing the above steps **works** from the command line (see bottom).

**NOTE:**  First I am using SNAP LXD so CRIU is included when LXD is installed.
Second, if I **stop** the originating container Host1 CN1 first then take the snapshot then the copy to Host2 the copy succeeds!

**Expected behavior**
The container CN1 should be created on Host2.

> **host1:~$ lxc info cn1**
> \:
> \: 
> Snapshots:
>   cn1-snap0 (taken at 2019/07/09 15:30 UTC) (stateless)
> host1\:\~\$ **lxc copy cn1/cn1-snap0 host2:cn1**
> host1\:\~\$ **lxc list host2:**           
+--------+------------+------+-------+------------------+-----------------+
| NAME |  STATE  | IPV4 | IPV6 |    TYPE          | SNAPSHOTS |
+--------+------------+------+-------+------------------+-----------------+
| cn1  | STOPPED |         |         | PERSISTENT |                       |
+--------+------------+------+-------+------------------+-----------------+

**Comment by turtle0x1** [comment]
The criu is out of scope of this project, does it work on the cli

**Comment by bmullan** [comment]
@turtle0x1 
yes... and I am using SNAP LXD which includes CRIU.
In either case why would it succeed in copying the snapshot if the originating container of the snapshot is stopped but only fail if the originating container of the snapshot is running?

**Comment by turtle0x1** [comment]
Becauase one is handled as migration and one is handled as a copy, ill take at the underlying library later to see if its someting i can fix, if criu is with snap i can probably give it ago

**Comment by turtle0x1** [comment]
My snap doesn't have criu by default, are you taking state full container snapshots from the CLI ?

**Comment by bmullan** [comment]
W the original container still running I took a snapshot
Then using the CLI I copied the snapshot successfully to Host2

Doing the same from LXDMosaic fails

**Comment by bmullan** [comment]
Sorry.. per Stephane Graber

For the snap, you need to do:

   - snap set lxd criu.enable=true
   - systemctl reload snap.lxd.daemon

To enable CRIU.


So it is installed but w SNAP LXD it has to be enabled... Forgot to mention
that

**Comment by turtle0x1** [comment]
In the container of your lxd mosaic instance
```
cd /var/www/LxdMosaic
git pull
composer update
```

Try again, this should fix it :smile:

**Comment by bmullan** [comment]
yes... that worked...
