### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by turtle0x1** [turtle0x1/LxdMosaic#104]
I have put out some documentation but im not to sure what or how to write, 

Ive done a basic introduction to cloud-config & deployments as they are the only "custom" part (that is, not just "standard" lxd functionality), if your interested in taking a look @bmullan 

https://lxdmosaic.readthedocs.io/

**Comment by turtle0x1** [comment]
This was merged!

**Comment by bmullan** [comment]
Sorry I have been offline for nearly a week.

The documentation should still be spell checked.
example:

Once the installation is complete you need to go to into your browser and*
> vist;*
>

Brian
