### ISSUE TITLE
When Creating a Snapshot of a container - add notification on Right to say "Snapshot Complete"

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdMosaic#106]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When Creating a Snapshot of a container - add notification on Right to say "Snapshot Complete"
Currently you get a Green CheckMark but I think the above is more explicit.

**Describe alternatives you've considered**

**Additional context**

**Comment by turtle0x1** [comment]
This is again a duplicate comment about making the operation synchronous which i assume for everybody the operation is fast but it may not be, 

again going to close as not really achievable
