### ISSUE TITLE
When Creating a Snapshot of a container - when complete new Snapshot doesn't appear under that Server until hitting "Dashboard"

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdMosaic#107]
**Describe the bug**
When Creating a Snapshot of a container - when complete new Snapshot doesn't appear under that Server until hitting "Dashboard"

**To Reproduce**
1. Create a snapshot of a container
2. when its complete note that you don't see the snapshot listed under that CN name until you hit "Dashboard" then click on the original CN name

**Expected behavior**
After the Snapshot is created the screen should refresh and the new Snapshot should appear under the Original CN it was created from automatically

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04.2 for Host & containers
 - Browser: chromium-browser

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by turtle0x1** [comment]
Im closing this because I can't duplicate it
