### ISSUE TITLE
After copying a Snapshot from Host1 to Host2 there should be a separate explicit notification on Right that says Container Copy Complete

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdMosaic#108]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
After copying a Snapshot from Host1 to Host2 there should be a separate **explicit notification** on the Right beyond just the Green checkmark to indicate its complete.

I think there should be one more that says "Creating Container Completed"

**Describe alternatives you've considered**

**Additional context**

**Comment by turtle0x1** [comment]
Hey, todo this LxdMosaic would need to make copying the snapshot synchronous (doing this would solve some of the other iseues you opened) this would also effect copying containers, which makes me not keen on the idea

Im going to close this for the time being

**Comment by bmullan** [comment]
@turtle0x1 
Thanks... but I have a non-programmer question.
How does the LXDMosaic UI know to change the check mark to Green when its done?

**Comment by turtle0x1** [comment]
Lxd "emits" / sends events as they hapen!

**Comment by bmullan** [comment]
I obviously don't know how this works but when that "event"  occurs couldn't a "copy complete" message be shown ?

**Comment by turtle0x1** [comment]
Your right i could do that, but would need to look at all operations and see which ones are also worthy of an additional notification!
