### ISSUE TITLE
When copy a CN snapshot from Host 1 to Host2, when complete menu never refreshes to remove entry Form until you hit "Dashboard" again & New CN for Host2 doesn't show until you click on Host2 on Left side of screen

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdMosaic#109]
**Describe the bug**
When copy a CN snapshot from Host 1 to Host2, when complete menu never refreshes and new CN under Host2 doesn't appear until you hit "Dashboard" again.

The Box in the middle of the screen where you entered the Remote Host and the new CN name  just stays there until you hit "Dashboard" to clear it.

But even after you've done that the new CN under the Remote Host2 doesn't show the new CN until you click on Host2 again also.

**To Reproduce**
1. Host1 create a snapshot of CN1
2. click on CN1
3. select Copy then enter Name/Alias of remote Server Host2 and name of new Host2 container
4. when complete the screen is never refreshed and that Form box remains until you hit "Dashboard" then it disappears but the Host2 entry on Left never shows new Container until you also Click on it again.

**Expected behavior**
When the Copy of the Snapshot to Host2 is complete the screen should refresh & remove that Form box where you had to enter the Name/Alias and the new CN name AND.. the Host2 entry on the left side of the screen should display its new CN (which will be in the stopped state"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04.2
 - Browser: chromium-browser

**Smartphone (please complete the following information):**
n/a

**Additional context**

**Comment by turtle0x1** [comment]
This should be closed by 72b94cd78afb67c906eb12caab63ece7a4668f32 :roll_eyes:
