### ISSUE TITLE
Make LXCMosaic LXD Clustering capable.

### ISSUE THREAD

**Issue by Philippe-Arnaud** [turtle0x1/LxdMosaic#112]
**Is your feature request related to a problem? Please describe.**
It seems that LxdMosaic cannot detect that some containers are configured in [clustering mode](https://lxd.readthedocs.io/en/latest/clustering/).

**Describe the solution you'd like**
I'd like to be able to operate a cluster of LXDs (migration, load balancing…) in the same fashion as Mosaic is currently operating.

**Describe alternatives you've considered**
So far, the only alternative is to use CLI to manage operations at clustering level while using the webUI for "conventional operations".

**Comment by turtle0x1** [comment]
Hey so this currently already an issue here #6 but ...

I dont use clusters (I have no problem creating one) so I need some input (please comment on #6) for the features you would expect :smile:

**Comment by Philippe-Arnaud** [comment]
Thanks for the feedback and sorry for the duplicate issue…

**Comment by turtle0x1** [comment]
No worries please do leave a comment on #6 though
