### ISSUE TITLE
IPV6 Hostnames not working

### ISSUE THREAD

**Issue by cvmiller** [turtle0x1/LxdMosaic#113]
**Describe the bug**
On the "first run" URL: 
Attempt to enter hostname:port  (e.g. my_v6_host:8443)
lxdMosaic responds: "Unable to parse URI: https://:8443"

**To Reproduce**
1. Go to First run URL https://my_v6_host/views/firstRun
2. Enter hostname:8443, and trust password
3. Click "Done"
4. Note error message

**Expected behavior**
Expected lxdMosaic to connect to my LXD on port 8443

**Screenshots**

**Desktop (please complete the following information):**
Shouldn't matter, but I was using Mac OS X and Firefox

**Additional context**

**Comment by turtle0x1** [comment]
Is this ipv6?

**Comment by cvmiller** [comment]
Yes, my host, and VM are both running IPv6. I can use the LXD client to control other LXDs over IPv6. I would like lxdMosaic to also run over IPv6 as well.

**Comment by turtle0x1** [comment]
Sorry i dont use ipv6 so i havent tested that, so you can manage remote hosts over ipv6 but not your local one?

**Comment by turtle0x1** [comment]
Also can you provide the connection string you are using that fails

**Comment by cvmiller** [comment]
Yes, if I ssh over Ipv6 into the LXD Host, I can run `lxc ls` just fine. I can also control the LXD Host (6pai) remotely over IPv6 using:
```
lxc remote add pai 6pai
```
Then run commands such as:
``
lxc launch -p default -p extbridge pai:web_image w2
```

I can see that lxdMosiac is establishing a TCP/TLS connection to the LXD Host (using tcpdump) but since it is encrypted (with TLS) I can't see the payload. Is there a log in lxdMosaic which I can look at for the connection setup?

**Comment by turtle0x1** [comment]
Okay, straight up here I dont understand IPV6 to debug this fully, 

There is a bug with `parse_url` for ipv6 addresses, if you can tell me what my ipv6 address is from this `fe80::b014:f3ff:fe6b:98d3/64` then I can probably give it another shot

**Comment by cvmiller** [comment]
The fe80 is a link local address. If that is the only IPv6 address you have, then you really don't have much IPv6 on your network. Your IPv6 address from your example (of a link-local address) is:

`fe80::b014:f3ff:fe6b:98d3`

**Comment by turtle0x1** [comment]
Im in a coffe shop right now, so ipv6 may be limited, okay well if thats my address (and similar to the string you input to connect) then I can debug

**Comment by cvmiller** [comment]
I am putting in a hostname:port 'my_v6_host:8443' rather than an direct IPv6 address. The address must be resolved at some point. So your testing may differ. You could put in a host entry in your /etc/hosts file, and use that to test to more closely match my environment.

**Comment by bmullan** [comment]
@turtle0x1 - Craig is a great guy and very experienced in IPv6 while many of us have never had much involvement with it.   Hopefully, Craig can help you through what you don't know to get LXDMosaic to where he'd like to see it with the IPv6 support.

**Comment by cvmiller** [comment]
Looking into this a bit more, I see that the lxdMosaic client (from the firstRun webpage) does appear to be resolving the IPv6 host address correctly, and sends data to the LXD Host. However, it does not authenticate correctly.

I am wondering if there is a version issue here. I am running LXD 3.0.2 on my LXDHost. Is lxdMosaic expecting a higher version of LXD to talk to?

[wireshark pcap file attached]
[lxdMosaic_container.pcap.zip](https://github.com/turtle0x1/LxdMosaic/files/3562691/lxdMosaic_container.pcap.zip)

**Comment by turtle0x1** [comment]
So here are my debugging steps

 - IPV6 address of laptop `fdf1:ed47:8331:1:d167:5a85:1968:c7b1`
 - Edit `/etc/hosts` to include `fdf1:ed47:8331:1:d167:5a85:1968:c7b1 ipv6Host`

## Worked
 - Go to LXDMosaic add server input "ipv6Host" (notice lack of port number) + trust password
## Didn't work
 - Add server in LXDMosaic 
   - server input as "ipv6Host:8443" (notice port number) + trust password (error message: "Unable to parse URI: https:\/\/:8443")
    -  server input as "ipv6 address" (error message: "Host can not be empty")

Are you on a centos or ubuntu install of LXDMosaic ?

What is the error message you get back ?

The version of LXD shouldn't really matter

**Comment by cvmiller** [comment]
The part that didn't work is the problem I was originally reporting in this bug.

I am using Ubuntu Bionic on a Raspberry Pi 3B+. The error I get back is something like "can't connect to host"

I messed up my installation, and will have to reinstall. I'll let you know if the connect problem over IPv6 continues to exist

**Comment by turtle0x1** [comment]
Okay so this isn't ipv6 related (other than trying to input an ipv6 address, which is a separate thing) specifying the port causes an error (that it shouldn't)

**Comment by vitaly-t** [comment]
Correct IPv6 address specification is to be within `[]`, especially when with a port: `[]:port`. You probably tried open IPv6, hence the error.

**Comment by cvmiller** [comment]
Just to be clear @vitaly-t I was using a hostname which resolved to an IPv6 address e.g. my_v6_host:8443

When using hostnames, one does not need to use the square brackets.
