### ISSUE TITLE
LXDMosaic should have some sort of access control

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdMosaic#119]
**Is your feature request related to a problem? Please describe.**
To be used in production (enterprise or not) LXDMosaic should have some sort of access control limiting who is permitted to manage & orchestrate containers.

**Describe the solution you'd like**
Whatever is implemented for LXDMosaic should  also be able to be integrated with other systems.   Perhaps others might have some ideas here.

**Describe alternatives you've considered**
Perhaps PAM might work if there was a LXDMosaic "group" of permitted users. 

**Additional context**

**Comment by turtle0x1** [comment]
Authentication logic is complicated for two reasons;

 - How should we authenticate (Custom Auth, LDAP, PAM ETC)
 - What permission models we are going to offer

## Auth schemes
I use it in an small business environment where LDAP auth (active directory) is the sensible choice but this wont work for 99% home users, it will also significantly raise the barrier to entry for new developers. 

I would probably copy the `rocket-chat` model which uses its own database which can create its own users and import users from other providers.

Other than LDAP (+ mysql auth for individual operators), authentication schemes don't interest me as I wouldn't use them, so they would need to be implemented by somebody else. 

## Permission models

Different people are going to want to different things from this, some people will want fine grain control down to:

 - Specific containers
 - Specific profiles 
 - Container creation 

But I suspect the majority of users will be in a "single user mode" and wont any sort of restrictions. 

## Give your input 

Directing my time and effort for my open source efforts is the most important thing for me, authentication (or lack of) is clearly holding this application back, but I don't want to write the wrong thing. 

Let me know here if you have any kind of specific ask (not just basic auth) other wise that is likely what is going to happen~

**Comment by shemgp** [comment]
I think that since the app is like a frontend to lxc/lxd, that the users can be the users that can run lxc, and the capabilities are the capabilities that those users can do.  So that there won't be any need of LDAP or database users. Kind of like what [cockpit io](https://cockpit-project.org/) does.

**Comment by turtle0x1** [comment]
Reading [the docs](https://cockpit-project.org/guide/latest/authentication.html) it would appear cockpit.io has been to installed on a sever to manage it, LXDMosaic doesnt, so it cant use PAM!

**Comment by shemgp** [comment]
Yes, for "Primary server authentication" it needs to be installed in the server, but for [ Secondary server authentication](https://cockpit-project.org/guide/latest/authentication.html#secondary-auth), it doesn't. So maybe the app could use `ssh` for authentication and verify if the user is in `lxd` group?

Upon researching on this more:
It's not actually recommended to use `core.trust_password` for [production setups](https://lxd.readthedocs.io/en/latest/security/#production-setup). So maybe using [Candid](https://ubuntu.com/tutorials/candid-authentication-lxd#1-overview) is the way to go?

**Comment by turtle0x1** [comment]
currently LXDMosaic only uses HTTP to connect to hosts, once we require SSH to manage to hosts, this is no longer just LXDMosaic, its a weird inbetween tool. If you goto the work of connecting over ssh to the hosts for auth you might aswell offer other management tools, its also more work for network admins.

You could if you wanted to unset the core password for LXD once you have added it to LXDMosaic (it acts in the same way as the LXC command)

**Comment by SkipTam** [comment]
Yes this is a very nice panel. But since i use LXD on VPSs with a public ipv4 and ipv6 this really is a deal Breaker for me. It would be awesome to have a login screen with bash users which have access to lxc on the Server. SSH conection to Hosts would be great too. Keep up the good work!
