### ISSUE TITLE
Create Container button will not use existing images in LXD

### ISSUE THREAD

**Issue by cvmiller** [turtle0x1/LxdMosaic#122]
**Describe the bug**
Clicking the green "Create Container" button opens a dialogue box where one can specify an image. Typing in a word, invokes searching, however the search does not find existing images on the LXD server.

**To Reproduce**
1. Click green "Create Container" button
2. Type "web" into Image blank
3. Observe that it doesn't find the web image (already existing)

**Expected behavior**
Expect to the image search to find existing images on the LXD host

**Screenshots**

Existing images on my system:
```
$ lxc image ls
+---------------+--------------+--------+-----------------------------------------------+--------+----------+-------------------------------+
|     ALIAS     | FINGERPRINT  | PUBLIC |                  DESCRIPTION                  |  ARCH  |   SIZE   |          UPLOAD DATE          |
+---------------+--------------+--------+-----------------------------------------------+--------+----------+-------------------------------+
| docker_image  | 1bc9e3b7d559 | no     |                                               | armv7l | 258.70MB | Dec 6, 2018 at 2:30am (UTC)   |
+---------------+--------------+--------+-----------------------------------------------+--------+----------+-------------------------------+
| openwrt_armhf | eae3ea753336 | no     | OpenWrt 18.06.1 from armvirt/32               | armv7l | 1.86MB   | Dec 19, 2018 at 5:06pm (UTC)  |
+---------------+--------------+--------+-----------------------------------------------+--------+----------+-------------------------------+
| openwrt_v1    | 227439f41f21 | no     |                                               | armv7l | 2.05MB   | Dec 19, 2018 at 7:17pm (UTC)  |
+---------------+--------------+--------+-----------------------------------------------+--------+----------+-------------------------------+
| openwrt_v2    | f9b35c54ed71 | no     |                                               | armv7l | 2.05MB   | Dec 21, 2018 at 12:18am (UTC) |
+---------------+--------------+--------+-----------------------------------------------+--------+----------+-------------------------------+
| openwrt_v3    | fec7e71d1dbc | no     |                                               | armv7l | 2.45MB   | Dec 24, 2018 at 1:55am (UTC)  |
+---------------+--------------+--------+-----------------------------------------------+--------+----------+-------------------------------+
| web_image     | 84a4b1f466ad | yes    |                                               | armv7l | 12.86MB  | Dec 4, 2018 at 2:46am (UTC)   |
+---------------+--------------+--------+-----------------------------------------------+--------+----------+-------------------------------+
|               | a85cab7f1c67 | no     | ubuntu 18.04 LTS armhf (release) (20190813.1) | armv7l | 163.77MB | Sep 3, 2019 at 2:35pm (UTC)   |
+---------------+--------------+--------+-----------------------------------------------+--------+----------+-------------------------------+

```
As you can see there is an image called "web_image". I was trying to create a new container using that image (it is a Alpine image with nginx installed)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] "Ubuntu 18.04.1 LTS" running on Raspberry Pi
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] v52.02

**Additional context**
I am managing lxdMosaic over IPv6, which is working well.

**Comment by turtle0x1** [comment]
If i recall correctly the image must exist on all servers that are being managed by LXDMosaic,

This is because its currently does not support copying images accross severs for deploying a container

**Comment by cvmiller** [comment]
As it happens I have copied those images over (using the lxd cli). So it does exist on both LXD hosts I am using. The "web_image" even has the same finger print on both LXD hosts.

LXD does allow launching remote containers using a "local" container, which is what I was expecting lxdMosaic to do. The "?" talks about "importing" an image, but it doesn't seem to make sense that you would import you own preconfigured images. 

Is it possible to override the field, and bypass the "search" by putting my_v6_host:image_name ?

**Comment by turtle0x1** [comment]
So does it find the image when its on both severs? 

Also prehaps but its difficult because you have to add the remote to lxc i believe and im not sure it can be done with LXD, so if it isnt already a remote it will fail!

**Comment by cvmiller** [comment]
No, unfortunately, it doesn't find the image. In fact, the funny thing is that the search only shows me ONE image, the ubuntu image that lxdMosiac is built on.

> Also prehaps but its difficult because you have to add the remote to lxc i believe and im not sure it can be done with LXD, so if it isnt already a remote it will fail!

Let me describe my setup a bit more.
I have 2 Pi's running LXD. One is on a test network, the other in my DMZ, both are accessible from lxdMosiac via IPv6.
Pi1 (on the text network) has Pi2 configured as a "remote"
Pi2 (in the DMZ) has nothing in its "remote" since it can't get to the test network (blocked by firewalls)
lxdMosaic is managing BOTH of the Pi's by "adding a Host" method in lxdMosaic
lxdMosaic is running in a container off of Pi1 (on the test network)

Since I am asking lxdMosiac to create containers on Pi1 and Pi2,  with an image that is on (in this case) both LXD hosts, I was expecting lxdMosaic to go off and create containers with ONE of the web_image(s).

I am assuming that lxdMosaic is just another LXD client, the way the "lxc" command is just a LXD client. Perhaps it is not, and lxdMosaic is not making api calls to the LXD host, but is just driving it with CLI in the background. Please explain a bit more how lxdMosaic controls LXD hosts.

**Comment by turtle0x1** [comment]
Okay then this is a bug, currently I only have on machine on me so ill have to fix this in a couple of days when im back at home, sorry about the delay :heart:

**Comment by turtle0x1** [comment]
Okay I have taken a look at the code if the image doesn't have the key "update_source" then it won't appear, I think this check is now redundant but I will have to investigate, it will probably be tomorrow I fix this

**Comment by turtle0x1** [comment]
Should be fixed in  2a21da293da6e4f9401a9dfd7ee72813e03cabb8

**Comment by justmeandopensource** [comment]
Hi,

Is this broken again?
I am using the latest release 0.9.0 and I couldn't get the images listed or searched while creating a container. All I have is one standalone host where I have the image downloaded.

Thanks,
Venkat

**Comment by turtle0x1** [comment]
Hmm okay ill take a browse and issue a fix later today 😊
