### ISSUE TITLE
Node: HTTPS Cert location

### ISSUE THREAD

**Issue by turtle0x1** [turtle0x1/LxdMosaic#13]
Currently the HTTPS certs are hard coded, could perhaps hide wss behind some nginx reverse property?

**Comment by turtle0x1** [comment]
The solution will be to load them through environment variables !

**Comment by lhorace** [comment]
Yeah,I run my own PKI here! If fact, I had to hunt through the code to amend the location.

**Comment by turtle0x1** [comment]
You use a custom location for the certificates ?

**Comment by lhorace** [comment]
No, they are in the same place as the self-signed ones, I just preferred my naming scheme over `snakeoil` so I can easily recognize them. All my other servers/container have certs in varied locations though, so specifying location could be useful.

**Comment by turtle0x1** [comment]
- [ ] Write wiki 
 - [ ] Update node script
