### ISSUE TITLE
Add support to manage Hosts/Servers

### ISSUE THREAD

**Issue by knippers** [turtle0x1/LxdMosaic#135]
It is really easy to add a server/host but there is no option (other than to go into the lxdmosaic container and update the mysql table) to manage the servers/hosts from the UI. A simple server/hosts page under settings would be nice.

Update: looking at closed issues this seems to be possible already. However I cannot find the option in the UI to do so.

**Comment by turtle0x1** [comment]
You can click on a link to any particular host (on the homepage & the breadcrumbs when you click on a container) and it will probably show you what you want to see, let me know any more specific functionality you need!
