### ISSUE TITLE
Question: is running Mosaic behind NAT rule supported?

### ISSUE THREAD

**Issue by knippers** [turtle0x1/LxdMosaic#136]
I run Mosaic on a container on LXD which is running behind an OPNSense VM. LXD and Containers get their IP from OPNSense DHCP. The "WAN" side of OPNSense is connected to our LAN. I have configured an LAN IP (the WAN side) -> OPNSense -> LAN (the internal network) NAT port forward. Mosaic seems to work but I do not get any active container info. I can see some items (e.g. network names, storage and profile names).

**Comment by turtle0x1** [comment]
Hmm this is interesting, are you using centos or ubuntu install ?

**Comment by knippers** [comment]
I am using the Ubuntu install on an 18.04 Ubuntu server with LXD.

**Comment by knippers** [comment]
Maybe different compared to the standard lxd install is the use of the OS bridge to get IP addresses form the network DHCP instead of from the container network itself

**Comment by knippers** [comment]
There are only 11 containers running on a host that is itself a vm on esxi. The logs get pretty full quick when I try to open the console from the UI. Other than that not much to see. Last lines;
```
[Wed Oct 30 20:15:14.580532 2019] [proxy_http:error] [pid 272] [client 192.168.1.17:55140] AH01114: HTTP: failed to make connection to backend: localhost, referer: https://192.168.0.78/
[Wed Oct 30 20:15:14.669486 2019] [proxy:error] [pid 856] (111)Connection refused: AH00957: WSS: attempt to connect to 127.0.0.1:3000 (*) failed
[Wed Oct 30 20:15:14.669544 2019] [proxy_wstunnel:error] [pid 856] [client 192.168.1.17:55142] AH02452: failed to make connection to backend: localhost
```
To be sure, what ports need to be opened on the firewall? I assumed only https, but I also added 80, 3000 and 8001 (as I see something listening on that on the container).

**Comment by turtle0x1** [comment]
I think thats a seprate issue it should effect showing hosts, can you press `f12` change to requests tab and then xhr, see if you get any error responses? 

At this point in time im not super interested in setting up these more involved network scenarios so i cant debug in my env but im happy to connect over teamviever or ssh and take a look if it works for you!

**Comment by knippers** [comment]
This is what i seen in the developer console;
index.js:83 XHR finished loading: GET "https://192.168.0.78/socket.io/?EIO=3&transport=polling&t=MuZHpUl".
index.js:83 XHR finished loading: POST "https://192.168.0.78/socket.io/?EIO=3&transport=polling&t=MuZHpVV&sid=RLRGQURh90kyJgqHAAAC".
index.js:83 XHR finished loading: GET "https://192.168.0.78/socket.io/?EIO=3&transport=polling&t=MuZHpVY&sid=RLRGQURh90kyJgqHAAAC".
index.js:83 XHR finished loading: GET "https://192.168.0.78/socket.io/?EIO=3&transport=polling&t=MuZHpWB&sid=RLRGQURh90kyJgqHAAAC".
jquery-3.3.1.min.js:2 XHR finished loading: POST "https://192.168.0.78/api/Hosts/Containers/GetAllController/getAll".
(index):5586 Uncaught TypeError: Cannot read property 'supportsProjects' of undefined
    at String.<anonymous> ((index):5586)
    at Function.each (jquery-3.3.1.min.js:2)
    at (index):5557
    at Object.success (globalFunctions.js:80)
    at u (jquery-3.3.1.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-3.3.1.min.js:2)
    at k (jquery-3.3.1.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery-3.3.1.min.js:2)
jquery-3.3.1.min.js:2 XHR finished loading: POST "https://192.168.0.78/api/Hosts/GetOverviewController/get".
jquery-3.3.1.min.js:2 XHR finished loading: POST "https://192.168.0.78/api/AnalyticData/GetLatestDataController/get".

**Comment by turtle0x1** [comment]
```
(index):5586 Uncaught TypeError: Cannot read property 'supportsProjects' of undefined
at String. ((index):5586)
```
What browser are you running ?

**Comment by knippers** [comment]
Chrome (build 78). Also tested wirth Firefox, which only gives the following error in the console;
TypeError: data.extensions is undefined

Behaviour is the same in both browsers.

**Comment by turtle0x1** [comment]
Can you open firefox dev tools again click network and then xhr refresh the page and you should see the failing request click it and then click response to see what the server is sending back

**Comment by knippers** [comment]
None of the xhr requests actually fail:
![image](https://user-images.githubusercontent.com/69477/68026329-b2c14e00-fcaf-11e9-99cb-91c0e36810bb.png)
any of the calls you would like to get the details from?

**Comment by turtle0x1** [comment]
`getAll` and the `get` requests please, what version are the LXD hosts + are they clustered?

**Comment by knippers** [comment]
Version 3.0.3 of LXD and they are not clustered.
`{
  "log": {
    "version": "1.2",
    "creator": {
      "name": "Firefox",
      "version": "70.0.1"
    },
    "browser": {
      "name": "Firefox",
      "version": "70.0.1"
    },
    "pages": [
      {
        "startedDateTime": "2019-11-01T15:22:58.902+01:00",
        "id": "page_2",
        "pageTimings": {
          "onContentLoad": 826,
          "onLoad": 897
        }
      }
    ],
    "entries": [
      {
        "pageref": "page_2",
        "startedDateTime": "2019-11-01T15:22:59.083+01:00",
        "request": {
          "bodySize": 0,
          "method": "POST",
          "url": "https://192.168.0.78/api/Hosts/Containers/GetAllController/getAll",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "192.168.0.78"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "X-Requested-With",
              "value": "XMLHttpRequest"
            },
            {
              "name": "Origin",
              "value": "https://192.168.0.78"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Referer",
              "value": "https://192.168.0.78/"
            },
            {
              "name": "Cookie",
              "value": "PHPSESSID=7le8do7rmb0pf4u2csj4s8pqsv; io=O3j_FvOQ-qSeVlG4AAAD"
            },
            {
              "name": "Content-Length",
              "value": "0"
            }
          ],
          "cookies": [
            {
              "name": "PHPSESSID",
              "value": "7le8do7rmb0pf4u2csj4s8pqsv"
            },
            {
              "name": "io",
              "value": "O3j_FvOQ-qSeVlG4AAAD"
            }
          ],
          "queryString": [],
          "headersSize": 467
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Fri, 01 Nov 2019 14:22:59 GMT"
            },
            {
              "name": "Server",
              "value": "Apache/2.4.29 (Ubuntu)"
            },
            {
              "name": "Cache-Control",
              "value": "max-age=0, private, must-revalidate"
            },
            {
              "name": "Vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "Content-Encoding",
              "value": "gzip"
            },
            {
              "name": "Content-Length",
              "value": "4194"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=5, max=97"
            },
            {
              "name": "Connection",
              "value": "Keep-Alive"
            },
            {
              "name": "Content-Type",
              "value": "text/html; charset=UTF-8"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/html; charset=UTF-8",
            "size": 9071,
            "text": "{\"LXD2\":{\"online\":true,\"hostId\":\"2\",\"containers\":[],\"hostInfo\":{\"config\":{\"core.https_address\":\"[::]:8443\",\"core.trust_password\":true},\"api_extensions\":[\"storage_zfs_remove_snapshots\",\"container_host_shutdown_timeout\",\"container_stop_priority\",\"container_syscall_filtering\",\"auth_pki\",\"container_last_used_at\",\"etag\",\"patch\",\"usb_devices\",\"https_allowed_credentials\",\"image_compression_algorithm\",\"directory_manipulation\",\"container_cpu_time\",\"storage_zfs_use_refquota\",\"storage_lvm_mount_options\",\"network\",\"profile_usedby\",\"container_push\",\"container_exec_recording\",\"certificate_update\",\"container_exec_signal_handling\",\"gpu_devices\",\"container_image_properties\",\"migration_progress\",\"id_map\",\"network_firewall_filtering\",\"network_routes\",\"storage\",\"file_delete\",\"file_append\",\"network_dhcp_expiry\",\"storage_lvm_vg_rename\",\"storage_lvm_thinpool_rename\",\"network_vlan\",\"image_create_aliases\",\"container_stateless_copy\",\"container_only_migration\",\"storage_zfs_clone_copy\",\"unix_device_rename\",\"storage_lvm_use_thinpool\",\"storage_rsync_bwlimit\",\"network_vxlan_interface\",\"storage_btrfs_mount_options\",\"entity_description\",\"image_force_refresh\",\"storage_lvm_lv_resizing\",\"id_map_base\",\"file_symlinks\",\"container_push_target\",\"network_vlan_physical\",\"storage_images_delete\",\"container_edit_metadata\",\"container_snapshot_stateful_migration\",\"storage_driver_ceph\",\"storage_ceph_user_name\",\"resource_limits\",\"storage_volatile_initial_source\",\"storage_ceph_force_osd_reuse\",\"storage_block_filesystem_btrfs\",\"resources\",\"kernel_limits\",\"storage_api_volume_rename\",\"macaroon_authentication\",\"network_sriov\",\"console\",\"restrict_devlxd\",\"migration_pre_copy\",\"infiniband\",\"maas_network\",\"devlxd_events\",\"proxy\",\"network_dhcp_gateway\",\"file_get_symlink\",\"network_leases\",\"unix_device_hotplug\",\"storage_api_local_volume_handling\",\"operation_description\",\"clustering\",\"event_lifecycle\",\"storage_api_remote_volume_handling\",\"nvidia_runtime\",\"candid_authentication\",\"candid_config\",\"candid_config_key\",\"usb_optional_vendorid\"],\"api_status\":\"stable\",\"api_version\":\"1.0\",\"auth\":\"trusted\",\"public\":false,\"auth_methods\":[\"tls\"],\"environment\":{\"addresses\":[\"192.168.200.86:8443\"],\"architectures\":[\"x86_64\",\"i686\"],\"certificate\":\"-----BEGIN CERTIFICATE-----***-----END CERTIFICATE-----\\n\",\"certificate_fingerprint\":\"***\",\"driver\":\"lxc\",\"driver_version\":\"3.0.3\",\"kernel\":\"Linux\",\"kernel_architecture\":\"x86_64\",\"kernel_version\":\"4.15.0-66-generic\",\"server\":\"lxd\",\"server_pid\":16144,\"server_version\":\"3.0.3\",\"storage\":\"zfs\",\"storage_version\":\"0.7.5-1ubuntu16.6\",\"server_clustered\":false,\"server_name\":\"ttxv11\",\"project\":\"\"}}},\"LXD1\":{\"online\":true,\"hostId\":\"1\",\"containers\":[],\"hostInfo\":{\"config\":{\"core.https_address\":\"[::]:8443\",\"core.trust_password\":true},\"api_extensions\":[\"storage_zfs_remove_snapshots\",\"container_host_shutdown_timeout\",\"container_stop_priority\",\"container_syscall_filtering\",\"auth_pki\",\"container_last_used_at\",\"etag\",\"patch\",\"usb_devices\",\"https_allowed_credentials\",\"image_compression_algorithm\",\"directory_manipulation\",\"container_cpu_time\",\"storage_zfs_use_refquota\",\"storage_lvm_mount_options\",\"network\",\"profile_usedby\",\"container_push\",\"container_exec_recording\",\"certificate_update\",\"container_exec_signal_handling\",\"gpu_devices\",\"container_image_properties\",\"migration_progress\",\"id_map\",\"network_firewall_filtering\",\"network_routes\",\"storage\",\"file_delete\",\"file_append\",\"network_dhcp_expiry\",\"storage_lvm_vg_rename\",\"storage_lvm_thinpool_rename\",\"network_vlan\",\"image_create_aliases\",\"container_stateless_copy\",\"container_only_migration\",\"storage_zfs_clone_copy\",\"unix_device_rename\",\"storage_lvm_use_thinpool\",\"storage_rsync_bwlimit\",\"network_vxlan_interface\",\"storage_btrfs_mount_options\",\"entity_description\",\"image_force_refresh\",\"storage_lvm_lv_resizing\",\"id_map_base\",\"file_symlinks\",\"container_push_target\",\"network_vlan_physical\",\"storage_images_delete\",\"container_edit_metadata\",\"container_snapshot_stateful_migration\",\"storage_driver_ceph\",\"storage_ceph_user_name\",\"resource_limits\",\"storage_volatile_initial_source\",\"storage_ceph_force_osd_reuse\",\"storage_block_filesystem_btrfs\",\"resources\",\"kernel_limits\",\"storage_api_volume_rename\",\"macaroon_authentication\",\"network_sriov\",\"console\",\"restrict_devlxd\",\"migration_pre_copy\",\"infiniband\",\"maas_network\",\"devlxd_events\",\"proxy\",\"network_dhcp_gateway\",\"file_get_symlink\",\"network_leases\",\"unix_device_hotplug\",\"storage_api_local_volume_handling\",\"operation_description\",\"clustering\",\"event_lifecycle\",\"storage_api_remote_volume_handling\",\"nvidia_runtime\",\"candid_authentication\",\"candid_config\",\"candid_config_key\",\"usb_optional_vendorid\"],\"api_status\":\"stable\",\"api_version\":\"1.0\",\"auth\":\"trusted\",\"public\":false,\"auth_methods\":[\"tls\"],\"environment\":{\"addresses\":[\"192.168.200.52:8443\"],\"architectures\":[\"x86_64\",\"i686\"],\"certificate\":\"-----BEGIN CERTIFICATE-----***-----END CERTIFICATE-----\\n\",\"certificate_fingerprint\":\"***\",\"driver\":\"lxc\",\"driver_version\":\"3.0.3\",\"kernel\":\"Linux\",\"kernel_architecture\":\"x86_64\",\"kernel_version\":\"4.15.0-65-generic\",\"server\":\"lxd\",\"server_pid\":1875,\"server_version\":\"3.0.3\",\"storage\":\"zfs\",\"storage_version\":\"0.7.5-1ubuntu16.6\",\"server_clustered\":false,\"server_name\":\"ttxv10\",\"project\":\"\"}}}}"
          },
          "redirectURL": "",
          "headersSize": 304,
          "bodySize": 4498
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 0,
          "wait": 1320,
          "receive": 0
        },
        "time": 1320,
        "_securityState": "secure",
        "serverIPAddress": "192.168.0.78",
        "connection": "443"
      },
      {
        "pageref": "page_2",
        "startedDateTime": "2019-11-01T15:22:59.084+01:00",
        "request": {
          "bodySize": 0,
          "method": "POST",
          "url": "https://192.168.0.78/api/AnalyticData/GetLatestDataController/get",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "192.168.0.78"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "X-Requested-With",
              "value": "XMLHttpRequest"
            },
            {
              "name": "Origin",
              "value": "https://192.168.0.78"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Referer",
              "value": "https://192.168.0.78/"
            },
            {
              "name": "Cookie",
              "value": "PHPSESSID=7le8do7rmb0pf4u2csj4s8pqsv; io=O3j_FvOQ-qSeVlG4AAAD"
            },
            {
              "name": "Content-Length",
              "value": "0"
            }
          ],
          "cookies": [
            {
              "name": "PHPSESSID",
              "value": "7le8do7rmb0pf4u2csj4s8pqsv"
            },
            {
              "name": "io",
              "value": "O3j_FvOQ-qSeVlG4AAAD"
            }
          ],
          "queryString": [],
          "headersSize": 467
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Fri, 01 Nov 2019 14:22:59 GMT"
            },
            {
              "name": "Server",
              "value": "Apache/2.4.29 (Ubuntu)"
            },
            {
              "name": "Cache-Control",
              "value": "max-age=0, private, must-revalidate"
            },
            {
              "name": "Content-Length",
              "value": "57"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=5, max=97"
            },
            {
              "name": "Connection",
              "value": "Keep-Alive"
            },
            {
              "name": "Content-Type",
              "value": "text/html; charset=UTF-8"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/html; charset=UTF-8",
            "size": 57,
            "text": "{\"warning\":\"Not Enough Data, 10 minutes is minimum time\"}"
          },
          "redirectURL": "",
          "headersSize": 255,
          "bodySize": 312
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 0,
          "wait": 1347,
          "receive": 1
        },
        "time": 1348,
        "_securityState": "secure",
        "serverIPAddress": "192.168.0.78",
        "connection": "443"
      },
      {
        "pageref": "page_2",
        "startedDateTime": "2019-11-01T15:22:59.084+01:00",
        "request": {
          "bodySize": 0,
          "method": "POST",
          "url": "https://192.168.0.78/api/Hosts/GetOverviewController/get",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Host",
              "value": "192.168.0.78"
            },
            {
              "name": "User-Agent",
              "value": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
            },
            {
              "name": "Accept",
              "value": "*/*"
            },
            {
              "name": "Accept-Language",
              "value": "en-US,en;q=0.5"
            },
            {
              "name": "Accept-Encoding",
              "value": "gzip, deflate, br"
            },
            {
              "name": "X-Requested-With",
              "value": "XMLHttpRequest"
            },
            {
              "name": "Origin",
              "value": "https://192.168.0.78"
            },
            {
              "name": "Connection",
              "value": "keep-alive"
            },
            {
              "name": "Referer",
              "value": "https://192.168.0.78/"
            },
            {
              "name": "Cookie",
              "value": "PHPSESSID=7le8do7rmb0pf4u2csj4s8pqsv; io=O3j_FvOQ-qSeVlG4AAAD"
            },
            {
              "name": "Content-Length",
              "value": "0"
            }
          ],
          "cookies": [
            {
              "name": "PHPSESSID",
              "value": "7le8do7rmb0pf4u2csj4s8pqsv"
            },
            {
              "name": "io",
              "value": "O3j_FvOQ-qSeVlG4AAAD"
            }
          ],
          "queryString": [],
          "headersSize": 458
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "headers": [
            {
              "name": "Date",
              "value": "Fri, 01 Nov 2019 14:22:59 GMT"
            },
            {
              "name": "Server",
              "value": "Apache/2.4.29 (Ubuntu)"
            },
            {
              "name": "Cache-Control",
              "value": "max-age=0, private, must-revalidate"
            },
            {
              "name": "Vary",
              "value": "Accept-Encoding"
            },
            {
              "name": "Content-Encoding",
              "value": "gzip"
            },
            {
              "name": "Content-Length",
              "value": "129"
            },
            {
              "name": "Keep-Alive",
              "value": "timeout=5, max=99"
            },
            {
              "name": "Connection",
              "value": "Keep-Alive"
            },
            {
              "name": "Content-Type",
              "value": "text/html; charset=UTF-8"
            }
          ],
          "cookies": [],
          "content": {
            "mimeType": "text/html; charset=UTF-8",
            "size": 129,
            "text": "{\"state\":\"error\",\"message\":\"cURL error 52: Empty reply from server (see http:\\/\\/curl.haxx.se\\/libcurl\\/c\\/libcurl-errors.html)\"}"
          },
          "redirectURL": "",
          "headersSize": 303,
          "bodySize": 432
        },
        "cache": {},
        "timings": {
          "blocked": 0,
          "dns": 0,
          "connect": 0,
          "ssl": 0,
          "send": 0,
          "wait": 1347,
          "receive": 0
        },
        "time": 1347,
        "_securityState": "secure",
        "serverIPAddress": "192.168.0.78",
        "connection": "443"
      }
    ]
  }
}`

I left out certificate and fingerprint info (replaced with ***). Also to note I have no IPV6 setup on the VM or NAT Router. It is still enabled on the LXD Hosts (but I can probably disable it there as well).

**Comment by turtle0x1** [comment]
`cURL error 52: Empty reply from server` this is the error that matters, 

[According to this](https://stackoverflow.com/questions/1924434/curl-error-52-empty-reply-from-server) its likely that your network setup isn't quite right, can the LXDMosaic container reach all the hosts its trying to manage ?

**Comment by knippers** [comment]
The LXDMosaic container can reach both of the LXD hosts.

```shellscript
mysql> select * from Hosts;
+---------+-----------------------------+-------------------------+---------------------+--------------------+-------------+------------+
| Host_ID | Host_Url_And_Port           | Host_Cert_Path          | Host_Cert_Only_File | Host_Key_File      | Host_Online | Host_Alias |
+---------+-----------------------------+-------------------------+---------------------+--------------------+-------------+------------+
|       1 | https://192.168.200.52:8443 | 192.168.200.52.combined | 192.168.200.52.cert | 192.168.200.52.key |           1 | LXD1       |
|       2 | https://192.168.200.86:8443 | 192.168.200.86.combined | 192.168.200.86.cert | 192.168.200.86.key |           1 | LXD2       |
+---------+-----------------------------+-------------------------+---------------------+--------------------+-------------+------------+
```

```
root@lxdMosaic:/var/www/LxdMosaic# curl -k https://192.168.200.52:8443
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":["/1.0"]}
root@lxdMosaic:/var/www/LxdMosaic# curl -k https://192.168.200.86:8443
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":["/1.0"]}
```

**Comment by turtle0x1** [comment]
Okay, ill need access to work out whats going on sorry about that curl 52 is pretty non specific (not your fault)

**Comment by knippers** [comment]
Getting you access will be difficult. However I went into more detail via code to find out it is effectively the API call to /1.0/resources that is failing. This is also the case with curl (remote and local on LXD host with sockets).

On LXD host:
```bash
curl --unix-socket /var/lib/lxd/unix.socket s/1.0/resources
curl: (52) Empty reply from server
```
And from LXDMosaic:
```bash
root@lxdMosaic:~# curl --http1.1 -i -v -H -s -k --cert /var/www/LxdMosaic/src/sensitiveData/certs/192.168.200.52.cert --key /var/www/LxdMosaic/src/sensitiveData/certs/192.168.200.52.key https://192.168.200.52:8443/1.0/resources
*   Trying 192.168.200.52...
* TCP_NODELAY set
* Connected to 192.168.200.52 (192.168.200.52) port 8443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS handshake, CERT verify (15):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: O=linuxcontainers.org; CN=root@ttxv10
*  start date: Oct 14 13:23:01 2019 GMT
*  expire date: Oct 11 13:23:01 2029 GMT
*  issuer: O=linuxcontainers.org; CN=root@ttxv10
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /1.0/resources HTTP/1.1
> Host: 192.168.200.52:8443
> User-Agent: curl/7.58.0
> Accept: */*
>
* TLSv1.2 (IN), TLS alert, Client hello (1):
* Empty reply from server
* Connection #0 to host 192.168.200.52 left intact
curl: (52) Empty reply from server
```
Now I am puzzled why there is no response. Did a quick Google on it but no obvious answer. Also the LXD server log does not show much (it does show when for example calling /1.0/resourcesfake).

**Comment by knippers** [comment]
I think it is solved. I upgraded from the apt-get LXD (which is on version 3.0.3) to the snap version (which is on 3.18). The boxes are Ubuntu LTS 18.04. 
Also running the `lxc info --resources` command gave no results (this command should be about equal to the resources endpoint).

**Comment by turtle0x1** [comment]
Oh okay, that might do it, I do try to support the 3.0.3 version so ill try to duplicate this when I have time,

Sorry about my slow responses on this, its been mega busy at work :heart:
