### ISSUE TITLE
Do not list containers on hosts

### ISSUE THREAD

**Issue by boblehue** [turtle0x1/LxdMosaic#137]
**Describe the bug**
Clean install and added hosts but report "There are no containers on the host" on every host added. 

I can list containers from lxdmosaic server by adding remote host (lxc remote add) and run lxc list "host":
Creating a container from the lxdmosaic web interface also work but still report "There are no containers on the host".

Had lxdmosaic working fine on a earlier version,

**To Reproduce**
Run install scrip on ubuntu server and add host.

**Expected behavior**
Showing all existing containers,

**Screenshots**
![image](https://user-images.githubusercontent.com/42911496/69015637-247ae680-0996-11ea-8101-8aedafd04efd.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu server 18.04 on Hyper-v and as a container.
 - Browser chrome, edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by turtle0x1** [comment]
Lxd version?

**Comment by boblehue** [comment]
All host's and the lxdmosaic server : 
lxd --version
3.0.3

**Comment by boblehue** [comment]
FYI, had the same behaviour when upgrading from the older version of lxdmosaic and was the reason for a fresh install.

**Comment by turtle0x1** [comment]
Okay ill take a look at this later, its probably because im using an API call that doesn't exist in 3.0.3 probably introduced by clustering!

**Comment by boblehue** [comment]
Another FYI. :-) 

I upgraded one host to use snap lxd version 3.18 and magic happen. :-D
This was a host used for test so i could try this out, but i'm a bit more sceptic to do the same on hosts with live containers despite the fact that the upgrade went without problems  So if you can implement support for api in 3.0.3 i will be a happy camper. Will do the change on the other hosts later to support future services, but not before testing some more.

**Comment by turtle0x1** [comment]
Fixed in 258fe4042e66368b0de6c64a7b01b19da4833e60
