### ISSUE TITLE
LxdMosaic update 

### ISSUE THREAD

**Issue by consultit** [turtle0x1/LxdMosaic#141]
**Is your feature request related to a problem? Please describe.**
Is there a procedure to update LxdMosaic safely without reinstalling it every time?
From documentation it seems possible only a new installation to update .
Thanks

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by turtle0x1** [comment]
Have you seen https://github.com/turtle0x1/LxdMosaic/blob/master/UPGRADING.md

**Comment by consultit** [comment]
Sorry I didn't see it!
Thanks
