### ISSUE TITLE
Indicate Host Cluster Group On Dashboard

### ISSUE THREAD

**Issue by tonyanytime** [turtle0x1/LxdMosaic#150]
Q0 and Q9 are one cluster
and Q1,Q2,Q3,Q4 are another cluster... No way to tell them apart or grouping
Good News when I added first server in Q1 it detected all the way to Q4
Rename Containers, and Alias to Server works well if not immediate, required refresh but was good

![Screenshot from 2020-02-12 19-35-15](https://user-images.githubusercontent.com/17663943/74394688-45a77380-4ddb-11ea-8803-5521f29f055b.png)

**Comment by turtle0x1** [comment]
Great, thank you for the feedback, I have modified the title to make it clear what im implementing and to preserve your input :smile:
