### ISSUE TITLE
Comments on Gui

### ISSUE THREAD

**Issue by tonyanytime** [turtle0x1/LxdMosaic#153]
Of the LXD Gui screens I have seen your is the best... but it could be better IMHO.
Putting the most best info on dashboard is the goal.  
I would reduce spacing and vertical size between boxes that are servers. Think 1U to your 2U
You could use width better and put IP and name in box in front CPU INFO
Make GPU info optional
On Left Overview panel, as mentioned before there is a bug and it disappears on occasion
In Drop down, Another level above Server should be Cluster, so it should be Cluster,Server,Container 
On top I would add a list option for Containers, where a list similar to a spread sheet like
lxc list  with IP etc... with hopefully selectable items. Why?
Because you have hundred of freaking containers this sortable list is your best friend, and you should be able to all the basic functions there.

![Screenshot from 2020-02-12 20-24-25](https://user-images.githubusercontent.com/17663943/74395469-6670c880-4ddd-11ea-9261-6cfaa4af32b6.png)

**Comment by turtle0x1** [comment]
Closed in #160
