### ISSUE TITLE
What do you recomment as a way to secure the site?

### ISSUE THREAD

**Issue by shemgp** [turtle0x1/LxdMosaic#154]
**Is your feature request related to a problem? Please describe.**
How do I secure the site so that only me can access it and not anyone in the network?

**Describe the solution you'd like**
The lxdMosaic virtual host is accessible from any browser in the network, it would be nice if there would be a security mechanism to limit who can access the site. eg. login/logout.

**Describe alternatives you've considered**
The fix I could think is to use apache2 digest passwords, but usually it only logs out when I close the browser.

**Comment by turtle0x1** [comment]
If you don't use any of the "advanced" features such as phoning home from containers you could use IP filtering to only allow your IP to connect to the Apache ports (80 & 443) you would also need to protect port  3000 for node, check out [this stackoverflow question](https://stackoverflow.com/questions/4400154/deny-all-allow-only-one-ip-through-htaccess)  to see how to do this in `.htaccess` which for `LxdMosaic` you can find here `/var/www/LxdMosaic/src/public/.htaccess`

#119 covers my general overview on this topic :smile:
