### ISSUE TITLE
include CI & update with the lxd api 

### ISSUE THREAD

**Issue by djverlinden** [turtle0x1/LxdMosaic#156]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by turtle0x1** [comment]
Pretty vague, care to elaberate?

**Comment by djverlinden** [comment]
haha you get the idea with CI and LXD-api ;-) (networking and nameservice can be a lot easier.)

I'll make  a description about it and how I would solve it.

**Comment by djverlinden** [comment]
ooo .. nice project!

I'll first install it properly and have it full working.

**Comment by turtle0x1** [comment]
Do you mean include unit tests ? The underlying library `php-lxd` may be better suited as this program just manipulates data to feed into `php-lxd`
