### ISSUE TITLE
400 Bad Request on container creation

### ISSUE THREAD

**Issue by shemgp** [turtle0x1/LxdMosaic#158]
**Describe the bug**
Getting 
```
Client error: `POST https://hidden.server:8443/1.0/instances?project=default` resulted in a `400 Bad Request` response: {"error":"json: cannot unmarshal array into Go struct field InstancesPost.devices of type map[string]map[string]string", (truncated...) /var/www/LxdMosaic/vendor/php-http/guzzle6-adapter/src/Promise.php 127 
```
when creating a container.

**To Reproduce**
1. install lxdMosaic 0.6.1
2. Click +Container
3. Fill up the needed items in the form
4. Click Create Container
3. See error

**Expected behavior**
Be able to create the container.

**Screenshots**
![Screenshot from 2020-03-07 22-09-40](https://user-images.githubusercontent.com/1734126/76145100-55a43180-60c1-11ea-9687-5e7df8951c6e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu Focal Fossa Development
 - Browser: Firefox
 - Version: lxdMosaic 0.6.1

**Server**
Ubuntu 18.04.4
LXD 3.22 snap

**Comment by turtle0x1** [comment]
Ill push a fix this evening (assuming its what i think it is) 😊
