### ISSUE TITLE
Install only the GUI

### ISSUE THREAD

**Issue by Drakunovu** [turtle0x1/LxdMosaic#159]
**Is your feature request related to a problem? Please describe.**
Install only the GUI without installing (again) the apache2, mysql and others.

**Describe the solution you'd like**
If you have installed those you can go right to the LXD thing, if not then you need to install it. Like leaving all the dependencies in a list to install.

**Describe alternatives you've considered**
None of one.

**Additional context**
Same of above

**Comment by turtle0x1** [comment]
In that case all you would need todo is clone this repository, instead of running the script, you will need to mannually setup apache & node yourself 😊

**Comment by turtle0x1** [comment]
Going close this as its not really clear what I can do beyond this!
