### ISSUE TITLE
Collection of bugs/issues

### ISSUE THREAD

**Issue by avsdev-cw** [turtle0x1/LxdMosaic#164]
One of the more feature full LXD front-ends, load of potential, but I've encountered a number of bugs of varying levels of seriousness.

Host: LXD Debian Buster container on a Debian Buster LXD snap host.
Client: Debian Bullseye, Firefox 72.0.1 (64 bit)
Version: v0.6.2

- ~~Memory stats tooltip always shows 0 bytes (even though the pie chart is proportional to memory use) [accessible by clicking the host name on the dashboard]~~
- ~~Dashboard charts consistently say "Not enough data check again in 10 minutes" (container has been up for over 24 hours)~~
- ~~Typo when clicking "Add Server": memebers~~
- ~~Sometimes the "Add Container" dialog gets stuck open (have not been able to find a way of reproducing, the console error log states "The modal is already in a state of transitioning"~~
  - this is a bootsrap issue, as  you said its very hard to reproduce, I have spent time trying to fix it, but to no luck! 
- ~~The API "api/Hosts/SearchHosts/search" comes back with an empty array no matter what the search term is~~
- ~~It would be more useful to default to showing a list of available options for drop-downs instead of requiring a search and then simply filter if the user types~~
 - Commented below
- ~~Cannot create/modify a cloud image with zero-length " Enviroment Variables "~~
- ~~View container, click "Files" and you get this error: `Call to a member function getHeaders() on null /var/www/LxdMosaic/src/classes/Tools/Containers/Files/GetPath.php 97`~~
- ~~Importing a backup fails with `Call to a member function hasWithHostId() on null /var/www/LxdMosaic/src/classes/Tools/Containers/Backups/StoreBackupLocally.php 42`~~
- ~~Console doesn't work~~
- ~~Type when editing a container's settings: update stragery~~
- ~~Some modals are not cleared of their previous contents when re-opened, (specifically the create/new modals)~~

Obviously without being able to select a host, I can't do any more testing!

**Comment by turtle0x1** [comment]
Awesome, thank you very much!

Some of these I have already fixed in #160 so I have put a strike through them, and I will probably strike through more as I do them :smile:

**Comment by turtle0x1** [comment]
@avsdev-cw 
You are running `LxdMosaic` in a ubuntu or centos container right ?

>Dashboard charts consistently say "Not enough data check again in 10 minutes" (container has been up for over 24 hours)

Can you go into the `LxdMosaic` container and run `php /var/www/LxdMosaic/src/cronJobs/fleetAnalytics.php` and paste any interesting output

**Comment by avsdev-cw** [comment]
Looks like the crontab wasn't installed properly for some reason. That one can be struck off I think

**Comment by turtle0x1** [comment]
Hm, did you manually install ? Id want to investigate further if not!

**Comment by avsdev-cw** [comment]
Probably would be beneficial to add cron to the list of dependencies!

**Comment by turtle0x1** [comment]
> Console doesn't work

Can you again go into the container and run `pm2 list` if the app has loads of errors (or report back if  isn't any apps)

**Comment by avsdev-cw** [comment]
```
root@lxd-mosaic:~# pm2 list
┌─────┬───────────┬─────────────┬─────────┬─────────┬──────────┬────────┬──────┬───────────┬──────────┬──────────┬──────────┬──────────┐
│ id  │ name      │ namespace   │ version │ mode    │ pid      │ uptime │ ↺    │ status    │ cpu      │ mem      │ user     │ watching │
├─────┼───────────┼─────────────┼─────────┼─────────┼──────────┼────────┼──────┼───────────┼──────────┼──────────┼──────────┼──────────┤
│ 0   │ events    │ default     │ 1.0.0   │ fork    │ 278      │ 6h     │ 0    │ online    │ 0.4%     │ 62.7mb   │ root     │ disabled │
└─────┴───────────┴─────────────┴─────────┴─────────┴──────────┴────────┴──────┴───────────┴──────────┴──────────┴──────────┴──────────┘

```

**Comment by turtle0x1** [comment]
Hmm that looks right, console appears to work fine on a default install, any warnings in the browser console ? What OS in the container your connecting to (alpine needs `ash` as the shell)

**Comment by avsdev-cw** [comment]
That would probably be the problem, `ash` isn't installed.

The container is using an image from linuxcontainers.org: `debian | buster | amd64 | default`

**Comment by turtle0x1** [comment]
Im so confused as to what your setup is right now;

The container with `LxdMosaic` doesn't need `ash` installed (or it shouldn't, which OS is `LxdMosaic` running in ?)

**Comment by avsdev-cw** [comment]
Host server (ie, physical server) OS: Debian Buster amd64 net-install
lxd-mirage is installed in an LXD container on that host.
LXD Mirage container OS: Debian Buster amd64 default (as provided from linuxcontainers.org)

My default shell on Debian is bash (sh is also installed).

I had to install ash to get the console to work. Without ash it shows up as a blank screen.

```
root@lxd-mosaic:~# wget -q -O - --no-check-certificate --post-data="host=" https://localhost/api/Hosts/SearchHosts/search ; echo -e
[]
root@lxd-mosaic:~# wget -q -O - --no-check-certificate --post-data="host=*" https://localhost/api/Hosts/SearchHosts/search ; echo -e
[]
root@lxd-mosaic:~# wget -q -O - --no-check-certificate --post-data="host=a" https://localhost/api/Hosts/SearchHosts/search ; echo -e
[]
root@lxd-mosaic:~# wget -q -O - --no-check-certificate --post-data="host=1" https://localhost/api/Hosts/SearchHosts/search ; echo -e
[]

**Comment by turtle0x1** [comment]
I will try installing this in a Debian later and see what else is needed;

`wget -q -O - --no-check-certificate --post-data="host=1" https://lxd.local/api/Hosts/SearchHosts/search ; echo -e`

Results in 

`[{"host":"https:\/\/192.168.1.101:8443","hostId":"3"}]`

What is the host called in LxdMosaic an IP address or did you give it an alias

**Comment by avsdev-cw** [comment]
I gave the host an alias. I've tried both typing in the full ip address and the alias and neither returns a result.

I've tried removing the alias, still an empty array

**Comment by turtle0x1** [comment]
Hm, remove all the alias's again set them to null 

Then add `var_dump($alias);`  to `/var/www/LxdMosaic/src/classes/Controllers/Hosts/SearchHosts.php` on line 23, run the `wget` command and paste the output

**Comment by avsdev-cw** [comment]
After a bit of playing around, I think I have found the issue. The client side does a tolower() (or equivalent) on the entry. The server side then uses strpos() which is case sensitive to do the matching and if the alias is in capitals, no match. Switching to stripos() fixes that. As for when I previously cleared the alias, I wasn't explicitly setting the field to null, only length 0

**Comment by turtle0x1** [comment]
I'm not entirely sure to be honest, im going chalk that up to "cosmic rays" 

Ill switch to using `stripos ` and strike that one of the list

**Comment by turtle0x1** [comment]
> It would be more useful to default to showing a list of available options for drop-downs instead of requiring a search and then simply filter if the user types

Yeah, I wanna find a drop down like gitlab or githubs labels, when I looked (a few moons ago now) there wasn't one I liked the look off,

So im going to close this issue, thank you for your report, if you got more open another issue :smile: 

_These fixes will all come out in 0.7.0_

**Comment by avsdev-cw** [comment]
https://selectize.github.io/selectize.js/ is pretty good, I've used it quite a lot in the past

**Comment by turtle0x1** [comment]
That is sexy, Ill take a look this week! (The one i use is "archived" so i need to change anyway
