### ISSUE TITLE
LXD port forwarding per container

### ISSUE THREAD

**Issue by avsdev-cw** [turtle0x1/LxdMosaic#165]
LXD has the capability to open a port on the host and forward traffic to a port on the container NIC (basically acting as a sort of alternative to iptables). This is done as a device on the container (I think). Would be useful to be able to view/edit these.

**Comment by turtle0x1** [comment]
Nice idea, aslong as the proxy implementation is not to complex ill be sure to add this

**Comment by avsdev-cw** [comment]
Not sure what the API is, but the command is in the form of:
```
lxc config device add [container] [name] proxy listen=[protocol]:[hostaddr]:[hostport] connect=[protocol]:[containeraddr]:[containerport]
```
For example, forwarding port 8443 on the host to 443 on the container (I used the loopback IP of the container to avoid DHCP issues):
```
lxc config device add cont-01 https proxy listen=tcp:0.0.0.0:8443 connect=tcp:127.0.0.1:443
```

**Comment by avsdev-cw** [comment]
Awesome job on this!
