### ISSUE TITLE
Projects + other bugs + ideas

### ISSUE THREAD

**Issue by avsdev-cw** [turtle0x1/LxdMosaic#169]
- ~~Cannot rename/delete projects~~
- ~~Filtering of profiles by project is broken~~
-  ~~Cannot add a profile, only way to make a new one is to copy then change~~
    - Tracked in #175
- ~~Filtering containers by project on load is broken~~
- ~~Selected project should probably default to "default" or "all/any" on load (would probably fix point 4 also)~~
- ~~Usage stats are not per-project~~
   - ~~Nice catch, none of the stats currently are~~
   - Tracked in #174
- ~~Cannot add an alias to an imported image~~
- ~~Cannot set image to be auto-updated~~
   - Tracking both of these in #170
- ~~Container memory usage "peak" always 0~~ [API returns 0]
- Useful to add/remove profiles to/from containers
- ~~Container disk utilisation would be useful (/1.0/instances/[container]/state metadata.disk.[disks].usage)~~
- ~~CPU usage by container would be useful~~
  - ~~Is there an API this returns this info ?~~
  - #148 covers this

- ~~Network traffic total/per container would be useful~~
- ~~Maybe switch to using the exec api and `ls -l` instead of files api?~~
  - ~~If this is because of the aforementioned bug it will be fixed in the next version~~
  - I was wrong this actually was a bug

**Comment by turtle0x1** [comment]
Closing this as I have addressed the individual issues or created a separate issue/s for the more involved ideas / problems
