### ISSUE TITLE
"Settings" always report "security.privileged"

### ISSUE THREAD

**Issue by akliouev** [turtle0x1/LxdMosaic#173]
**Describe the bug**
With a mix of privileged and non-privileged containers, lxdMosaic will display the individual non-privileged container's settings correctly only until you view the settings of a privileged container. After this the system will show security.privileged=True for all containers

**To Reproduce**
1. Go to 'Dashboard -> (your-non-privileged-container)'
2. Click on 'Actions -> Settings'
3. Verify that the settings are displayed correctly (i.e. no security.privileged=True)
4. Go to 'Dashboard -> (your-privileged-container)'
5. Click on 'Actions -> Settings'
6. Verify that the settings are displayed correctly (i.e. security.privileged=True)
7. Go back to 'Dashboard -> (your-non-privileged-container)'
8. Verify that the settings are NOT displayed correctly (i.e. security.privileged=True)

**Expected behavior**
Correct listing of settings for each container

**Desktop (please complete the following information):**
 - OS: Macos 10.15.4
 - Browser Safari
 - Version 13.1

**Additional context**

**Comment by turtle0x1** [comment]
Already fixed will be in the next version (sometime this weekend) :smile:
