### ISSUE TITLE
Everything by project

### ISSUE THREAD

**Issue by turtle0x1** [turtle0x1/LxdMosaic#174]
Suggested by @avsdev-cw

**Comment by avsdev-cw** [comment]
Extending this: the implementation of projects is incomplete. For example:

- the projects page doesn't show the list of "used by" even though there is a place-holder table there
- there are more config settings for projects now which aren't available (eg project specific storage pool, cpu limits, device restrictions etc)
- perhaps a notice on the top banner to show which project you are in when viewing profiles etc would be of use

**Comment by avsdev-cw** [comment]
One more:

- Only empty projects can be renamed. Trying to rename a project in Mosaic succeeds when it should not (actually the command fails but the failure isn't handled)

**Comment by turtle0x1** [comment]
> the projects page doesn't show the list of "used by" even though there is a place-holder table there

Cant duplicate that one, which version of LXD are you using ?

> Only empty projects can be renamed. Trying to rename a project in Mosaic succeeds when it should not (actually the command fails but the failure isn't handled)

Again can't duplicate - I think this is probably an error with what LXDMosaic is returning - are you comfortable with either of the following ? :)

 -  Opening browser dev tools & seeing what the response is one click on a project 
 - Sharing the project configuration (so I can get it into an error state)

**Comment by avsdev-cw** [comment]
The former produces a: `TypeError: data.used_by is undefined`

The latter, actually I hadn't noticed that it throws a small error in the operations list. No other feedback is given (perhaps a nice, in your face pop-up or a red toast would be handy)

**Comment by turtle0x1** [comment]
Thanks - that indicates the server isn't returning the expected response, what browser do you use ? Can you investigate the network request and see what the response is  ?

**Comment by avsdev-cw** [comment]
```json
{"state":"error","message":"Not found. \/var\/www\/LxdMosaic\/vendor\/dhope0000\/lxd\/src\/HttpClient\/Plugin\/LxdExceptionThower.php 42"}
```

**Comment by turtle0x1** [comment]
can you hop in to the LXDMosaic container and edit the file  `/var/www/LxdMosaic/src/classes/Tools/Projects/GetProjectInfo.php` commenting out lines 14-17 so it looks like this 

```php
//$project["used_by"] = StringTools::usedByStringsToLinks(
//    $host,
//    $project["used_by"]
//);
```

This should make it so it actually returns, when it returns if you wouldn't mind sharing your your `used_by` contents I can probably duplicate this

**Comment by avsdev-cw** [comment]
My bad on this one, hadn't properly read through composers update log (there was an error). Incidently the os package `php-mbstring` is now a requirement (we might have missed it in the install script...)

**Comment by turtle0x1** [comment]
Good spot! 

That dependency is because Im slowly adding tests and `phpunit` requires it, the install script got updated to include `--no-dev` to make sure it doesn't fail

**Comment by turtle0x1** [comment]
This isn't going to make into `0.10.0`, its to complicated & the release is pretty thick already - its is very important so `0.11.0` is the new target

**Comment by turtle0x1** [comment]
@avsdev-cw im splitting this out into smaller issues as I find them, im going to close this;

If you find something not by project (& no issue) please open a single issue per "part"
