### ISSUE TITLE
What should the profile overview show

### ISSUE THREAD

**Issue by turtle0x1** [turtle0x1/LxdMosaic#176]
The profiles overview is baron! What do you think it should show ?

**Comment by vsltimkay** [comment]
Maybe a table with the list of profiles, whether the profile instantiates devices, contains config user.data, vendor.data, the usage count and/or the instances using that profile?

 |  name 	| devices  | config   	| count   	| instances   	|
|---	|---	|---	|---	|---	|
|  profile1	| [disk]  	|   [vendor-data]	|   2	|  [inst1][inst3]	|
|   profile2-test	|   	|   [user-data][vendor-data]	| -  	|   	|
|   profile3	| [disk] [unix-char][gpu]  	|   	|   3	|  [inst2][inst3][inst5] 	|

It may overflow if there's too much data but it would help where multiple profiles are assigned to the same instance. Sometimes I find myself adding cloud init to a profile where I'm already doing the same in another profile that applies to the same instance and losing one of the configs.

If there's space maybe a host list too(?) I have per-host profiles and a view that showed I'd applied a   "host 3" profile to an instance running on host1 would be useful.
