### ISSUE TITLE
Be able to send backup job into the backgroud in a Q of jobs

### ISSUE THREAD

**Issue by naz9ul** [turtle0x1/LxdMosaic#189]
Hi it been a will since I haven't upgrade my lxd "manager".

You are doing a great job !  Making lxd shine more and more.

The first thing I have try was doing backup !

Since lxd backup can be very long, I was wondering if we could close the windows backup and send it into a Q of jobs, and be able to reconnect to it !

Tx for your amazing job

naz9ul@gmail.com

**Comment by turtle0x1** [comment]
Good suggestion, Ill get this in the next release

**Comment by turtle0x1** [comment]
https://github.com/peppeocchi/php-cron-scheduler looks good to schedule cron jobs wich will enable background jobs (plus it looks easy to express things like daily @ so we can easily introduce backup scheduling)
