### ISSUE TITLE
Cluster: container created on incorrect host.

### ISSUE THREAD

**Issue by vsltimkay** [turtle0x1/LxdMosaic#196]
**Describe the bug**
When creating a container in a cluster environment via the "Create a container" form the resulting container is instantiated on the wrong machine. 
In a cluster of hosts I have gpu1/gpu2/gpu3 with different hardware characteristics, the correct host is selected in the dialogue box and the GPU choices in the "GPU'S (sic) Optional" corresponds to _that_ host but the (stopped) container is actually created on another host at random. It /looks/ like the --target setting is not being passed to LXD. Container creation on a specific host works correctly via the command line. 

**To Reproduce**
1. Go to the "new container" dialogue 
2. Create a new container (any name, instance type, image, profiles) on a specific host.
3. Click "Create Container"
4. Verify target using Mosaic or the command line.

**Expected behavior**
The container should appear on the selected host

**Desktop**
Tested  using Google Chrome Version 80.0.3987.163 (Official Build) and Firefox 75.0 (64-bit)

**LXD version**
Snap installed V 4.0 stable on Ubuntu 18.04.

**Comment by turtle0x1** [comment]
Thanks for this ill take a look either today or tomorrow :smile:
