### ISSUE TITLE
Add device id info for GPU

### ISSUE THREAD

**Issue by vsltimkay** [turtle0x1/LxdMosaic#197]
**Allow multiple GPU  in a container by passing more information in config**
If the host machine has only a single GPU it is possible to add just a simple
devices:
```
  mygpu:
    type: gpu 
```
to the config. With multiple devices you need to provide an ID or PCIe bus id (though it appears than only the latter option works reliably). For example:
```
devices:
  gpu0:
    pci: 0000:5e:00.0
    type: gpu
  gpu1:
    pci: 0000:af:00.0
    type: gpu
```

**Describe the solution you'd like**

At present LxdMosaic allows you to select mutiple GPU on the host but passes:
```
"gpu_0": {
"id": "undefined",
"type": "gpu"
 },
 "gpu_1": {
 "id": "undefined",
 "type": "gpu"
  },
```
to the container which results in the error  `Error: Common start logic: Failed to start device "gpu_X": Failed to detect requested GPU device` on attempted container startup. It "should" (I would like it to)  pass the below instead:

```
"gpu_0": {
"id": "0000:aa:00.0",
"type": "gpu"
 },
 "gpu_1": {
 "id": "0000:ab:00.0",
 "type": "gpu"
  },
```

 I'm running LXD 4.0 and the resources API  /1.0/resources has been extended to provide the required information to poplulate the multi-select in the interface. I'm not sure how/if you can get the data from an earlier version or how you can differentiate the GPU from its associated audio controller (maybe the driver field though that's vendor specific?) ...

``` 
lxc query /1.0/resources | jq .pci
...
...
    {
      "driver": "nvidia",
      "driver_version": "440.64.00",
      "numa_node": 0,
      "pci_address": "0000:03:00.0",
      "product": "GP107GL [Quadro P600]",
      "product_id": "1cb2",
      "vendor": "NVIDIA Corporation",
      "vendor_id": "10de"
    },
    {
      "driver": "snd_hda_intel",
      "driver_version": "4.15.0-96-generic",
      "numa_node": 0,
      "pci_address": "0000:03:00.1",
      "product": "GP107GL High Definition Audio Controller",
      "product_id": "0fb9",
      "vendor": "NVIDIA Corporation",
      "vendor_id": "10de"
    },
...
...
```

**Describe alternatives you've considered**
The current workaround is just to add a host-machine specific profile to the container with the fully enumerated GPU devices added. Not onerous but 

1. It means that a container has double the GPU in config - only half of which are real and 
2. The lovely GPU selector in the LxDMosaic is sort of redundant.
 

**Additional context**
More than happy to test / provide more data if required.

**Comment by turtle0x1** [comment]
Thank you for the fantastic bug submission with a clear path of how to resolve it! 

Ive taken a quick glance at my code and I think whats happened is the LXD API has changed its response keys in regards to GPU's between when it was first released and 4.0, my code references a filed `id` from the LXD API which no longer exists and is why you are `"undefined"` in the subsequent API requests (or maybe it never existed & the tests I ran on my machine only worked b dumb luck), 

A note for me It may also be that the key "id"  needs to change in `src/classes/Tools/Instances/CreateInstance.php` as-well (switching to the pci_address is probably better anyway)
