### ISSUE TITLE
Ubuntu 20.04 host support

### ISSUE THREAD

**Issue by rodalpho** [turtle0x1/LxdMosaic#201]
The install script fails spectacularly on Ubuntu 20.04. Installing dependencies myself didn't fix the issue, there are quite a few of them.

**Comment by turtle0x1** [comment]
Ill fix this at somepoint (need to confirm fixes dont break 18.04 before releasing)

Temp work around (all in the container)

Curl the install script - inside replace `php7.2` with `php7.4`

Run the install script

Then run `mysql`

ALTER USER 'lxd'@'localhost' IDENTIFIED WITH mysql_native_password BY 'lxdManagerPasswordComplex321';

then run `pm2 restart 0`

**Comment by rodalpho** [comment]
Thanks! Looking to move all my containers to 20.04 these days.
