### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by heibatec** [turtle0x1/LxdMosaic#202]
On the first run, when adding a lxd server I get this error:
Couldn't store key file /var/www/LxdMosaic/src/classes/Tools/Hosts/GenerateCert.php 83

I tried some other installations (ubuntu 18.04 and 20.04) it's always the same
Browsers: Firefox or Chrome
IP and password are right

**Comment by heibatec** [comment]
Additional info from error.log:

PHP Warning:  file_put_contents(/var/www/LxdMosaic/sensitiveData/certs/xxx.xxx.xxx.xxx.key): failed to open stream: No such file or directory in /var/www/LxdMosaic/src/classes/Tools/Hosts/GenerateCert.php on line 82, referer: https://xxx.xxx.xxx.yyy/views/firstRun

xxx - my IP octets

**Comment by heibatec** [comment]
Later i tried a Centos7 install: this works!
So the bug seems to be in the ubuntu script

**Comment by turtle0x1** [comment]
Update your env file and change the variable to `LXD_CERTS_DIR=/var/www/LxdMosaic/src/sensitiveData/` that should fix it - Im just testing it now

**Comment by heibatec** [comment]
> Update your env file and change the variable to `LXD_CERTS_DIR=/var/www/LxdMosaic/src/sensitiveData/certs` that should fix it - Im just testing it now

This didn't work for me, same error.

**Comment by turtle0x1** [comment]
Which file did you change ?

**Comment by heibatec** [comment]
I tried a new installation and set the shell env LXD_CERTS_DIR=/var/www/LxdMosaic/src/sensitiveData/certs

Do you mean somthing other?

**Comment by turtle0x1** [comment]
You need to modify `/var/www/LxdMosaic/.env` (there was still a problem with fresh install I just tested - sorry been focusing else where tonight)

**Comment by heibatec** [comment]
Ah, okay, thank you, this works!
