### ISSUE TITLE
Where might I find more detailed documentation?

### ISSUE THREAD

**Issue by AverageGuy** [turtle0x1/LxdMosaic#203]
I installed Mosaic in a container as described and when I went to try to add a host I received the following:
Can't connect to 10.93.89.250, is lxd running and the port open?
Port 22 is open and I can ssh into it so I'm guessing it want to talk in some other way.  I can't find any documentation that tells me ho the other host (the one I'm trying to add) should be configured.
Thanks,
Jim.

**Comment by AverageGuy** [comment]
Also it was advised to change the password as soon as I logged in, but I don't see that option anywhere?

**Comment by turtle0x1** [comment]
https://github.com/turtle0x1/LxdMosaic/blob/master/README.md#prep-lxd-instances

LXD Listens on port 8443 (from memory) by dedault so this app needs access to that  port 

You can change the password in the "settings" page
