### ISSUE TITLE
Node server isn't reachable error

### ISSUE THREAD

**Issue by cbyreddy** [turtle0x1/LxdMosaic#204]
**Describe the bug**
I keep getting node server isn't reachable error

**To Reproduce**
1.Login to https://host_ip_address

**Expected behavior**
No error displayed

**Screenshots**

![image](https://user-images.githubusercontent.com/9153945/81158407-91feeb80-8fa5-11ea-86e0-7065944638f5.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 - Browser:Edge

**Additional context**
I was not able to access ipaddress:3000 from my browser. It said connection refused

**Comment by turtle0x1** [comment]
How did you install ?

**Comment by cbyreddy** [comment]
I started an lxc congtainer in my existing Proxomox server and then followed the steps
# Download the script
curl https://raw.githubusercontent.com/turtle0x1/LxdMosaic/master/examples/install_with_clone.sh >> installLxdMosaic.sh
# Then give the script execution permissions
chmod +x installLxdMosaic.sh
# Then run bellow to setup the program
./installLxdMosaic.sh

After installation, it told me to go to ipaddreess and ipaddress:3000.
I was able to reach ipaddress but ipaddress:3000 resulted in a connection refused error.

**Comment by turtle0x1** [comment]
What O.S ?

**Comment by cbyreddy** [comment]
Ubuntu 20.04 

pm2 log 0 is empty

[PM2] Spawning PM2 daemon with pm2_home=/home/fintraadmin/.pm2
[PM2] PM2 Successfully daemonized
[TAILING] Tailing last 15 lines for [0] process (change the value with --lines option)

**Comment by turtle0x1** [comment]
Ah its probably todo with mysql can you try the following in the container

```
mysql -u root 

ALTER USER 'lxd'@'localhost' IDENTIFIED WITH mysql_native_password BY 'lxdManagerPasswordComplex321';

exit

pm2 restart 0
```

See if that works

**Comment by cbyreddy** [comment]
1698 (28000): Access denied for user 'root'@'localhost'
I get this erro

**Comment by turtle0x1** [comment]
> 1698 (28000): Access denied for user 'root'@'localhost'

This is unusual, I have just launched a new Ubuntu 20.04 container, installed in mysql and run `mysql -u root` and I get straight into the shell - where is the ubuntu image from ?

**Comment by cbyreddy** [comment]
I was able to login using sudo mysql and had to set the mysql to use the nativepassword authentication method.

I id what you asked me to but I get this error when running pm2 restart 0

Use --update-env to update environment variables
[PM2] Applying action restartProcessId on app [0](ids: 0)
[PM2][ERROR] Process 0 not found

**Comment by turtle0x1** [comment]
oh okay so pm2 didn't start the process, what does `pm2 list` show ?

**Comment by cbyreddy** [comment]
It's empty

**Comment by turtle0x1** [comment]
```
pm2 start /var/www/LxdMosaic/node/events.js

pm2 startup

pm2 save
```

**Comment by cbyreddy** [comment]
I checked the logs when the application errored out.

0|events   |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|events   |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|events   |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:32:23)
0|events   |     at Module._compile (internal/modules/cjs/loader.js:778:30)
0|events   |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
0|events   |     at Module.load (internal/modules/cjs/loader.js:653:32)
0|events   |     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
0|events   |     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
0|events   |     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
0|events   |     at startup (internal/bootstrap/node.js:283:19)
0|events   |     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
0|events   |   errno: -13,
0|events   |   syscall: 'open',
0|events   |   code: 'EACCES',
0|events   |   path: '/etc/ssl/private/ssl-cert-snakeoil.key' }

**Comment by turtle0x1** [comment]
Okay so run it as `sudo`

**Comment by cbyreddy** [comment]
That fixed it.
I was able to access the ip:3000 link and no longer see the error.

I have another question though. I downloaded the latest 20.04 image and started it on my host.
I tried to use the console via the default bash command but nothing shows up on the screen.

**Comment by turtle0x1** [comment]
Im "at work" so ill have to take a look at that later (2 / 3 hours), try rebooting make sure everything's up and running, close and re-open the web page!

**Comment by turtle0x1** [comment]
The console works as expected in a Ubuntu 20.04 container, can you show the output of `pm2 log 0`

**Comment by cbyreddy** [comment]
I am able to get into the console on the host itself.
Here is the output of pm2 log 0

> 0|events   |     at Object.readFileSync (fs.js:343:35)
0|events   |     at Promise (/var/www/LxdMosaic/node/Hosts.js:49:35)
0|events   |     at new Promise (<anonymous>)
0|events   |     at Hosts.addDetails (/var/www/LxdMosaic/node/Hosts.js:35:12)
0|events   |     at loadHostsFromDb.then.mysqlResults (/var/www/LxdMosaic/node/Hosts.js:18:14)
0|events   |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|events   |   errno: -2,
0|events   |   syscall: 'open',
0|events   |   code: 'ENOENT',
0|events   |   path:
0|events   |    '/var/www/LxdMosaic/node/../src/sensitiveData/certs/192.168.1.172.cert' }
0|events   | { Error: ENOENT: no such file or directory, open '/var/www/LxdMosaic/node/../src/sensitiveData/certs/192.168.1.172.cert'
0|events   |     at Object.openSync (fs.js:443:3)
0|events   |     at Object.readFileSync (fs.js:343:35)
0|events   |     at Promise (/var/www/LxdMosaic/node/Hosts.js:49:35)
0|events   |     at new Promise (<anonymous>)
0|events   |     at Hosts.addDetails (/var/www/LxdMosaic/node/Hosts.js:35:12)
0|events   |     at loadHostsFromDb.then.mysqlResults (/var/www/LxdMosaic/node/Hosts.js:18:14)
0|events   |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|events   |   errno: -2,
0|events   |   syscall: 'open',
0|events   |   code: 'ENOENT',
0|events   |   path:
0|events   |    '/var/www/LxdMosaic/node/../src/sensitiveData/certs/192.168.1.172.cert' }
0|events   | { Error: ENOENT: no such file or directory, open '/var/www/LxdMosaic/node/../src/sensitiveData/certs/192.168.1.172.cert'
0|events   |     at Object.openSync (fs.js:443:3)
0|events   |     at Object.readFileSync (fs.js:343:35)
0|events   |     at Promise (/var/www/LxdMosaic/node/Hosts.js:49:35)
0|events   |     at new Promise (<anonymous>)
0|events   |     at Hosts.addDetails (/var/www/LxdMosaic/node/Hosts.js:35:12)
0|events   |     at loadHostsFromDb.then.mysqlResults (/var/www/LxdMosaic/node/Hosts.js:18:14)
0|events   |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|events   |   errno: -2,
0|events   |   syscall: 'open',
0|events   |   code: 'ENOENT',
0|events   |   path:
0|events   |    '/var/www/LxdMosaic/node/../src/sensitiveData/certs/192.168.1.172.cert' }
0|events   | { Error: ENOENT: no such file or directory, open '/var/www/LxdMosaic/node/../src/sensitiveData/certs/192.168.1.172.cert'
0|events   |     at Object.openSync (fs.js:443:3)
0|events   |     at Object.readFileSync (fs.js:343:35)
0|events   |     at Promise (/var/www/LxdMosaic/node/Hosts.js:49:35)
0|events   |     at new Promise (<anonymous>)
0|events   |     at Hosts.addDetails (/var/www/LxdMosaic/node/Hosts.js:35:12)
0|events   |     at loadHostsFromDb.then.mysqlResults (/var/www/LxdMosaic/node/Hosts.js:18:14)
0|events   |     at process._tickCallback (internal/process/next_tick.js:68:7)
0|events   |   errno: -2,
0|events   |   syscall: 'open',
0|events   |   code: 'ENOENT',
0|events   |   path:
0|events   |    '/var/www/LxdMosaic/node/../src/sensitiveData/certs/192.168.1.172.cert' }

**Comment by turtle0x1** [comment]
Your install heres gone abit of the charts! Can you do `ls /var/www/LxdMosaic/src/sensitiveData`

**Comment by turtle0x1** [comment]
If you want to add more info you can re-open
