### ISSUE TITLE
Potentially deprecated package - container-interop

### ISSUE THREAD

**Issue by theCiscoGeek** [turtle0x1/LxdMosaic#210]
During the installation on a raspberry pi4, I saw this message:

`Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.`

Just wanted to throw it out there in case someone else hadn't noticed it ^_^

**Comment by turtle0x1** [comment]
Hello, thank you for pointing this out :smile: 

Its not actually a direct dependency of this application we - don't rely on any of the interfaces it provides (although I am bad and use `\DI\Container` but that implements `Psr\Container\ContainerInterface`),

**_I assume_**
which ever dependency I use that requires it (its not in the [composer.json](https://github.com/PHP-DI/PHP-DI/blob/master/composer.json) of the DI package so if im honest I dont know / cant be bothered to find out) will do a major version release at some point that resolves the issue and ill upgrade then! 

**_If thats not the case_**

Ill fix it
