### ISSUE TITLE
Backup function is broken

### ISSUE THREAD

**Issue by yurtesen** [turtle0x1/LxdMosaic#211]
I installed LxdMosaic and added localhost.
```
Not found. /var/www/LxdMosaic/vendor/dhope0000/lxd/src/HttpClient/Plugin/LxdExceptionThower.php 42
```
Tried to take backup of the lxdMosaic container and it created a backup file in `/var/snap/lxd/common/lxd/backups/lxdMosaic/` but then in GUI it threw out the error message above.

**Comment by yurtesen** [comment]
![image](https://user-images.githubusercontent.com/1926599/83759185-df8d7780-a67b-11ea-9586-39b31658f1cf.png)

**Comment by turtle0x1** [comment]
Hey, sorry about the delayed response - this was a stupid bug!

It might be a little while before I can publish a new snap revision, hopefully some time this week!

**Comment by yurtesen** [comment]
@turtle0x1 hmm confusing... I installed lxdmosaic using the instructions on project page. Not sure if same script can update it?

Snap revision? now I will install using snap also. Lets see how that goes...

On an additional note, can't there be the currently installed version visible somewhere in the UI? so one can check which version they are running easily?

**Comment by intrepidsilence** [comment]
I am experiencing this bug as well.  I have updated all the way to v0.11.6. It was working in v0.10.x. Could we please re-open this bug?

**Comment by turtle0x1** [comment]
Sure, ill try and get round to it tonight but I'm very busy at work at the moment!

So your saying its as simple as;

- Create container
- Create backup schedule
- Nothing happens? (both snap install & a container based one?)

**Comment by turtle0x1** [comment]
@intrepidsilence the backups view is working fine when viewing an instance & container, whatever the issue is it isn't this one - can you open a new ticket with details please. 

If you want to really save time & dont me giving me access to your system (container version of LxdMosaic) you can find my email in the commit logs!
