### ISSUE TITLE
Update wiki & read me to include how to reset admin password

### ISSUE THREAD

**Issue by aanjaneyam** [turtle0x1/LxdMosaic#216]
Hi sorry for dumb request. I forgot the admin password of the lxd container instance. I tried passwd admin as root but it says admin user does not exists. 

In fact I get this

```
cat /etc/passwd | grep admin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
```
How to reset the password. Lxdmosaic itself is also is running in an Ubuntu 18.04 container.

**Comment by turtle0x1** [comment]
okay, so 

```
lxc exec lxdMosaic bash # or whatever your container name is

php -a

php > echo password_hash("NEW_PASSSWORD", PASSWORD_DEFAULT);
#$2y$10$MIFCZ6cfoNRn2UbPfDYyCe6JDs0ygPQ5ActjyHQkPGRkwwUMSQShG
php > exit

mysql -u root

mysql > use LXD_Manager;

mysql > select `User_ID`, `User_Name`
```
+---------+-----------+
| User_ID | User_Name |
+---------+-----------+
|       1 | admin     |
+---------+-----------+
```
mysql > update `user` set `User_Password` = "$2y$10$MIFCZ6cfoNRn2UbPfDYyCe6JDs0ygPQ5ActjyHQkPGRkwwUMSQShG" where `User_ID` = 1;
```

**Comment by aanjaneyam** [comment]
Many thanks. I have a small question. I understand the mysql command bit. Does the php code below is used to just generate password hash to be fed into mysql command:

```
php -a

php > echo password_hash("NEW_PASSSWORD", PASSWORD_DEFAULT);
#$2y$10$MIFCZ6cfoNRn2UbPfDYyCe6JDs0ygPQ5ActjyHQkPGRkwwUMSQShG
php > exit
```

**Comment by turtle0x1** [comment]
Yeah, the output "$2y$10...." needs to be put in the query, ive also updated my previous comment
