### ISSUE TITLE
Feature Request: CPU Usage - Per container and aggregated per host

### ISSUE THREAD

**Issue by intrepidsilence** [turtle0x1/LxdMosaic#217]
It would be great to have CPU usage on a per container basis and also have CPU usage aggregated per cluster host. The data is available in the lxd API.

**Comment by turtle0x1** [comment]
> The data is available in the lxd API.

It is not (only CPU time which can only increase - unless something has changed), 

I have written a custom metric gathering thats coming in https://github.com/turtle0x1/LxdMosaic/pull/149 and you will be able to build your own dashboards ETC (it doens't depend on any external software for gathering metrics) I.E 

![Screenshot from 2020-06-18 15-23-34](https://user-images.githubusercontent.com/12494629/85032437-bf7baf00-b177-11ea-8030-b45a34804fae.png)

**Comment by intrepidsilence** [comment]
Thanks
