### ISSUE TITLE
Show user project per server

### ISSUE THREAD

**Issue by turtle0x1** [turtle0x1/LxdMosaic#230]
This is kind of an annoying UX problem because of the potentially unlimited length of LXD hosts, can probably display 1/2 hosts but any more than than that it will have to be a drop down

Suggested by @avsdev-cw

**Comment by avsdev-cw** [comment]
Alternatively you could make the project selection a "global" selection. Any servers that don't provide that project could be hidden from the user.

I only have 1 server and so I haven't had a play around to see how the various UI elements react with multiple servers.

**Comment by avsdev-cw** [comment]
Looking at the docs, _SERVER is still defined, but the variables that would be set by a server won't be there or will be garbage. Using it to store globals/envvars seems to be the better path to go

**Comment by turtle0x1** [comment]
@avsdev-cw im closing this & opening an issue "Permissions" (yet todo)

this will be a small part of "Permissions"
