### ISSUE TITLE
Past Metric Removal

### ISSUE THREAD

**Issue by turtle0x1** [turtle0x1/LxdMosaic#231]
Metrics are cool but removing metrics is cooler, 

So the current logic is this;

If the period > 1 day and < 31 show 15 minute intervals - great we can delete everything not at 15, 30, 45 & 00

If the period > 31 days show 60 minute intervals - great we can delete everything not at 00

Now the house keeper should probably be clever and average all the values its about to delete and re-insert an average of those values but thats alot of effort

**Comment by avsdev-cw** [comment]
> Now the house keeper should probably be clever and average all the values its about to delete and re-insert an average of those values but thats alot of effort

Not so much, you could do it quite easily with SQL (pseudo..):
```sql
select first(timestamp), sum(value) / count(value) as value
from metrics
group by datepart(hour, timestamp)
where (timestamp - now()) > 31
order by timestamp asc
```

You might have to store it in a temporary table, delete the old rows and then copy back though, or do something smart by building the required date match and doing an update then delete the intermediate rows.
