### ISSUE TITLE
Setting host alias breaks the UI Completely

### ISSUE THREAD

**Issue by ronlaws86** [turtle0x1/LxdMosaic#234]
**Describe the bug**
Setting a host alias from 'configure host' breaks the interface 

**To Reproduce**
Steps to reproduce the behaviour*:
1. Go to 'Dashboard'
2. Click on 'Configure Host (After selecting one from the left)'
3. Type in a new alias
4. watch it catch fire. 

**Expected behavior**
A host alias to be set 

**Screenshots**
![image](https://user-images.githubusercontent.com/11991709/87210070-25d59680-c30c-11ea-8ccf-18f285ff75ab.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 conatiner (as per instructions)
 - Browser: Any

**Comment by turtle0x1** [comment]
Is this a cluster?

**Comment by ronlaws86** [comment]
yes clustering is enabled but not actually in use
