### ISSUE TITLE
Install by ansible

### ISSUE THREAD

**Issue by quanticware** [turtle0x1/LxdMosaic#236]
**Describe the bug**
When add local LXD 

```
LXD client certificate is not trusted. /var/www/LxdMosaic/vendor/dhope0000/lxd/src/HttpClient/Plugin/LxdExceptionThower.php 38
```
LxdMosaic 0.9.3

How accept self-trusted certificate?

Thanks

**Comment by turtle0x1** [comment]
Typically this is because the provided trust password for LXD is wrong!

**Comment by quanticware** [comment]
That's it. 
I build, destroy, build, destroy etc.. My LXD instance and change password.
Thanks

**Comment by turtle0x1** [comment]
No problem 😊 feel free to open any other issues you have or comment here
