### ISSUE TITLE
Backups only allow "daily" frequency

### ISSUE THREAD

**Issue by robcorepo** [turtle0x1/LxdMosaic#241]
When scheduling backups, the drop menu for "Frequency" only contains one item (daily).

Is this the only supported frequency currently?

**Comment by turtle0x1** [comment]
Currently, because I only run daily backups - how do you envision using it? (My main familiarity is Veeam)

**Comment by abelgomez** [comment]
May I jump in the conversation?

I'm also interested in this feature. I think that something that could be "easily" done is to add a selector for the days of the week that the backup should be executed.

E.g. if all days are selected, backups are done daily. If only, let's say Saturday, is selected, the backup is executed weekly (on Saturdays), etc.

This is, for example, how proxmox backups work.

![imagen](https://user-images.githubusercontent.com/5593904/93102816-255ed080-f6ac-11ea-86ca-ef2302fa9905.png)

**Comment by robcorepo** [comment]
Ideally, I'd like to run weekly (where I can select the DOW) and monthly (where I can select a date). Though @abelgomez 's suggestion is still much better than only having daily option. With sizeable containers, daily may not be feasible, especially because I'm running one instance of LxdMosaic across a connection that maxes at 10 mbps.

**Comment by turtle0x1** [comment]
Alright so ive got weekly backups working but monthly on dates is on hold until I resolve

**Comment by truelai** [comment]
Nice. Thanks much!
