### ISSUE TITLE
Manual backups fail to import tarball - v0.9.3

### ISSUE THREAD

**Issue by robcorepo** [turtle0x1/LxdMosaic#242]
v0.9.3

1. Navigate to: _Dashboard / LXD-host / Container-name_
2. Click on the _Backups_ tab
3. In the LXD Instance Backups pane, click on _Create_
4. Enter a backup name and select _Import & Delete From Remote_
5. Note that the modal never disappears
6. Using another tab, navigate to  _Dashboard / LXD-host / Container-name_
7. Click on the _Backups_ tab
8. Note that there is an LXD Instance Backup but no LXDMosaic Instance Backup
9. Try to import (with or without deleting the remote backup)
10. Note that import never occurs

It appears that the remote backup is created. Where can I check for that tarball on the remote? Also, in the Even Log for the containers in question. I can see the events _Import Remote Instance Backup_. But I don't see them actually existing in the backups tab.

**Comment by robcorepo** [comment]
Watching iftop, I can see that transfer is occurring. It seemed to terminate the connection before the transfer actually finished (based on the size of transfer). I tried with a smaller container and got the same results. 

Interestingly, I can see this:
```
root@lxd-mosaic:/var/www/LxdMosaic/src/sensitiveData/backups# ll 8/adlive-calendar/
total 0
drwxr-xr-x 1 www-data www-data 124 Sep 15 14:24 ./
drwxr-xr-x 1 www-data www-data  40 Sep 15 14:38 ../
-rw-r--r-- 1 www-data www-data   0 Sep 15 14:06 backup.2020-09-14T19:53:30Z.tar
-rw-r--r-- 1 www-data www-data   0 Sep 15 14:24 backup.2020-09-15T18:19:14Z.tar
```

**Comment by turtle0x1** [comment]
Hmm odd, when I follow the same procedure It does return & does create a backup (but doesn't import it, which probably is because of the improvements to scheduling backups, ill take a look at that)

Those backups loock odd because they are 0 sized

**Comment by robcorepo** [comment]
Yep. I see lots of transfer in iftop, but it's not completing properly, it seems.

**Comment by robcorepo** [comment]
No, I'm not getting it to complete even with the smaller container.

**Comment by turtle0x1** [comment]
Okay something odd is going, let me come back to you I might need more details

**Comment by turtle0x1** [comment]
Okay nope, running those steps doesn't create empty backups and kinda works as expected, what containers OS are they? are they running ? Whats LXD running on ?

Is LXDMosaic ubuntu, centos, debian or snap ?

**Comment by robcorepo** [comment]
Previously, I was using the apt repo for LXD 3
I migrated to the snap and am now with:

Ubuntu 18.04.5 LTS
LXD 4.4

This is the instance with Mosaic.

The remote machine is the same release and version.

**Comment by turtle0x1** [comment]
Are you using the --edge snap ?

**Comment by robcorepo** [comment]
lxd     4.4       16926  latest/stable  canonical

**Comment by robcorepo** [comment]
I installed mosaic with your script.

**Comment by turtle0x1** [comment]
okay anything interesting under `/var/log/apache2/error.log` ?

**Comment by robcorepo** [comment]
[Tue Sep 15 16:38:09.161532 2020] [proxy:error] [pid 363] (111)Connection refused: AH00957: HTTPS: attempt to connect to 127.0.0.1:3000 (localhost) failed
[Tue Sep 15 16:38:09.161593 2020] [proxy_http:error] [pid 363] [client 10.212.134.200:57756] AH01114: HTTP: failed to make connection to backend: localhost, referer: https://mosaic.robco.com/

**Comment by robcorepo** [comment]
Current vhost:

<VirtualHost _default_:80>
#    ServerName lxd.local
    ServerName mosaic.domain.com
    DocumentRoot /var/www/LxdMosaic/src/public
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI}
</VirtualHost>
<IfModule mod_ssl.c>
        <VirtualHost _default_:443>
#            ServerName lxd.local
            ServerName mosaic.domain.com
                ServerAdmin webmaster@localhost

                DocumentRoot /var/www/LxdMosaic/src/public

                ErrorLog ${APACHE_LOG_DIR}/error.log
                CustomLog ${APACHE_LOG_DIR}/access.log combined

                SSLEngine on

#                SSLCertificateFile      /etc/ssl/certs/ssl-cert-snakeoil.pem
		SSLCertificateFile	/etc/ssl/certs/letsencrypt/fullchain.pem
#                SSLCertificateKeyFile   /etc/ssl/private/ssl-cert-snakeoil.key
		SSLCertificateKeyFile	/etc/ssl/certs/letsencrypt/privkey.pem

                RewriteEngine On
                RewriteCond %{REQUEST_URI}  ^/socket.io            [NC]
                RewriteCond %{QUERY_STRING} transport=websocket    [NC]
                RewriteRule /(.*)           wss://localhost:3000/$1 [P,L]

                <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>
                <Directory /usr/lib/cgi-bin>
                                SSLOptions +StdEnvVars
                </Directory>
                <Directory /var/www/LxdMosaic>
                   AllowOverride All
                </Directory>

                SSLProxyEngine on
                SSLProxyVerify none
                SSLProxyCheckPeerCN off
                SSLProxyCheckPeerName off

                ProxyPass        /socket.io https://localhost:3000/socket.io
                ProxyPassReverse /socket.io https://localhost:3000/socket.io
        </VirtualHost>
</IfModule>

**Comment by turtle0x1** [comment]
Hmm, thats todo with node service not being available, if your seeing events on the homepage this is just a temporary error

Ill try to replicate your setup to see if that could lead to the issue

**Comment by turtle0x1** [comment]
Just as a test could you schedule a daily backup for in the next couple of minutes to see if that completes sucesfully and isn't empty ?

**Comment by robcorepo** [comment]
Thanks much. And thanks for this project. I've asked my team to use, test, and submit bugs. 

Also, I have already completed scheduled backups successfully.

**Comment by turtle0x1** [comment]
Thanks, that sounds great!

Aha, PHP memory exhaustion, cron jobs shouldn't suffer from this because the default CLI value is `-1` which is unlimited;

The exhaustion causes a 500 error response which the app doesn't handle properly (no output from API), so the interface hangs as a result

- [ ]  Properly catch memory exhaustion on manual backup jobs

- [ ] Remove empty backup file from our file system 

`Tools/Instances/Backups/StoreBackupLocally::downloadBackup()` is where the magic happens (reminder for me)

**Comment by robcorepo** [comment]
With this patch, I'm now getting a file with contents:

```
root@lxd-mosaic:/var/www/LxdMosaic/src/sensitiveData/backups# ll  8/bind9/
total 1176128
drwxr-xr-x 1 www-data www-data         62 Sep 15 14:38 ./
drwxr-xr-x 1 www-data www-data         48 Sep 15 16:50 ../
-rw-r--r-- 1 www-data www-data 1204355072 Sep 15 21:41 backup.2020-09-15T18:22:02Z.tar
```

The container appears to not finish transfer. This is only 1.2 G and I believe the tar should be larger. IT doesn't show up in LXDMosaic backups and the remote is not deleted. Can you tell me where to find this backup on the remote? Is it here?

```
root@R810-LXD9-Centcom:/var/snap/lxd/common/lxd/backups/bind9# ll 
total 7330612
drwx------ 2 root root       4096 Sep 15 18:22 ./
drwx------ 6 root root       4096 Sep 16 01:01 ../
-rw------- 1 root root 7506533405 Sep 15 18:38 20200915
```

**Comment by robcorepo** [comment]
By deleting the pre-patch remote backups and re creating it, I was able to:

1. Create the remote backup
2. Copy the remote backup to LxdMosaic
3. Delete the remote backup
4. Quit the modal

Thanks very much for the quick patch!

**Comment by robcorepo** [comment]
[Wed Sep 16 01:30:44.295309 2020] [php7:error] [pid 9695] [client 10.212.134.200:35934] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/LxdMosaic/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 394, referer: https://mosaic.domain.com/
