### ISSUE TITLE
Tarball fails to import due to php execution timeout

### ISSUE THREAD

**Issue by robcorepo** [turtle0x1/LxdMosaic#245]
After applying 4ce27cbeada07510d8fc757dd798c7a1d762bec5

Importing tarballs from remotes time out unless small containers transfer in time.

`
[Wed Sep 16 02:54:23.613488 2020] [php7:error] [pid 7289] [client 10.212.134.200:40312] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/LxdMosaic/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 394`

**Comment by truelai** [comment]
Beautiful! Thanks much, @turtle0x1
