### ISSUE TITLE
Creating a new project does not update the "projects" list on the main dashboard

### ISSUE THREAD

**Issue by avsdev-cw** [turtle0x1/LxdMosaic#246]
Creating a new project does not update the "projects" list on the main dashboard. This requires you to refresh the entire page in order to select the new project.

**Comment by turtle0x1** [comment]
Does your dashboard take a while to render? Because every time you click "dashboard" it reloads the dashboard in the background so you should get the new projects

**Comment by avsdev-cw** [comment]
After playing around with this, it appears the refresh is intermittent. Sometimes it does refresh, other times it does not (even with the same action sequences). Another noticeable instance where it does not always refresh is when creating new containers.

Clicking the "Dashboard" link does cause a hard refresh contently though.

**Comment by avsdev-cw** [comment]
Related but not identical:

Further usage shows that the list of containers consistently does not update when adding a new container. You have to fully, manually refresh to get the left nav list to display the new container.

**Comment by turtle0x1** [comment]
@avsdev-cw

When you click "dashboard" in the main nav it reloads the entire of the dashboard, it should display the new projects it just may take a while 

The only option here is to indicate the dashboard is loading with a spinning cog icon or something, which i will do!

**Comment by avsdev-cw** [comment]
I think it's more of a "responsive expectation" thing. When you add something, these days you expect lists, menus etc to auto-update/refresh with the new item added.

Clicking the "dashboard" link does indeed refresh for me.

**Comment by turtle0x1** [comment]
@avsdev-cw is there any chance you could drop screenshots of what doesn't update

I think you sent a video but I think i fixed those things
