### ISSUE TITLE
Php memory exhaustion when using RestoreBackup

### ISSUE THREAD

**Issue by truelai** [turtle0x1/LxdMosaic#249]
[Thu Sep 17 16:50:02.390960 2020] [php7:error] [pid 278] [client 10.1.1.5:51984] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 1335611512 bytes) in /var/www/LxdMosaic/src/classes/Tools/Backups/RestoreBackup.php on line 23

**Comment by turtle0x1** [comment]
If you wanna get it done now edit `/etc/php/7.2/apache2/php.ini` and set `memory_limit` to `-1` while restoring

**Comment by turtle0x1** [comment]
Ill look for a fix for this over the weekend

**Comment by truelai** [comment]
Cool. Thanks!
