### ISSUE TITLE
Can't find OS (Cant find verison)

### ISSUE THREAD

**Issue by truelai** [turtle0x1/LxdMosaic#250]
0.9.3

All containers show this message in: Dashboard / LXD1 / c1

`Can't find OS (Cant find verison)`

**Comment by turtle0x1** [comment]
Its likely the image details were all unset when importing, does `lxc list` show them properly?

**Comment by truelai** [comment]
Ahh, I see. This is a manual field?

**Comment by turtle0x1** [comment]
Ah, I think it may be linked to the image like a `LEFT JOIN` if you know SQL, I think if you download the image it will populate

**Comment by truelai** [comment]
What do you mean by "download the image".

**Comment by turtle0x1** [comment]
Well if the original containers are `ubuntu:18.04` you would do `lxc launch ubuntu:18.04 temp` which will download the image, you can then delete the temp container but the image details should show on your restored containers

(You cant reach the official ubutnu servers through LXDMosaic right now)

**Comment by truelai** [comment]
Gotcha. Thanks!

**Comment by truelai** [comment]
> (You cant reach the official ubutnu servers through LXDMosaic right now)

Why is that?

**Comment by turtle0x1** [comment]
Because 21 year old me made some interesting choices!

The image import process is abit weird & ubuntu servers use simplestreams instead of LXD protocol or something like that made it difficult at the time
