### ISSUE TITLE
Scheduled backups fail (backp is size 0)

### ISSUE THREAD

**Issue by truelai** [turtle0x1/LxdMosaic#257]
This is where I'm starting from:

```
lai@lxd-mosaic:/var/www/LxdMosaic$ n ls
node/10.0.0
lai@lxd-mosaic:/var/www/LxdMosaic$ sudo npm i
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 630 packages in 6.565s

4 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
lai@lxd-mosaic:/var/www/LxdMosaic$ sudo pm2 log 0
[TAILING] Tailing last 15 lines for [0] process (change the value with --lines option)
/home/lai/.pm2/logs/events-error.log last 15 lines:
/home/lai/.pm2/logs/events-out.log last 15 lines:
^C
lai@lxd-mosaic:/var/www/LxdMosaic$ 
```

Scheduled backups give me an empty file. Must be timing out or hitting a max, but I don't have visibility in the logs about what is being hit. Also, my version is again not displaying properly.

![version](https://user-images.githubusercontent.com/4158476/93896680-37013300-fcbf-11ea-9855-f8a60e59e991.png)

**Comment by turtle0x1** [comment]
Check `/var/log/apache2/error.log`, are you doing this in the browser or scheduled job? 

Whats the commit `cd /var/www/LxdMosaic && git rev-parse HEAD`

**Comment by truelai** [comment]
```
[Tue Sep 22 10:29:05.045004 2020] [proxy:error] [pid 13181] (111)Connection refused: AH00957: HTTPS: attempt to connect to 127.0.0.1:3000 (localhost) failed
[Tue Sep 22 10:29:05.045080 2020] [proxy_http:error] [pid 13181] [client 10.212.134.200:50752] AH01114: HTTP: failed to make connection to backend: localhost, referer: https://mosaic.robco.com/
```
```
# cd /var/www/LxdMosaic && git rev-parse HEAD
c07329caf6f3d75b81d9eae31da517d04be388e7
```

**Comment by truelai** [comment]
And it's scheduled

**Comment by turtle0x1** [comment]
So it didn't work when you try to manually run the job?

**Comment by truelai** [comment]
Manual works.

**Comment by truelai** [comment]
Manual works but caveats:

1. Backup and Import only imports
2. Modal doesn't exit after import suceeds

**Comment by truelai** [comment]
Since my php.ini has 

memory_limit = -1

Maybe this is execution time issue?

**Comment by turtle0x1** [comment]
Shouldn't effect the CLI,  but you can try setting `max_execution_time = 0`

**Comment by truelai** [comment]
```
Wed Sep 23 10:43:47.558998 2020] [proxy:error] [pid 341] (111)Connection refused: AH00957: HTTPS: attempt to connect to 127.0.0.1:3000 (localhost) failed
[Wed Sep 23 10:43:47.559077 2020] [proxy_http:error] [pid 341] [client 10.212.134.200:43852] AH01114: HTTP: failed to make connection to backend: localhost, referer: https://mosaic.robco.com/
```

Will this be a blocker for scheduled backups?

**Comment by turtle0x1** [comment]
No, this is apache failing to proxy node traffic (I.E node server isn't reachable)

**Comment by truelai** [comment]
It's not working still. No backup is being created.

**Comment by truelai** [comment]
How can I invoke it from CLI to see where this is failing?

**Comment by turtle0x1** [comment]
The CLI environment is different so there is no guarantee you will hit the same error,

you can do `cd /var/www/LXDMosaic && vendor/bin/crunz schedule:list` this will show you all the scheduled jobs it will run, something like;

```
+---+--------------------------------------------+-------------+--------------------------------------------------------------------------------------------------+
| # | Task                                       | Expression  | Command to Run                                                                                   |
+---+--------------------------------------------+-------------+--------------------------------------------------------------------------------------------------+
| 1 | Gathering container metrics                | * * * * *   | /usr/bin/php7.4  /var/www/LxdMosaic/src/cronJobs/scripts/containerMetrics.php                    |
| 2 | Gathering fleet metrics                    | */5 * * * * | /usr/bin/php7.4  /var/www/LxdMosaic/src/cronJobs/scripts/fleetAnalytics.php                      |
| 3 | Checking hosts are online                  | * * * * *   | /usr/bin/php7.4  /var/www/LxdMosaic/src/cronJobs/scripts/hostsOnline.php                         |
| 4 | Backing up 13 apache default 1 daily@21:00 | 0 21 * * *  | /usr/bin/php7.4  /var/www/LxdMosaic/src/cronJobs/scripts/backupContainer.php 13 apache default 1 |
| 5 | Check Retention                            | 0 2 * * *   | /usr/bin/php7.4  /var/www/LxdMosaic/src/cronJobs/scripts/enforceBackupRetention.php              |
+---+--------------------------------------------+-------------+--------------------------------------------------------------------------------------------------+

```
You will want to find one of the jobs like number 4 and copy `Command To Run` I.E `usr/bin/php7.4  /var/www/LxdMosaic/src/cronJobs/scripts/backupContainer.php 13 apache default 1`, run it and see if any output is created

**Comment by truelai** [comment]
```
root@lxd-mosaic:/var/www/LxdMosaic# /usr/bin/php7.2  /var/www/LxdMosaic/src/cronJobs/scripts/backupContainer.php 1 social-robco-com default 1  
PHP Notice:  Undefined index: DB_HOST in /var/www/LxdMosaic/src/classes/Model/Database/Database.php on line 12
PHP Notice:  Undefined index: DB_NAME in /var/www/LxdMosaic/src/classes/Model/Database/Database.php on line 13
PHP Notice:  Undefined index: DB_USER in /var/www/LxdMosaic/src/classes/Model/Database/Database.php on line 13
PHP Notice:  Undefined index: DB_PASS in /var/www/LxdMosaic/src/classes/Model/Database/Database.php on line 13
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) in /var/www/LxdMosaic/src/classes/Model/Database/Database.php:13
Stack trace:
#0 /var/www/LxdMosaic/src/classes/Model/Database/Database.php(13): PDO->__construct('mysql:host=;\n  ...', NULL, NULL)
#1 /var/www/LxdMosaic/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(140): dhope0000\LXDClient\Model\Database\Database->__construct()
#2 /var/www/LxdMosaic/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(70): DI\Definition\Resolver\ObjectCreator->createInstance(Object(DI\Definition\ObjectDefinition), Array)
#3 /var/www/LxdMosaic/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(58): DI\Definition\Resolver\ObjectCreator->resolve(Object(DI\Definition\ObjectDefinition), Array)
#4 /var/www/LxdMosaic/vendor/php-di/php-di/src/DI/Container.php(303): DI\Definition\Resolver\ResolverDispatcher->resolve(Object(DI\Definition\ObjectDefinition), Array)
#5 /var/www/LxdMo in /var/www/LxdMosaic/src/classes/Model/Database/Database.php on line 13
```

**Comment by truelai** [comment]
The user is blank?

**Comment by turtle0x1** [comment]
Edit `/var/www/LxdMosaic/src/cronJobs/scripts/backupContainer.php`

so the first few lines look like this;

```
<?php

require __DIR__ . "/../../../vendor/autoload.php";

$env = new Dotenv\Dotenv(__DIR__ . "/../../../");
$env->load();
....
```

**Comment by truelai** [comment]
Just fired it off and gzip popped up on the remote host.

**Comment by truelai** [comment]
It completed.

**Comment by turtle0x1** [comment]
So its only when you run the job in browser this fails, set this file back to its original contents

Ill have todo more testing on large containers, if it takes 5 minutes on the CLI its going to take 5 minutes in the browser (it waits for completion)

Open the browser developer tools, switch to the "networking tab", browse to the container backup window (notice the 200 responses n the relativly fast time they respond in) now start the backup wait for it to complere with either a 200 or 500 error, click on the request then click "response" what does it say? If it was a case of not just waiting long enough it should return 200, otherwise you might see an error

**Comment by turtle0x1** [comment]
Have you looked at snapshots instead of using manual backups, they might be much faster?

**Comment by truelai** [comment]
I wasn't running in the browser (not for the last couple days). These were scheduled ones failing. But thanks for the debug advice. I'll use this in the future.

How would snapshots be faster? You mean by skipping gzip? You mean copying containers using the snapshot? Like this?
`
lxc copy local:c1/snap3 remote:c1`

I think how fast that is may depend on your filesystem, no? I think there might be some scenarios with btrfs where it might actually take longer. But regardless, it'd be a nice option to have this if this is what you mean.

**Comment by turtle0x1** [comment]
That's really weird that it works when you manually run it, 

What do you get with, vendor/bin/crunz schedule:run --task YOUR_BACKUP_TASK_NUMBER --force

Ignore my comments on snapshots, I thought this was like a "make a change", "take a backup", "make a change" scenario but if your scheduling them its not that!

**Comment by truelai** [comment]
$ sudo vendor/bin/crunz schedule:run --task YOUR_BACKUP_TASK_NUMBER --force

In TaskNumber.php line 43:
                                                         
  Task number 'YOUR_BACKUP_TASK_NUMBER' is not numeric.  
                                                         

schedule:run [-f|--force] [-t|--task TASK] [--] [<source>]

**Comment by truelai** [comment]
you want me to run that with the env patch in place? 

here is the output with the backupContainer.php already edited:

```
$ sudo vendor/bin/crunz schedule:run --task 33 --force
PHP Notice:  Undefined index: DB_HOST in /var/www/LxdMosaic/src/classes/Model/Database/Database.php on line 12
PHP Notice:  Undefined index: DB_NAME in /var/www/LxdMosaic/src/classes/Model/Database/Database.php on line 13
PHP Notice:  Undefined index: DB_USER in /var/www/LxdMosaic/src/classes/Model/Database/Database.php on line 13
PHP Notice:  Undefined index: DB_PASS in /var/www/LxdMosaic/src/classes/Model/Database/Database.php on line 13
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user ''@'localhost' (using password: NO) in /var/www/LxdMosaic/src/classes/Model/Database/Database.php:13
Stack trace:
#0 /var/www/LxdMosaic/src/classes/Model/Database/Database.php(13): PDO->__construct()
#1 /var/www/LxdMosaic/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(140): dhope0000\LXDClient\Model\Database\Database->__construct()
#2 /var/www/LxdMosaic/vendor/php-di/php-di/src/DI/Definition/Resolver/ObjectCreator.php(70): DI\Definition\Resolver\ObjectCreator->createInstance()
#3 /var/www/LxdMosaic/vendor/php-di/php-di/src/DI/Definition/Resolver/ResolverDispatcher.php(58): DI\Definition\Resolver\ObjectCreator->resolve()
#4 /var/www/LxdMosaic/vendor/php-di/php-di/src/DI/Container.php(303): DI\Definition\Resolver\ResolverDispatcher->resolve()
#5 /var/www/LxdMosaic/vendor/php-di/php-di/src/DI/Container.php(131): DI\Container->resolveDefinition()
#6 /var/www/LxdMosaic/vendor/php-di/php-di/src/DI/Definition/AliasDefinition.php( in /var/www/LxdMosaic/src/classes/Model/Database/Database.php on line 13
```

**Comment by turtle0x1** [comment]
The patch should be removed first :smile:

**Comment by truelai** [comment]
Without patch, it completed.

**Comment by turtle0x1** [comment]
Backup size > 0? Im really not sure, why the backup is failing then

So;

Creating it with the script work
Creating it by running the cron job worked
Creating it in the browser works

Letting the cronjob run does not work, 

Please answer the following;

Do any of the scheduled jobs run successfully?
How many jobs are running at one time ? (I.E are 5/6 schedulded at the same time)
Are the backups present on the remote?

**Comment by truelai** [comment]
Size is correct:

Creating it with the script work
- when I made the env adjustments, yep

Creating it by running the cron job worked
- yep

Creating it in the browser works
- yep

I just scheduled a job for 10:30 (10 minutes from now) to test again. Is there an easy way I can alter the cron command to output to a log file?

**Comment by turtle0x1** [comment]
You could try

```
# crunz.yml
log_errors: true
errors_log_file: /some_where
```

**Comment by truelai** [comment]
I just noticed this in the config:

# Timezone is used to calculate task run time
# This option is very important and not setting it is deprecated
# and will result in exception in 2.0 version.
timezone: Europe/London

This is not my timezone. How was this set in the first place?

**Comment by turtle0x1** [comment]
Hardcoded, ill need to write a tool for that - snap makes that complicated because you cant edit files - sigh

**Comment by truelai** [comment]
I added logging for errors and output but nothing is written. Who should be the owner? Root?

After fixing the timezone (crucial info to know), I see gzip on the remote. The "imported" file size is zero. There is no successful backup on the remote.

**Comment by truelai** [comment]
Interestingly, I see that two separate gzip processes are kicked off on the remote. When the process ends, there is nothing in the backups directory on the remote. Is there supposed to be two processes here?

**Comment by turtle0x1** [comment]
That doesn't sound right, 

but LXDMosaic will delete backups after it thinks its done with them;

Can you reliably trigger this 0 backup size?

Ive probably been silly and forgot to check an additional error (although, you would think you would see failed events in the sidebar)

Can you modify `/var/www/LxdMosaic/src/classes/Tools/Instances/Backups/BackupInstance.php` line modify around line 44 so it looks like this;

```
$response = $host->instances->backups->create($instance, $backup, [], $wait);

if(isset($response['err'])){
     throw new \Exception($response['err'])
}
...
``

**Comment by truelai** [comment]
I actually DO see an error in the sidebar:

![backup](https://user-images.githubusercontent.com/4158476/94179130-11fcf380-fe6a-11ea-9611-85ed322f3ebd.png)

I'm an asshat for not noticing and reading it. 

I can reliably trigger it. I just need to set any scheduled backup.

I'll modify the file and schedule for 29 minutes from now.

**Comment by truelai** [comment]
I think that error is related to what I see in the backups pane. There will often be TWO backups of size zero for the same time.

**Comment by truelai** [comment]
I should be _replacing_ this chunk, yes:
 
```
       if ($importAndDelete) {
            $this->storeBackupLocally->store($host, $instance, $backup, true);
        }
```

**Comment by truelai** [comment]
Here are the doubles I'm seeing. It must be related to the double gzip process that kicks off on the remote. 

![doubles](https://user-images.githubusercontent.com/4158476/94179761-f7774a00-fe6a-11ea-9a7e-67e4e2965f6a.png)

**Comment by turtle0x1** [comment]
Oo spooky, yeah so were getting double jobs running some how, you haven't got 2 entries in `crontab` do you ?

**Comment by turtle0x1** [comment]
> I should be _replacing_ this chunk, yes?:
> 
> ```
>        if ($importAndDelete) {
>             $this->storeBackupLocally->store($host, $instance, $backup, true);
>         }
> ```

Nope just before that line - but we can see the error is now that there is a duplicate process some how, we control the backup name

Do you have 2 different servers running a backup at the same time for this instance ? - that would probably do it

**Comment by truelai** [comment]
`[2020-09-24 14:00:05] crunz.ERROR: Backing up 1 social-robco-com default 1 daily@14:00(/usr/bin/php7.4  /var/www/LxdMosaic/src/cronJobs/scripts/backupContainer.php 1 social-robco-com default 1)  PHP Parse error:  syntax error, unexpected '}' in /var/www/LxdMosaic/src/classes/Tools/Instances/Backups/BackupInstance.php on line 49   [] []`

I can do a remote session with you anytime if that helps.

**Comment by turtle0x1** [comment]
> I can do a remote session with you anytime if that helps. Only one mosaic is running the schedule at a time.

You can get my email from `git log` and drop me a line!

**Comment by truelai** [comment]
Guess we should close this one.

Lessons learned:

- be sure crontab isn't being appended with repeated lines
- drop --exact-match from the symbolic-ref pulling the id of HEAD
