### ISSUE TITLE
Create Project error

### ISSUE THREAD

**Issue by gregtampa** [turtle0x1/LxdMosaic#259]
```Not found. /var/www/LxdMosaic/vendor/dhope0000/lxd/src/HttpClient/Plugin/LxdExceptionThower.php 42```
hit create button on create project and got this error on top right in red.

**Comment by turtle0x1** [comment]
What version you got installed?

**Comment by turtle0x1** [comment]
And what version of LXD are you "talking to"

**Comment by truelai** [comment]
You get get your LxdMosaic version in the GUI by going to the "settings" tab

**Comment by gregtampa** [comment]
whatever latest is as i pulled from this git 21 hours ago.
i can grab version if you like.
clean install last night.
however im running lxc on ubuntu 18 and it seems from your install guide it put mosaic inside a ubuntu 20 lxc.
as thats the latest.

**Comment by turtle0x1** [comment]
Im fairly certian this is caused by trying create a host that doesnt support projects

Ill add some kind of filter
