### ISSUE TITLE
Pages are not populated if a LXC host is down

### ISSUE THREAD

**Issue by Innercode** [turtle0x1/LxdMosaic#265]
Hi,

First of all, many thanks for this great web interface!

When a LXC host is down almost all pages aren't populated with data and becomes not useable.

All the get requests on the controllers, for instance `/api/Dashboard/GetController/get` and `/api/Backups/GetBackupsOverviewController/get` resulting in a HTTP 500 error.

In the log the following error occurs and is for every route the same

`PHP Fatal error:  Uncaught Error: Call to undefined method dhope0000\\LXDClient\\Model\\Hosts\\GetDetails::getIdByUrlMatch() in /var/www/LxdMosaic/src/classes/App/ExceptionHandler.php:38\nStack trace:\n#0 [internal function]: dhope0000\\LXDClient\\App\\ExceptionHandler->handle()\n#1 {main}\n  thrown in /var/www/LxdMosaic/src/classes/App/ExceptionHandler.php on line 38`

Many thanks in advance!

**Comment by turtle0x1** [comment]
Hmm i usually run with offline hosts alot

Are you running the install script version or master? 😀

**Comment by turtle0x1** [comment]
I think the undefined method issue was resolved erliar thats all - i may be wrong but im on mobile probably until tommorow

**Comment by Innercode** [comment]
I ran the install script and instructions as stated here https://lxdmosaic.readthedocs.io/en/latest/

**Comment by turtle0x1** [comment]
Okay, this is probably fixed in version 0.10.0 coming out in the next couple of weeks - but ill double check 😊

**Comment by Innercode** [comment]
Thanks! :+1: 
Wish you all the best with this project and thanks for your fast support

**Comment by turtle0x1** [comment]
Thank you

This was fixed here, which will come out in the next release 0.10.0 :smile: 

https://github.com/turtle0x1/LxdMosaic/commit/14d652ff2ea32be716b098ab5c846117c06a4c1a
