### ISSUE TITLE
no usernames are recognized. 

### ISSUE THREAD

**Issue by vonschutter** [turtle0x1/LxdMosaic#266]
**Describe the bug**
After I installed the app from snapcraft.io there is no indication of what to do. I figured that I would just put the IP in the browser and go. It sort of worked since the login page came up. However, no user names and password combination worked, and no instruction of what to do to set up a username and password for the service. 

**To Reproduce**
install from snapcraft with --beta option.

Start the service per the instructions on github.

got to xx.xx.xx.xx and try to log in. 

**Expected behavior**
To be able to log in or to see instruction on how to set it up on the login page. 

**Screenshots**

**Desktop (please complete the following information):**
lastest Ubuntu. 

**Additional context**

**Comment by vonschutter** [comment]
and teh error message: {"state":"error","message":"Username not found \/snap\/lxdmosaic\/23\/htdocs\/src\/classes\/Tools\/User\/LogUserIn.php 27"}

**Comment by turtle0x1** [comment]
If your stuck;

Default username & password is admin test123 - Change the password in settings ASAP

Im going to close this in favour of a more general issue later because its not snap related & will form a part of a larger change to the "first run" experience
