### ISSUE TITLE
Console does not work with version v0.10.0

### ISSUE THREAD

**Issue by naz9ul** [turtle0x1/LxdMosaic#269]
**Juste tried version 10 and console does not work anymore**

**To Reproduce**
Fresh install of version 10 on a new container.
Click on host
click on container
click on consolem select default bash 
hi go
Nice black sreen :-(

![image](https://user-images.githubusercontent.com/28147503/96750186-a8ed9a80-1399-11eb-99c6-57d60a933ee5.png)

Tested with Chrome and firefox on linux.
LXD version 4.7 snap

**Comment by turtle0x1** [comment]
`cd /var/www/LxdMosaic && git fetch && git checkout v0.10.1 && pm2 restart all` will fix that
