### ISSUE TITLE
Configure http/s port/s in snap

### ISSUE THREAD

**Issue by sstubbs** [turtle0x1/LxdMosaic#270]
**Is your feature request related to a problem? Please describe.**
This project looks great. I just tried installing this as a snap. It seems to work however its using both ports 80 and 443 which means I won't be able to use it. I think this will be a problem for a lot of users.

**Describe the solution you'd like**
I see there are variables available for port but they don't seem to work for me. Also it would be nice to disable http and only leave https. Something like the following:

```
sudo snap install lxdmosaic && \
sudo snap set lxdmosaic ports.https=9091 && \
sudo snap set lxdmosaic ports.http=disable
```

**Comment by turtle0x1** [comment]
Yeeaa it is a pain, i removed the command from the snap to simplify the initial build but it can be ripped from nextcloud

**Comment by turtle0x1** [comment]
@sstubbs by tomorrow morning you will be able todo;

`sudo snap set lxdmosaic ports.http=81 ports.https=444`

_(snap build times are "fun", ill comment again when on `stable`)_

**Comment by sstubbs** [comment]
@turtle0x1 thanks that will be amazing. This project is really great.

**Comment by turtle0x1** [comment]
Thanks for you kind words, this is live now :smile:

**Comment by sstubbs** [comment]
@turtle0x1 its working thanks a lot.
