### ISSUE TITLE
Set certificate location in snap package

### ISSUE THREAD

**Issue by klockren80** [turtle0x1/LxdMosaic#271]
There are no snap configuration directives for certificate locations. Please add them.

**Comment by turtle0x1** [comment]
I keep dropping in and out of this cant get quite get it working, there is the command `sudo lxdmosaic.enable-https custom -h` but I cant quite get it working!

**Comment by turtle0x1** [comment]
I'm tidying up for a release, this is isn't going to make it! 

Will assign to the next milestone but not that hopeful!

**Comment by turtle0x1** [comment]
Had another crack at this tonight, think It can be done - some minor annoyances in the way.

Will try again in a few days.
