### ISSUE TITLE
Error when trying to change admin password

### ISSUE THREAD

**Issue by cbc02009** [turtle0x1/LxdMosaic#274]
**Describe the bug**
When I try to change the admin account password via the web gui I get the JSON error below. lxdMosaic is installed in an Ubuntu 20.10 container running on an Ubuntu 20.10 host. lxdMosaic version is v0.10.1

**To Reproduce**
1. Go to Settings
2. Click on icon underneath Reset Password

**Expected behavior**
I should be able to change the password for the account

**Resulting Error**
{"state":"error","message":"Dont understand the path /var/www/LxdMosaic/src/classes/App/RouteController.php 109"}

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser firefox
 - Version 82.0

**Comment by turtle0x1** [comment]
Im not able to duplicate this - I fresh installed with no problem

**Comment by cbc02009** [comment]
I just tried it again and it magically works. No idea what the issue was. 🤷
