### ISSUE TITLE
Can't change default admin password on fresh install

### ISSUE THREAD

**Issue by abelgomez** [turtle0x1/LxdMosaic#282]
**Describe the bug**
Can't change default admin password on fresh install, the following error is thrown:
`{"state":"error","message":"Dont understand the path \/var\/www\/LxdMosaic\/src\/classes\/App\/RouteController.php 109"}`

Seems related to #274

**To Reproduce**
1. Install LxdMosaic on a fresh Ubuntu container as explained in README.md
2. Perform first login, and setup connection to an LXD server
3. Go to the settings section
4. Try to reset the admin password
5. The browser navigates to `https://<lxdmosaic-ip>/?password=my-pass`, showing the error:
`{"state":"error","message":"Dont understand the path \/var\/www\/LxdMosaic\/src\/classes\/App\/RouteController.php 109"}`

**Expected behavior**
The admin password is changed to `my-pass`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 (focal) running in a LXC inside Raspbian Buster
 - Browser: Firefox 82.0.3

**Additional info**

Users table in LXD_Manager database exists, and admin user exists and works. For the moment, I changed the password directly in the DB, but the "Reset password" functionality from the UI still does not work. 

BTW, there's a typo in the "reset password" instructions: the SQL statement for the `update` indicates ```update `user` set ...``` rather than ```update `Users` set ...```

I can confirm that the same error happens in another LxdMosaic instance I have just upgraded from 0.9.x to 0.10.2 following the upgrading instructions (https://github.com/turtle0x1/LxdMosaic/blob/master/UPGRADING.md#09x---0100).

**Comment by abelgomez** [comment]
After trying, testing, checking the requests and random errors raised by LxdMosaic, it seems it's caused by a race condition or any other timing/performance issue: if I wait several seconds (5-10s) before pressing the "submit" button, the password change seems to work...

**Comment by turtle0x1** [comment]
Thanks for the detailed report, ive just fresh installed in a container and not hit this issue, 

> The browser navigates to https://lxdmosaic-ip/?password=my-pass

This request should never happen (should be in request body)

but it _might_ happen if `globalUrls.settings.users.resetPassword` is some how `undefined` (setting this value to `undefined`  or `null` doesn't cause the same behaviour, its still a `POST`)

If you can cause the issue to happen reliably, there may be an error in the console that reveals the actual cause.

This is a strange one!

**Comment by abelgomez** [comment]
I tested again, and I can reproduce the issue reliably. But now, I noticed something I didn't notice past week: when I was waiting to update de password a few minutes, I was clicking the submit button; but when I was changing the password directly I was hitting the return key.

Thus, the issue does not seem to be a race condition/timing issue; but just simply how the action gets executed: either pusing the submit button or pressing enter. Sorry for not realizing earlier this difference.

**Comment by abelgomez** [comment]
BTW, I'm not seeing any error in the browser console since with the page change to `https://lxdmosaic-ip/?password=my-pass` the console gets cleared (and indeed, althought the `https://lxdmosaic-ip/?password=my-pass` shows an error, in fact is replied with a 200 status).

**Comment by turtle0x1** [comment]
Haha! Yes the enter key does it!

**Comment by abelgomez** [comment]
And related to the "ENTER key" issue, I noticed something else: there are quite a few dialogs that do not close when pressing ESC (such as "change password", "add user", "fetch logs", "create api key", "search", "create image alias", ...).

**Comment by abelgomez** [comment]
Great! Bug catched! 😊

**Comment by turtle0x1** [comment]
What im going todo is fix  this one particular `$.confirm` as it relates to this one issue & create a wider issue (+ PR) of going through all the confirms and updating the button actions (as there is quite a few!)  :smile:

**Comment by abelgomez** [comment]
Perfect, makes sense. I was simply too lazy to open an issue (and also didn't want to bother you with more open issues since the ESC problem is something minor). Thanks for fixing this.

**Comment by turtle0x1** [comment]
No worries, small things like that make up a big part of UX so im always happy to fix! 

(Its something im (quite rightly) frequently criticized on, all input helps!)
