### ISSUE TITLE
Memory Usage Seems Incorrect

### ISSUE THREAD

**Issue by sstubbs** [turtle0x1/LxdMosaic#284]
**Describe the bug**
When running free command on host and inside lxd containers memory usage is much lower than what is showed by lxd mosaic. 

**To Reproduce**
1. Install snap
2. create some containers
3. run free inside inside container
4. see difference in memory

**Expected behavior**
Memory usage to be similar

**Comment by turtle0x1** [comment]
LXDMosaic only uses the API value provided by LXD and unless ive miss understood the API (which I dont think I have) its an LXD problem;

For instance, you can run this command to see what LXD reports
```
root@root lxc query /1.0/instances/c1/state
{
        ....
	"memory": {
		"swap_usage": 0,
		"swap_usage_peak": 0,
		"usage": 188903424,
		"usage_peak": 433291264
	},
       ...
}
````

then when I run

```
lxc exec c1 bash
free -h
              total        used        free      shared  buff/cache   available
Mem:           15Gi       130Mi        15Gi          0B        50Mi        15Gi

```

**Comment by turtle0x1** [comment]
100% sure this isn't an LXDMosaic problem & matches the behaviour of the command line

Created an issue here

https://github.com/lxc/lxd/issues/8143

**Comment by sstubbs** [comment]
Thanks a lot @turtle0x1 sorry for the late reply.
