### ISSUE TITLE
Changing projects doesn't update all references

### ISSUE THREAD

**Issue by avsdev-cw** [turtle0x1/LxdMosaic#292]
**Describe the bug**
When you change projects, sometimes the pop-ups (eg create new container) still reference profiles, images etc from the previous project.

**To Reproduce**
Have more than 1 project, each with their own set of profiles and/or images.
Swap project
Create a container
Try to add either an image or profile to the container and the suggest list contains all of the previous project's entries, not the new project.

**Expected behavior**
Filtering of profiles/images should be done per project

Repeated on latest master (after a bit of update fixing because the latest pull broke the DB!)

**Comment by turtle0x1** [comment]
Hey ill take a look at this, in the meantime

> (after a bit of update fixing because the latest pull broke the DB!) 

What do you mean?

There is a new migration method, the following should bring your DB up to date `vendor/bin/phinx migrate -e mysql` (if you haven't worked it out already) - if you still faced issues what were they ? :smile:

**Comment by avsdev-cw** [comment]
Had not seen the new migration method. I manually ran the migration script #9 =]

**Comment by turtle0x1** [comment]
Oops, yeah you still need to import `0.9.0.sql` then run the migration command above!

**Comment by turtle0x1** [comment]
Hmm, does this happen on master or another version? (Cant duplicate)

**Comment by avsdev-cw** [comment]
Yup, on master. Have you got a method I can email/DM you a video link?

**Comment by turtle0x1** [comment]
In the commit logs you should see my email `git log` :)

**Comment by avsdev-cw** [comment]
Inbound
