### ISSUE TITLE
Avoid use of web CDN sources

### ISSUE THREAD

**Issue by avsdev-cw** [turtle0x1/LxdMosaic#293]
There are quite a few web CDN source files used (see a list below). This means that lxd-mosaic does not run on a network without internet access.

bootstrap: bootstrap.min.css
jquery: jquery-3.3.1.min.js
moment: moment.min.js
fontawesome: all.css
datatables: jquery.dataTables.min.css, jquery.dataTables.min.js, dataTables.bootstrap.min.js
tether: tether.min.js
chart (jsdelivr.net): Chart.min.js
jqueryContextMenu: jquery.contectMenu.min.css, jquery.contectMenu.min.js
jquery.ui.position.js

**Comment by turtle0x1** [comment]
Yeah definitely, this was on my mental `todo` list anyway :smile:
