### ISSUE TITLE
Snap refresh to '--edge' failing

### ISSUE THREAD

**Issue by dzidek23** [turtle0x1/LxdMosaic#311]
I was trying to update the current snap to the edge channel but I'm getting errors. It sticks to stable after update...

channels:
  latest/stable:    0+git.976d6e8 2020-10-30 (33) 106MB -
  latest/candidate: ↑
  latest/beta:      ↑
  latest/edge:      0+git.f6052d7 2020-12-12 (62) 109MB -
installed:          0+git.976d6e8            (33) 106MB -

xxx@linuxtest:~$ sudo snap refresh lxdmosaic --edge
error: cannot perform the following tasks:
- Run post-refresh hook of "lxdmosaic" snap if present (run hook "post-refresh":
-----
Phinx by CakePHP - https://phinx.org.

using config file .snaplxdmosaic62htdocsphinx.php
using config parser php
using migration paths
 - /snap/lxdmosaic/62/htdocs/db/migrations
using environment snap
using adapter sqlite
using database /var/snap/lxdmosaic/62/lxdMosaic
ordering by creation time

 == 20201009185423 UserProjectLimit: migrating
 == 20201009185423 UserProjectLimit: migrated 0.9762s

 == 20201030020554 StoreBackupProject: migrating
PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: tmp_Container_Backups.CB_Project in /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:181
Stack trace:
#0 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(181): PDO->exec('INSERT INTO `tm...')
#1 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/SQLiteAdapter.php(781): Phinx\Db\Adapter\PdoAdapter->execute('INSERT INTO `tm...')
#2 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/SQLiteAdapter.php(800): Phinx\Db\Adapter\SQLiteAdapter->copyDataToNewTable('tmp_Container_B...', 'Container_Backu...', Array, Array)
#3 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Db/Util/AlterInstructions.php(119): Phinx\Db\Adapter\SQLiteAdapter->Phinx\Db\Adapter\{closure}(Array)
#4 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(606): Phinx\Db\Util\AlterInstructions->execute('ALTER TABLE `Co...', Array)
#5 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(981): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps('Container_Backu...', Object(Phinx\Db\Util\AlterInstructions))
#6 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(484): Phinx\Db\Adapter\PdoAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
#7 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(434): Phinx\Db\Adapter\AdapterWrapper->executeActions(Object(Phinx\Db\Table\Table), Array)
#8 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(153): Phinx\Db\Adapter\TimedOutputAdapter->executeActions(Object(Phinx\Db\Table\Table), Array)
#9 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(722): Phinx\Db\Plan\Plan->execute(Object(Phinx\Db\Adapter\TimedOutputAdapter))
#10 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(629): Phinx\Db\Table->executeActions(true)
#11 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(688): Phinx\Db\Table->update()
#12 /snap/lxdmosaic/62/htdocs/db/migrations/20201030020554_store_backup_project.php(24): Phinx\Db\Table->save()
#13 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(106): StoreBackupProject->change()
#14 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(383): Phinx\Migration\Manager\Environment->executeMigration(Object(StoreBackupProject), 'up', false)
#15 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(356): Phinx\Migration\Manager->executeMigration('snap', Object(StoreBackupProject), 'up', false)
#16 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(123): Phinx\Migration\Manager->migrate('snap', 20201205160839, false)
#17 /snap/lxdmosaic/62/htdocs/vendor/symfony/console/Command/Command.php(258): Phinx\Console\Command\Migrate->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /snap/lxdmosaic/62/htdocs/vendor/symfony/console/Application.php(911): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /snap/lxdmosaic/62/htdocs/vendor/symfony/console/Application.php(264): Symfony\Component\Console\Application->doRunCommand(Object(Phinx\Console\Command\Migrate), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(69): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /snap/lxdmosaic/62/htdocs/vendor/symfony/console/Application.php(140): Phinx\Console\PhinxApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /snap/lxdmosaic/62/htdocs/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#23 {main}
-----)
xxx@linuxtest:~$

**Comment by turtle0x1** [comment]
Thanks for pointing this out, edge snap is building it takes 20mins~

If you wouldn't mind giving it another go in 30 minutes and reporting back that would be great (I did manage to duplicate the error so it should be fine :smile:)

**Comment by dzidek23** [comment]
I'll have no access to the machine in question for the next fortnight but testing the edge channel on my laptop seems to be working fine.
