### ISSUE TITLE
Restrict container/host access to users

### ISSUE THREAD

**Issue by venkatkrishnanr** [turtle0x1/LxdMosaic#317]
currently all users have access to all the servers and all containers. is it possible to restrict users access to specific containers or host machine?

**Comment by turtle0x1** [comment]
Yes its coming in `0.11.0` or is available on the edge snap channel now

In fact users other than admin wont be able to login in version `0.11.0` until they have been assigned to a project & server

**Comment by turtle0x1** [comment]
I've found some issues when installing `--edge` ill fix these up now

**Comment by turtle0x1** [comment]
Issue on edge are fixed, might be some issues - let me know if you find any! :smile:
