### ISSUE TITLE
Errors first run (& add Host)

### ISSUE THREAD

**Issue by andig91** [turtle0x1/LxdMosaic#331]
I have tried to install LxdMosaic around 20-25 times the last two days.
But I don't know, what i made wrong.
3 or 4 times the install script ended with an error.
Mostly the I got an error at "First Run" in Browser. (Error FirstRun.php oder Error AddHost.php)
2 or 3 times I had a success to complete the "First Run". I used a Test Host because I changed the host settings to look for this errors

A complete install until I can call the webpage with the browser only worked OOTB on Ubuntu.
LXC Containers with Debain & CentOS I have to fulfil manually some dependencies.

All my LXC/LXD Hosts was based on the "Ubuntu Appliance Image".
Tested on RPi LXC Host and in a VM LXC Host.
Tested with Script install and also with snap install.
Also tested on privileged container.
LXC Remote over Command Line is working fine.

I was looking the last two days for an equal bug-report, but it looks like nobody have this problem too.
I also think I made something wrong, but what?

Btw:
The Tool is looking great. Thank you. I hope I can use it soon.

**To Reproduce**
1. Install with Script or Snap
2. Open Webinterface
3. Complete the First Run Site.
4. See error "FirstRun.php" or "AddHost.php"
5. If no error: Add an extra host an get 

**Screenshots**
![image](https://user-images.githubusercontent.com/43803844/103576094-e65ec000-4ed2-11eb-8e00-e713d8aa23d1.png)

![image](https://user-images.githubusercontent.com/43803844/103576115-eced3780-4ed2-11eb-982d-128289dd23c7.png)

**Desktop (please complete the following information):**
Tested on Firefox & Safari on Mac.
In Chrome I had no (easy-klick) chance to accept the certificates.

I am not a "LXC-Pro", here are logs from the last test-container.
Log:

lxc test 20210104194854.441 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1152 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.monitor.test"
lxc test 20210104194854.444 WARN     cgfsng - cgroups/cgfsng.c:mkdir_eexist_on_last:1152 - File exists - Failed to create directory "/sys/fs/cgroup/cpuset//lxc.payload.test"
lxc test 20210104194854.446 ERROR    utils - utils.c:lxc_can_use_pidfd:1867 - Invalid argument - Kernel does not support waiting on processes through pidfds
lxc test 20210104194854.453 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1573 - No such file or directory - Failed to fchownat(17, memory.oom.group, 1000000000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )

**Comment by turtle0x1** [comment]
Sorry about that - thanks for opening a report, latest version was big change!

Okay so;

It fails to connect to the host but the admin password gets set and so first run cant be run again this is why you get the second error "cant run first run" - Ive made this transactional so failing to add the host doesn't cause this  error

The issue with "cant connect to host", are you sure you haven't got any firewalls in the way?

Have you made sure the `LXD` host is available over the network?

```
lxc config set core.https_address [::]
lxc config set core.trust_password some-secret-string #remember this you will be asked later
```
In about 20 minutes the edge snap will refresh with latest master branch so, to avoid it being any dependency / config errors lets try with that

You'll need to run `snap install lxdmosaic --edge` or `snap refresh lxdmosaic --edge`

**Comment by andig91** [comment]
Hey!

Thank you for the fast answer.
But I think I have bad news.

I got a new error after clicking "Launch LXDMosaic":
![image](https://user-images.githubusercontent.com/43803844/103590040-292d9180-4eed-11eb-9817-8fd087721037.png)

FYI: 
In the last 2 hours I noticed, that I have in another problem: 
"like firewall": Containers with macvlan can't communicate with LXC-Host.
https://discuss.linuxcontainers.org/t/from-containers-can-not-ping-host/6588
But there was so many tests and I have tested so many thinks across Host-Nodes and on the same. ;)
But the last test was from LXC-Container in VM-LXC-Host to another VM-LXC-Host. 
Ping was possible.
RPi as LXDMosaic was not possible. (snap "lxdmosaic" is not available on edge for this architecture (arm64))

On this point I had another question:
"Your Setup:" core.https_address [::] 
"Standard Setup:" core.https_address: :8443
Why I have to change this?
It`s the same, all IPs allowed. But not only one Port?!
Did I think wrong. (But I set it before)

Sry for my bad english.

regards 
Andreas

**Comment by turtle0x1** [comment]
Your right it wont work for a container trying to access a host on macvlan, but there isn't much I can do about that

`LXD client certificate is not trusted` implies your your trust password is wrong (I get that exact error if i put the wrong password in)

Set a trust password on your LXD host

`lxc config set core.trust_password MY_PASSWORD`

Then when running LXDMosaic you put your hosts IP address & then `MY_PASSWORD` from the above

I discovered a silly error on the edge channel but i've fixed it so you will do to a `snap refresh lxdmosaic` again

**Comment by andig91** [comment]
Hey!

Sry for the late answer.
Too much (mini) projects for the time after christmas-holidays.

Now I have tested it and I can confirm, that it is working on my system.

Thank you for your great work.

regards
