### ISSUE TITLE
memory stats are used in the storage part of the widget

### ISSUE THREAD

**Issue by hmodateresyc** [turtle0x1/LxdMosaic#332]
Memory stats are used in the storage part of the current usage widget:
https://github.com/turtle0x1/LxdMosaic/blob/3dec563a1389d13ea38f8942e169ac13ce3c360c/src/views/index.php#L974

**Comment by turtle0x1** [comment]
The dangers of copy n paste, well spotted 

Your welcome to submit a PR fixing it or ill take a look later!
