### ISSUE TITLE
Unable to access instance details - "Uncaught TypeError: Cannot read property 'toLowerCase' of undefined"

### ISSUE THREAD

**Issue by candlerb** [turtle0x1/LxdMosaic#341]
I have just installed LxdMosaic using `./installLxdMosaic.sh` inside an Ubuntu 20.04 container, and connected it successfully to the lxd host.

However, I am unable to get a console on an instance - or even get to the instance detail page.

When I click the name of the host ("nuc1") in the left-hand column, no list of containers is shown underneath it, even though the arrow changes to pointing downwards.

In the main panel, I _do_ see a list of running containers, and below that a list of stopped containers:

![image](https://user-images.githubusercontent.com/44789/106366954-0731fe00-6337-11eb-8719-2d0cf0d2bb7c.png)

But there's no "Console" button here.  I can however check a container and use Start, Stop or Delete buttons.

If I refresh, open the browser console and then click on the left-arrow beside the host again, I get an exception:

![image](https://user-images.githubusercontent.com/44789/106367166-91c72d00-6338-11eb-8509-92f8741e3bda.png)

If I have the console closed, refresh and click on left-arrow, then open console, I see two errors:

![image](https://user-images.githubusercontent.com/44789/106367222-ee2a4c80-6338-11eb-99e3-b069dc296af6.png)

I can see the 403 error in apache access log, although nothing in error log:

```
root@lxdmosaic:~# tail /var/log/apache2/access.log  | grep 403
X:X:X:X::X - - [30/Jan/2021:20:21:08 +0000] "GET /assets/lxdMosaic/favicons/manifest.json HTTP/1.1" 403 4707 "https://lxdmosaic.example.net/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
```

More info:

* Installation log [here](https://gist.github.com/candlerb/b785960478d7930fd7c078d20188b133)
* Host is running Ubuntu 18.04 with lxd 4.10 from snap
* Browser is Chrome 88 under macOS 10.14.6

**Comment by turtle0x1** [comment]
Doing  the following should fix this (feel free to re-open if it doesn't)

```
lxc exec lxd_mosaic_container

cd /var/www/LxdMosaic

git fetch

git checkout 0.11.5
```

**Comment by turtle0x1** [comment]
You will see console / terminal once you can access the drop down and select an instance!

**Comment by candlerb** [comment]
Awesome, it works great, thank you!

I see from the patch that the problem was something to do with `image.os`.  Indeed, when I open one of the affected instances, I see this:

![image](https://user-images.githubusercontent.com/44789/106368075-db1a7b00-633e-11eb-9356-18b4fbd79060.png)

So I think there are a couple of other minor problems there:
1. The HTML tags are escaped
2. It says "Cant [sic] find verison [sic]" - should be "Can't find version"

Cheers, Brian.

**Comment by candlerb** [comment]
One other thing - are you sure it's not a typo where it says "images.os" rather than "image.os" ?

```
./src/views/index.php:                if(details.config.hasOwnProperty("image.os") && details.config["images.os"] != null){
                                                                                                      ^^^^^^^^^
```

**Comment by turtle0x1** [comment]
lol oops, ill fix that

**Comment by turtle0x1** [comment]
New version 0.11.6 will fix both those things;

```
lxc exec lxd_mosaic_container bash

cd /var/www/LxdMosaic

git fetch

git checkout v0.11.6
```

**Comment by candlerb** [comment]
You rock sir!

It still says "Cant find verison" but I'll let you off that one :-)

**Comment by turtle0x1** [comment]
Spellings not my strong suite, ive pushed a fix but wont do another release just for that detail! :smile:

**Comment by candlerb** [comment]
Do you mind if I ask how you managed to locate the problem from that minimised browser backtrace? Or was it the only place where `toLowerCase` could be in error?

**Comment by turtle0x1** [comment]
As your suggesting it was really the only place it could be used in error, the full explanation is;

There was a couple of changes to the sidebar in 0.11.0 so i was kind of expecting there to be some issues,

My use of `toLowerCase` is quite low so starting from the top of the sidebar code i searched for `toLowerCase` and it only appeared once, in this particular case it was os image property missing (which I should have expected) and went from there

**Comment by candlerb** [comment]
Great, thanks for the explanation!
