### ISSUE TITLE
Tool tips for buttons at top right

### ISSUE THREAD

**Issue by candlerb** [turtle0x1/LxdMosaic#342]
**Is your feature request related to a problem? Please describe.**
This is a very minor suggestion, but as a new user, I found the purpose of the icons at the top right to be not immediately obvious, apart from the Logout one.

I now know they're Add Host, Create Container, Create VM.

**Describe the solution you'd like**
Add tooltips to these icons.  (Most of the other buttons do already have tooltips)

**Describe alternatives you've considered**
None

**Additional context**
These are the icons that don't currently have tooltips:
![image](https://user-images.githubusercontent.com/44789/106368450-6a289280-6341-11eb-8552-fd8b3a5359a1.png)

**Comment by turtle0x1** [comment]
Good idea, ive added this above!
