### ISSUE TITLE
Make the assets folder configurable

### ISSUE THREAD

**Issue by xuedi** [turtle0x1/LxdMosaic#347]
**Is your feature request related to a problem? Please describe.**
i have a config website admin.myserver.com where i have all my tools that i need to manage my server, i have /LxdMosaic configured to pass traffic to the LxdMosaic instance via proxy

**Describe the solution you'd like**
If there would be an option in the LxdMosaic app to tell it, that its assets are not anymore under `/assets`, but under `/LxdMosaic/assets`, the app hopefully works as usual

**Describe alternatives you've considered**
An alternative would be set set up LxdMosaic.admin.myserver.com but that rather does not fit with all the other tools together

**Comment by turtle0x1** [comment]
This will probably effect all URLs on the site (API, images & terminals)

I think a setting "domain name" for the `LXDMosaic` instance would fix this , ensuring I prefix all my URLs with the provided setting (in this case you would set it to `admin.myserver.com/LxdMosaic`)

**Development thoughts**

I dont think this would be to hard, I think the following would do it;

  - 24 "hard links" for  JS, CSS & favicons in `index.php` prefixed with setting
  - 17 "hard links" for  JS, CSS & favicons in `login.php` prefixed with setting
  - Modify `ajaxRequest` to auto prefix all the API URLs to keep the object with all the URLs "clean"
  - Terminals & console code will probably also need a look over

My main concern would be the difference between SNAP & container installs, snap is likely to be `localhost`  and a container is likely to be an IP address so the default URL would probably have to be blank or just a `/` which may be confusing to the user but there go!

Why dont I just make all the URLs relative? I'm pretty sure a "#" making its way into the URL (as it does) will end up with malformed URLS like `lxd.local/#/api` which wont work so its not an option!

**Comment by xuedi** [comment]
That might work, i am also a php dev myself, if you tell me how to get the app working locally, i can create a PR myself :-) 
I am a bit unsure what the setup is after composer, never worked with that frontend before (gulp and stuff).

cronjobs via crunz i assume, is there a standalone run command?

I would also like to add a makefile for ex: https://github.com/xuedi/ImageViewer/blob/master/Makefile that might make it a bit more easy to get started.

cheers

**Comment by turtle0x1** [comment]
Sorry about the delayed response, it was late last night & had work today.

Right now i'm in a funny place with regards to pull requests as im likely to start monetizing the project for users with more than 3 or 5 servers (nothing set in stone yet), 

This means Ill need (at minimum) to take the "linux kernal style" approach of asking contributors to forgo copyright claims on their contributions as its likely I will have to re-license the project (I'm already going to have a hard enough time reaching out to the few existing contributors)

If you dont mind those conditions Im happy to share how to  setup a dev environment, if not ill take a look at this today / tomorrow anyway as I like to implement user requests quickly compared to my own "ideas" or features.

**Comment by turtle0x1** [comment]
@xuedi i take it that bothers you, so Ill take a look at this in the next hour or two if I dont here back (not expecting you to-do it today)

**Comment by xuedi** [comment]
Hey, sorry, i was also away from digital equipment :-) i am ok, i just like to run the app on my local machine out of the container and be able to make adjustments.

**Comment by turtle0x1** [comment]
Out of a container might be a slightly risky environment but on your own head be it :smile: 

You can extract the full instructions from the install script [here](https://github.com/turtle0x1/LxdMosaic/blob/master/examples/install_with_clone.sh) but you dont want to run this script on your host system as it may break stuff

Basic setup would be something like this;

 - install dependencies (get from install script)
 - Clone repository 
 - run `composer install`
 - run `npm i`
 - Create a database in MySQL
 - Import the `sql/*.sql` files (in order, these are "legacy" now)
 - Setup your `.env` file
 - Run the new database migrations `vendor/bin/phinx migrate -e mysql` 
 - Copy the apache2 config to `/etc/apache2/sites-available`
 - Restart apache
 - Good to go

Happy to answer any more specific questions as they come up :smile: (Im based in the UK  and am most available between 18:00 - 23:00)

**Comment by turtle0x1** [comment]
Hey, I dont like closing issues opened by others without a fix but I think in the case im going to sorry! :disappointed: :heart: 

I dont need the feature and I think it will overcomplicate giving support (especially in SNAP).
