### ISSUE TITLE
[question] How many people uses LxdManager?

### ISSUE THREAD

**Issue by lhorace** [turtle0x1/LxdMosaic#35]
Hey there,

I was wondering, how many people uses LxdManager, and is the Issues forum the best way to contact? Eg, support questions? And, how are you about Pull Requests?

Regards

**Comment by turtle0x1** [comment]
Short answer I have no real way of knowing, I don't track users on the system

Github says there is about 5 - 10 unique cloners a week at the moment but Im not sure how many stick with it, 

Pull requests and issues are fine, I own the domain for the new name so I may setup some email address for questions etc

Thanks!

**Comment by lhorace** [comment]
Thanks for the reply. I was curious how serious you were about development. I've been using LXDUI locally, but it's useless here. There were too many limitations that  reverting to CLI was easier to manage. And it seems to me that LXDUI is stale. I'm going to build a ArchLinux, and wanted a Frontend, easy to use, for Docker, Qemu, and LXC. I'm glad I find something that might be useful.

**Comment by turtle0x1** [comment]
Give it a try, Im not sure it will 100% eliminate your use of the CLI, there is currently no console for the container built into the web app, 

But give it ago and add any issues you like ill get round to them 

Thanks again!

**Comment by lhorace** [comment]
Will do, it's on my ToDo list, so anytime between now and whenever I feel like sitting down and working on it. xD
