### ISSUE TITLE
Installing in Container on arm based host

### ISSUE THREAD

**Issue by flaep** [turtle0x1/LxdMosaic#352]
Hi,

I am trying to install mosaic on my qnap nas.
The Container is a Ubuntu 20.04 based 
uname -a                                                                                                                                                     
> Linux lxdmosaic 4.2.8 #2 SMP Tue Feb 2 08:46:50 CST 2021 armv7l armv7l armv7l GNU/Linux

lsb_release -a                                                                                                                                               
> No LSB modules are available.                                                                                                                                                    
> Distributor ID: Ubuntu                                                                                                                                                           
> Description:    Ubuntu 20.04.2 LTS                                                                                                                                               
> Release:        20.04                                                                                                                                                            
> Codename:       focal             

 there is a warning shown while running the script:
> update-alternatives: using /usr/bin/python2.7 to provide /usr/bin/python (python) in auto mode                                                                                   
> npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upg  
> de to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)                                                                                                          
> /usr/bin/pm2 -> /usr/lib/node_modules/pm2/bin/pm2                                                                                                                                
> /usr/bin/pm2-dev -> /usr/lib/node_modules/pm2/bin/pm2-dev                                                                                                                        
> /usr/bin/pm2-docker -> /usr/lib/node_modules/pm2/bin/pm2-docker                                                                                                                  
> /usr/bin/pm2-runtime -> /usr/lib/node_modules/pm2/bin/pm2-runtime                                                                                                                
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):                                                  
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})  

the installation fails with the following lines at the end:
> 
> gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.24.0"                                                                             
> gyp WARN EACCES attempting to reinstall using temporary dev dir "/var/www/LxdMosaic/node_modules/bufferutil/.node-gyp"                                                           
> gyp WARN install got an error, rolling back install                                                                                                                              
> gyp WARN install got an error, rolling back install                                                                                                                              
> gyp ERR! configure error                                                                                                                                                         
> gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/www/LxdMosaic/node_modules/bufferutil/.node-gyp'                                                                    
> gyp ERR! System Linux 4.2.8                                                                                                                                                      
> gyp ERR! command "/usr/bin/node" "/var/www/LxdMosaic/node_modules/node-gyp/bin/node-gyp.js" "rebuild"                                                                            
> gyp ERR! cwd /var/www/LxdMosaic/node_modules/bufferutil                                                                                                                          
> gyp ERR! node -v v10.24.0                                                                                                                                                        
> gyp ERR! node-gyp -v v3.8.0                                                                                                                                                      
> gyp ERR! not ok                                                                                                                                                                  
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):                                                                                         
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})               
>                                                                                                                                                                                  
> npm ERR! code ELIFECYCLE                                                                                                                                                         
> npm ERR! errno 1                                                                                                                                                                 
> npm ERR! bufferutil@4.0.1 install: `node-gyp-build`                                                                                                                              
> npm ERR! Exit status 1                                                                                                                                                           
> npm ERR!                                                                                                                                                                         
> npm ERR! Failed at the bufferutil@4.0.1 install script.                                                                                                                          
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                               
>                                                                                                                                                                                  
> npm ERR! A complete log of this run can be found in:

There is no path given for the complete log.

Just running the script again gives the error
> fatal: destination path 'LxdMosaic' already exists and is not an empty directory.

**Comment by turtle0x1** [comment]
Hmm, dont have an ARM platform lying around at the moment - i can try and set one up later

In the meantime can you try

```
lxc exec your_instance bash
cd /var/www/LxdMosaic
npm i --unsafe-perm
```

**Comment by flaep** [comment]
sudo  npm i --unsafe-perm                                                                               
 [sudo] password for ubuntu:                                                                                                                                                                                                                                                          
> > bufferutil@4.0.1 install /var/www/LxdMosaic/node_modules/bufferutil                                                                       
> > node-gyp-build                                                                                                                            
>                                                                                                                                             
> make: Entering directory '/var/www/LxdMosaic/node_modules/bufferutil/build'                                                                 
>   CC(target) Release/obj.target/bufferutil/src/bufferutil.o                                                                                 
>   SOLINK_MODULE(target) Release/obj.target/bufferutil.node                                                                                  
>   COPY Release/bufferutil.node                                                                                                              
> make: Leaving directory '/var/www/LxdMosaic/node_modules/bufferutil/build'                                                                  
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.12 (node_modules/fsevents):                                                    
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":
> "linux","arch":"arm"})                                                                                                                      
>                                                                                                                                             
> added 1 package from 1 contributor and audited 597 packages in 15.974s                                                                      
>                                                                                                                                             
> 7 packages are looking for funding                                                                                                          
>   run `npm fund` for details                                                                                                                
>                                                                                                                                             
> found 1 low severity vulnerability                                                                                                          
>   run `npm audit fix` to fix them, or `npm audit` for details                                     

What is the expected outcome of this command?
Running the install again:

> fatal: destination path 'LxdMosaic' already exists and is not an empty directory.

and the following warnings

> npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js env
> ironment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)                                
> /usr/bin/pm2 -> /usr/lib/node_modules/pm2/bin/pm2                                                                                           
> /usr/bin/pm2-dev -> /usr/lib/node_modules/pm2/bin/pm2-dev                                                                                   
> /usr/bin/pm2-docker -> /usr/lib/node_modules/pm2/bin/pm2-docker                                                                             
> /usr/bin/pm2-runtime -> /usr/lib/node_modules/pm2/bin/pm2-runtime                                                                           
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):             
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"
> linux","arch":"arm"})   

I also setup a new 18.04 container. The installation fails aswekk with the same permission and bufferuttil errors.
Btw. as far as i know, I cant just lxc exec on the NAS. Qnap offers an app called ContainerStation that manages lxc and docker. From there I can of cause get shell access.
I'll try to setting up an raspberry to check if it makes any difference.

**Comment by turtle0x1** [comment]
Great, so what I think has happened is  that a pre-built binary wasn't available for you OS - `node-gyp` tried to build it instead but couldn't (because it didn't have permissions, should have noticed you weren't running with `sudo`)

Now its managed to install the dependencies for LxdMosaic so now we need to run the rest of the setup script, using your favourite editor comment out line 70 on the install script so that 

`git clone https://github.com/turtle0x1/LxdMosaic.git || exit $?`

looks like

`#git clone https://github.com/turtle0x1/LxdMosaic.git || exit $?`

And re-run the script, hopefully that should complete the install!

**Comment by flaep** [comment]
this worked. LxdMosaic is running, as far as I can tell. ^^
Thank you.

I do however not quiet understand the part about not running as root. I always run the script with sudo and followed https://lxdmosaic.readthedocs.io/en/latest/.
Have I missed any prequisite or is my container just weird?
