### ISSUE TITLE
Onboard all external assets so there will be no external dependency

### ISSUE THREAD

**Issue by k3idii** [turtle0x1/LxdMosaic#358]
**Is your feature request related to a problem? Please describe.**
LXD Mosaic cannot be used offline now due to usage of jquery & bootstrap being linked from CDN's

**Describe the solution you'd like**
Ship all scripts w/ release

**Describe alternatives you've considered**
Hacking code myself

**Additional context**
No ctx.

**Comment by turtle0x1** [comment]
Welcome, this has already been done! 😊 

I think its been released, are you up to date?

**Comment by k3idii** [comment]
:-)
Guess next step is to provide apt/yum based upate process to skip manual updates ;)

Much thanks. Good work on that project.

**Comment by turtle0x1** [comment]
Im sure you wont like this answer if you like apt / yum, but there is a SNAP if you want that experience :wink: 

I would be open to someone else packaging it but I probably wont ever take it on!
