### ISSUE TITLE
ldap login using something other than cn

### ISSUE THREAD

**Issue by aivanise** [turtle0x1/LxdMosaic#359]
**Is your feature request related to a problem? Please describe.**
We prefer using logins or email addresses instead of CN's when logging in with LDAP, as they are usually not only shorter but also less ambiguous, i.e. the common names in our setup are the user's real names, which can be misspelled or spelled differently than the user expects (think people with several surnames or hereditary titles).

**Describe the solution you'd like**
In the LDAP config box it should be possible to configure a filter which (if filled) would be used to look up user's CN.

this is the code we use to illustrate better what I mean

```php
  $server = "ldaps://ldap.example.com:636":
  $basedn = "ou=People,dc=exampledc,dc=com"; // base dn
  $filter = "(|(uid=$user)(mail=$user))"; // where to look for specified "user name"

  // Connect anonymously and get user data
  $connect = ldap_connect( $server) or die( "Could not connect to LDAP server");
  $bind = ldap_bind( $connect, "", "") or die( "Could not anonymously bind");

  // NOTE lowercase attribute names:
  $attrs = array( "dn", "title", "sn", "givenname", "cn", "mailaccount", "mail",
      "jiraoldaccount", "uid", "ou", "l");
  $search = ldap_search( $connect, $basedn, $filter, $attrs);
  $entries = ldap_get_entries( $connect, $search);
  ldap_unbind( $connect);
  
  $fullname = $entries[0]['cn'][0];
  $dn = "cn=" . $fullname . "," . $basedn;

  $connect = ldap_connect( $server) or die( "Could not connect to LDAP server");

   // Try to bind with supplied password

   $bind = @ldap_bind( $connect, $dn, $password);
   if( ldap_error( $connect) != "Success") {
      $error = "Error [$user]: " . ldap_error( $connect) . "("
          . ldap_errno( $connect) . ")" . "\n";
      return;
     ldap_unbind( $connect);
  }
```

**Comment by turtle0x1** [comment]
Welcome :smile: 

Thanks for the code example, will be a massive help! 

Ill make sure to take a look at this for the next release!

**Comment by aivanise** [comment]
thanks, so far what I've seen looks pretty impressive, im available for testing if you need me
