### ISSUE TITLE
apitoken requires an userid?

### ISSUE THREAD

**Issue by aivanise** [turtle0x1/LxdMosaic#360]
shouldn't the token be enough to identify the user? If I put in just a token it complains

```
# curl -sSk 'https://alex-test.2e-systems.com/api/Instances/GetInstanceController/get'   -H 'apitoken: uyb0zd2l6pm'  --data-raw 'container=ben&hostId=1'   --compressed 
{
  "error": "Missing either user id or token"
}

```
but this works:

`root@alex-test:~# curl -sSk 'https://alex-test.2e-systems.com/api/Instances/GetInstanceController/get'   -H 'apitoken: uyb0zd2l6pm' -H 'userid: 1'  --data-raw 'container=ben&hostId=1'   --compressed 
`

Also is there an API documentation somewhere? I reconstructed the above from the chrome dev tools as I couldn't find anything anywhere.

**Comment by turtle0x1** [comment]
Yep you are right requiring the `userId` is stupid, at the moment the system relies on it being provided quite heavily so this will bit a bit more fiddly to replace but should be do-able! (If you want to script now, the system will ignore the provided `userId` in the future)

The quite old issue #179 was to improve the API for when other people might want to use it but I never got round to it as I've never really been asked about it before.

There isn't documentation anywhere because I never really expected people to use my API! What are you trying to achieve?

**Comment by aivanise** [comment]
My idea is to use your api as a (logging) gateway to the real API. My biggest grief with lxd is that there is no real access control, it's either all or nothing. (BTW it is not currently possible for me to set record actions to 1 in the settings screen)

I would hand out tokens to devs and/or create small GUIs or CLIs for self service. For that I would also need to be able to restrict what an individual token can do, e.g. stop/start a container but not create, launch but only certain images on certain hosts/clusters, etc. etc.

**Comment by turtle0x1** [comment]
You should definitely be able to set recorded actions to 1, not sure what's going on there - anything in the dev tools after clicking save? It records everything & gives you something like this for a user overview & you can look at specific instance events aswell!

![Screenshot from 2021-03-25 15-44-09](https://user-images.githubusercontent.com/12494629/112501285-0474e780-8d81-11eb-99c8-1ad5645bf5e6.png)

As for access control, currently users can be restricted to hosts & projects (including access to one project on one member of a cluster) but there isn't RBAC :disappointed:  but it is on the list #327, maybe you could add some thoughts there? I dont have a great need for RBAC so input on the kind of restrictions people want would be good!

**Comment by aivanise** [comment]
When I click on the green save icon absolutely nothing happens in devtools, I see in the LDAP box /api/InstanceSettings/Ldap/SaveLdapSettingsController/save is called, but in the main one, nothing

I've ran update Instance_Settings_Values set ISV_Value=1 where ISV_IS_ID=2; so its not really a biggie

yeah, I've already noticed you could restrict users to hosts, this is already fairly useful, will update #327 with my ideas

**Comment by turtle0x1** [comment]
Ive changed my mind on this, without a user ID we would have to load every token in the database and validate against it.

If I was to implement JWT its likely id be in agreement with this proposal but I dont think requiring the user ID is unusual in the current work flow.
