### ISSUE TITLE
cluster node without containers is not counted

### ISSUE THREAD

**Issue by aivanise** [turtle0x1/LxdMosaic#361]
its not fair that the cluster without any containers is not recognised as a first class citizen ;)

lxd3 here has no containers

BTW is there a way to rename a cluster? 'Cluster 0' is not very informative.

![image](https://user-images.githubusercontent.com/3426040/112497964-5f5d0d80-8d86-11eb-8939-bdd2c53bcc36.png)

**Comment by turtle0x1** [comment]
Yep this one is silly. I finish work in an hour or so ill take a look then!

Clusters don't exist as a database entity anywhere so ill track that as a separate issue!

**Comment by aivanise** [comment]
it might not be that, i have created a container on lxd3 in the meantime but the page still says the same

**Comment by turtle0x1** [comment]
For some reason the code is `if (hostsInCluster <= 3) { showWarning }`  when it should be `if (hostsInCluster < 3) { showWarning }`
