### ISSUE TITLE
if any of the hosts goes offline, nothing works

### ISSUE THREAD

**Issue by aivanise** [turtle0x1/LxdMosaic#362]
somewhat of a duplicate of #152 but with a default dashboard, if any of the configured hosts goes down, everything goes away until it is back, the only thing you get is a modal saying "its likely a host has gone offline, refresh the page" and an unclickable Dashboard link.

![image](https://user-images.githubusercontent.com/3426040/112598524-fe2d4c80-8e0e-11eb-857e-51331496ddfb.png)

**Comment by turtle0x1** [comment]
I think i may have fixed this already, i usually run with 1/2 offline hosts.

I will investigate!

**Comment by turtle0x1** [comment]
@aivanise if your still using LXDMosaic please could you confirm this issue still exists? I'm running with a host offline right now with no problems!

**Comment by aivanise** [comment]
I have tried to upgrade to latest 0.12.0 (at least its the latest according to the install scripts in exapmples/) and the problem is still there

here are the steps I did, as I don't see any official upgrade script anywhere, am I missing something?
```

  525  cd /var/www/
  526  mv LxdMosaic LxdMosaic.0.11.6/
  527  git clone https://github.com/turtle0x1/LxdMosaic.git || exit $?
  528  mkdir -p /var/www/LxdMosaic/src/sensitiveData/certs
  529  mkdir -p /var/www/LxdMosaic/src/sensitiveData/backups
  530  cp /var/www/LxdMosaic.0.11.6/src/sensitiveData/certs/* /var/www/LxdMosaic/src/sensitiveData/certs
  531  chown -R www-data:www-data /var/www/LxdMosaic/src/sensitiveData/
  532  cd /var/www/LxdMosaic || exit
  536  git checkout v0.12.0
  537  npm install || exit $?
  538  cp ../LxdMosaic.0.11.6/.env .
  539  export COMPOSER_ALLOW_SUPERUSER=1; composer install --no-dev || exit $?



```

**Comment by turtle0x1** [comment]
You will also need todo `vendor/bin/phinx migrate -e mysql`!  (you should check the [upgrade file](https://github.com/turtle0x1/LxdMosaic/blob/master/UPGRADING.md) for instructions)

I will try to duplicate this issue again

**Comment by aivanise** [comment]
yeah, I did that too, forgot to paste. Anyway just tried on the fresh installation just to make sure I didn't break anything while fiddling around and it is still there.

**Comment by turtle0x1** [comment]
I have run with a host offline for a few days on master branch apart from the above 2 commits I couldn't find any other issues.

If a host goes offline "randomly" the next request that tries to use that server catches the timeout and sets the host to offline, it is "slow" and a faster check could be implemented using the events socket but its abit "extra" and any requests being processed would still trigger the PHP code.

I'm going to close this, if it still happens on master please add steps to reproduce.

**Comment by turtle0x1** [comment]
This really isn't fixed, i see it with my laptop now - reopening
