### ISSUE TITLE
Delete host error

### ISSUE THREAD

**Issue by mrlicmi** [turtle0x1/LxdMosaic#365]
When I try to delete the host i get an error that is stating: 
"Sql state 23000
Integrity constraint violation. 1451 Cannot delete or update a parent row: a foreign key contraint fails ....
 
1. Change ip adress of lxd mosaic VM or change the name of Ethernet adapter or the bridge on which that nic is.

**Screenshots**
![lxdmosaic1](https://user-images.githubusercontent.com/7086110/113762053-756cb580-9718-11eb-9a6a-c8597edf939c.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS
 - Browser: Firefox
 - Version: 87

**Comment by turtle0x1** [comment]
Ah yeah its part of #287, but I should probably add a feature for changing the address.

Are you using a container or snap?

**Comment by mrlicmi** [comment]
I am sorry for repeating it.

I am using container.

**Comment by turtle0x1** [comment]
No worries, 

You can probably rescue this by doing something like;

```
lxc exec lxdmosaic bash

root@lxdmosaic # mysql 

mysql> use LXD_Manager;

mysql> select * from Hosts;

# Note your host Id

mysql> UPDATE Hosts SET `Host_Url_And_Port` = "https://MY_NEW_IP:8443" WHERE `Host_ID` = HOST_ID_FROM_ABOVE 

mysql> exit
# Restart node
root@lxdmosaic # pm2 restart all
# Restart apache for good measure although probably not required
root@lxdmosaic # service apache2 restart
```

Cert files will have the wrong names but thats not the end of the world, DNS might be a better option if your IP changes frequently as deleting hosts will loose your backup schedules and metric data in the future!
