### ISSUE TITLE
Selecting a variant when importing images

### ISSUE THREAD

**Issue by Simon-L** [turtle0x1/LxdMosaic#380]
**Is your feature request related to a problem? Please describe.**
As of today I have not found a way to import the "cloud" variant of container images through the Images section of lxdMosaic which makes Cloud Config unusable, as far as I have found.

**Describe the solution you'd like**
Adding a variant filter in the Import image page

**Describe alternatives you've considered**
I've had to do it on the command line, like: `lxc launch images:debian/11/cloud` and then delete, and then the image is available in lxdMosaic!

**Additional context**
It seems to me the Virtual Machine images have cloud support by default, that's another work around.

Would be happy to help working on that, I'm getting up to speed with php lately so that's the perfect fit :) !

**Comment by turtle0x1** [comment]
Great spot! The behaviour before was definitely buggy & unpredictable!

Thanks for the offer to help but its a bit of a weird implementation on this particular set of code, if you feel you can improve it further you can look a the pull request and have a go from there - happy to answer any questions! :smile:
