### ISSUE TITLE
timeouts for non-admin users

### ISSUE THREAD

**Issue by aivanise** [turtle0x1/LxdMosaic#388]
**Describe the bug**
if I test with an admin user, everything works more or less but if I create a new user or sync users from LDAP i get a timeout

[Tue Jun 01 09:24:37.748932 2021] [php7:error] [pid 469] [client 192.168.220.1:52668] PHP Fatal error:  Maximum execution time of 30 seconds exceeded in /var/www/LxdMosaic/src/classes/Objects/HostsCollection.php on line 56, referer: https://lxdmosaic.2e-systems.com/

if i increase the timeout to 300 seconda, sometimes I get a timeout in some wild place

[Tue Jun 01 09:31:54.636931 2021] [php7:error] [pid 1842] [client 192.168.220.1:52700] PHP Fatal error:  Maximum execution time of 300 seconds exceeded in /var/www/LxdMosaic/src/classes/Objects/Host.php on line 3444088416, referer: https://lxdmosaic.2e-systems.com/
[Tue Jun 01 09:38:40.200941 2021] [php7:error] [pid 1843] [client 192.168.220.1:52778] PHP Fatal error:  Maximum execution time of 300 seconds exceeded in /var/www/LxdMosaic/src/classes/Objects/HostsCollection.php on line 56, referer: https://lxdmosaic.2e-systems.com/

i also get 

[Tue Jun 01 09:42:37.420985 2021] [core:notice] [pid 228] AH00052: child pid 1842 exit signal Segmentation fault (11)

**To Reproduce**
1. create a user
2. grant user access to some hosts and projects
3. log in as that user
4. all you get is a spinning sprocket (see screenshot)

**Expected behavior**
it should work the same as for admin user

**Screenshots**
![image](https://user-images.githubusercontent.com/3426040/120302517-47e25980-c2ce-11eb-9468-469a180eb0ad.png)

**Desktop (please complete the following information):**
 - OS: OSX 10.15.7
 - Browser Chrome 
 - Version 90.0.4430.212 (Official Build) (x86_64)

**Additional context**
its basically a vanilla installation done with https://raw.githubusercontent.com/turtle0x1/LxdMosaic/master/examples/install_with_clone.sh, all I did is configure the lxd cluster admin user and LDAP sync. Even creating a non-LDAP user ends up in the same way. Access granted is the default project, no other projects are there.

looked in the database, no hanging queries

root@lxdmosaic:/var/log/apache2# cat /etc/*version*
bullseye/sid
Ubuntu 20.04.2 LTS (Focal Fossa)

any pointers in how to debug this further are apreciated.

**Comment by turtle0x1** [comment]
How odd, line 56 is a trivial line of code so I suspect its going wrong long before

https://github.com/turtle0x1/LxdMosaic/blob/6735ed9de0c57583829621ebdb93fdf7a2a9cf6f/src/classes/Objects/HostsCollection.php#L56

Could it be not correctly setting a host offline in the DB, then tries some HTTP request to that host and it just hangs for a really long time awaiting a response? Is one of the hosts offline? If so you could try manually setting the host offline the mysql database

**Comment by aivanise** [comment]
all the hosts are online, and everything works if the user is 'admin', it does not work if the user is either manually created or synced from LDAP.

I also see apache process using up a full CPU core

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
    232 www-data  20   0  287476  26528  16592 R 100.0   0.3   0:32.09 apache2

i would think its something with apache/php, but why is it working for an admin user?

**Comment by turtle0x1** [comment]
Hmm interesting, of course this is tested so im not entirely sure what's gone wrong here!

If you open the browser developer console do any of the HTTP requests return?

Is this master or the latest commit?

I've just tested a similar setup and not run into the same issue, so if its possible to arrange access that might work? (my test system has 4000 users, local account though not LDAP)

**Comment by aivanise** [comment]
it was v0.12.0, but I've switched to master and the same thing happens. in the developer console all requests return except the one to Request URL: https://lxdmosaic.2e-systems.com/api/Dashboard/GetController/get which returns HTTP 500, which is natural since it is a timeout

I can arrange acces if you give me your public ssh key

**Comment by aivanise** [comment]
I have narrowed it down to cluster access, I have one standalone host and one three member cluster. If I grant access to the standalone host it works, as soon as I attempt to add cluster to any (or all three) of the cluster members it starts blocking. So it's either something with my cluster or with clusters as such.

**Comment by turtle0x1** [comment]
Sorry, I became flat out at work and i forgot to "circle back".

That sounds like a promising lead, ill try and replicate with a cluster later!

**Comment by aivanise** [comment]
I have debugged a bit further, it loops in /var/www/LxdMosaic/src/classes/Tools/Universe.php:155: where you try to delete cluster hosts to build a  list of standalone hosts. However as soon as you delete one cluster host, it keeps looping


       foreach ($hosts as $i => $host) {
            var_dump($hosts);
            if (in_array($host->getHostId(), $hostsInClusterGroups)) {
                if (gettype($hosts) == "array") {
                    unset($hosts[$i]);
                } else {
                    $hosts->removeHostId($host->getHostId());
                }
            }
        }

This is now too esoteric for me, sounds like a "feature" of php :)

I've put a var_dump in line 156 and attached the outpput, hope this helps
[bb.txt](https://github.com/turtle0x1/LxdMosaic/files/6611430/bb.txt)

**Comment by turtle0x1** [comment]
Hey sorry in the delay! 

If you could test the pull request I have opened that would be great, let me know of any issues :smile: 

The tests dont cover a cluster setup as I was either being lazy or thought it would be hard - I should really look into making that part of it.

**Comment by aivanise** [comment]
works like a charm! Many thanks!
