### ISSUE TITLE
No host found after fresh installation

### ISSUE THREAD

**Issue by kimjohans** [turtle0x1/LxdMosaic#389]
**Describe the bug**
I freshly installaed mosaic like described in the readme under "Ubuntu (18.04 & 20.04) / Debian (Buster & Bullseye)"
After it finished, i connected to the displayed IP and acceppted the self ssl certificate. no problems.

![image](https://user-images.githubusercontent.com/43292439/120306971-bd502900-c2d2-11eb-945a-b4b6345d70a5.png)

But now it asks for a host and user (no problem), but unimportant which IP/hostname i enter in "hostname" (given IP, localhost, 127.., hostname from apache conf, ...), it messages "Conot connect to ..."

f.eg. using the IP:
![image](https://user-images.githubusercontent.com/43292439/120307189-fc7e7a00-c2d2-11eb-9123-e84d1fee301e.png)

error:
![image](https://user-images.githubusercontent.com/43292439/120307259-0dc78680-c2d3-11eb-8f0c-fe801ce84261.png)

LXD is running:
![image](https://user-images.githubusercontent.com/43292439/120307481-554e1280-c2d3-11eb-860b-bf2494779238.png)

**Expected behavior**
A better/clearer information about which IP or hostname has to entered i this case of "automatic" setup.

**Desktop (please complete the following information):**
OS: Linux Ubuntu (updated)
Browser: Firefox (updated)

**Comment by turtle0x1** [comment]
Have you set a secret password and enabled listening on the network? https://github.com/turtle0x1/LxdMosaic#prep-lxd-instances

**Comment by kimjohans** [comment]
Ok. That was my fault. I read that part, but forgot is during the container setup. Sorry and thanks. Maybe a reminder at the end of the installation would help others with similar problems.

Now it is no trusting the SSL certificate:
![image](https://user-images.githubusercontent.com/43292439/120309351-6f88f000-c2d5-11eb-81bd-c1889acfbaba.png)

in my previous setup i executed "lxdmosaic.enable-https self-signed" and everything worked find, but i am not able to find that command any more in the new environment. which step did i miss this time ?

**Comment by turtle0x1** [comment]
127.0.0.1 probably isn't valid in a SNAP, the IP should work fine - hmm 

You sure the password you entered for the host is the same password you entered here https://github.com/turtle0x1/LxdMosaic#prep-lxd-instances ?

**Comment by kimjohans** [comment]
Yes. Double checked and (because i have the bashes still open) i also copied the password (simple password, but sometimes even the simplest password can case typos)

**Comment by turtle0x1** [comment]
sure there is no firewall standing in the way?

**Comment by kimjohans** [comment]
Yes. Locally running (on same PC) without any firewall, switch, router ... nothing what could harm the traffic

**Comment by kimjohans** [comment]
I rebootet and now it is working. Maybe something screw up ? Thanks for your very kind and even faster responses !

**Comment by turtle0x1** [comment]
That is odd, I will try and duplicate this later maybe it was an Issue with the LXD settings taking effect (?) and a reboot put it straight (?)

**Comment by kimjohans** [comment]
The whole process is a bit tricky (maybe only for somebody beginning with lxdmosaic ?)
I had to run "lxd init" in the created container manually to get a storage etc.
Then i downloaded the debian buster image and create a new project names "test":

![image](https://user-images.githubusercontent.com/43292439/120313648-94339680-c2da-11eb-843f-40ea037c993b.png)

But that one would not start:
![image](https://user-images.githubusercontent.com/43292439/120313688-a281b280-c2da-11eb-910a-4bf7d518ddbf.png)

Tried to start in the bash and got this error:
`/snap/lxd/current/bin/lxd: error while loading shared libraries: liblxc.so.1: cannot open shared object file: No such file or directory`

**Comment by turtle0x1** [comment]
> LXD Init

Yea we dont run that part, its assumed you've got LXD setup before hand

>  create a new project names "test"

Im nit picking but I assume you mean `container` here, `projects` are a concept part of LXD so its important to use the correct terminology :smile: 

> /snap/lxd/current/bin/lxd: error while loading shared libraries: liblxc.so.1: cannot open shared object file: No such file or directory

This is likely a system / LXD error and not LXDMosaic, I cant say of the top of my head why this might happen!

What does the log file show?

There is a very old issue [here](https://github.com/lxc/lxd/issues/4198) that suggests its an issue with your system?

If you are running LXD in a container enabiling nesting might help `lxc config set YOUR_CONTAINER security.nesting true`

**Comment by turtle0x1** [comment]
as suggested by @bmullan you might have LXD installed from both SNAP & APT, if you are using the SNAP of LXD you need to remove the apt version!

**Comment by kimjohans** [comment]
No, i uninstalled the SNAP version previously.
I have my Ubuntu System running and (after uninstalling the SNAP version) i installed lxc/lxd from APT:
```
apt install lxc lxd
(...)
lxc ist schon die neueste Version (1:4.0.4-0ubuntu3).
lxd ist schon die neueste Version (1:0.9).
```
... what says (in german) that both packages are the current version.

After that, i ran "lxd init" and installed mosaic following the instructions (except my missed part with the secret password from above).

On my ubuntu pc, only the lxc container mosaic is running:```

lxc list
+-----------+---------+----------------------+-----------------------------------------------+-----------+-----------+
|   NAME    |  STATE  |         IPV4         |                     IPV6                      |   TYPE    | SNAPSHOTS |
+-----------+---------+----------------------+-----------------------------------------------+-----------+-----------+
| lxdMosaic | RUNNING | 10.207.98.1 (lxdbr0) | fd42:495f:e3e6:8a6f:216:3eff:fef8:c856 (eth0) | CONTAINER | 0         |
|           |         | 10.183.2.119 (eth0)  | fd42:1ba8:90b9:587b::1 (lxdbr0)               |           |           |
+-----------+---------+----------------------+-----------------------------------------------+-----------+-----------+
```

I rebooted and was able to login into mosaic, downloaded an image (debian buster) and then created a container (of course you're right: not a project) "test".

inside the mosaic container i have my text container:
```
lxc list
+------+---------+------+------+-----------------+-----------+
| NAME |  STATE  | IPV4 | IPV6 |      TYPE       | SNAPSHOTS |
+------+---------+------+------+-----------------+-----------+
| loe  | STOPPED |      |      | VIRTUAL-MACHINE | 0         |
+------+---------+------+------+-----------------+-----------+
| test | STOPPED |      |      | CONTAINER       | 0         |
+------+---------+------+------+-----------------+-----------+
```

that start failed.

```
lxc start test
Error: Failed to run: /snap/lxd/current/bin/lxd forkstart test /var/snap/lxd/common/lxd/containers /var/snap/lxd/common/lxd/logs/test/lxc.conf:
```

So i checked with `lxc info --show-log test`:

Name: test
Location: none
Remote: unix://
Architecture: x86_64
Created: 2021/06/01 10:51 UTC
Status: Stopped
Type: container
Profiles: lxdMosaicPullMetrics, default

Log:

```
lxc test 20210601123159.673 ERROR    cgfsng - cgroups/cgfsng.c:__cgroup_tree_create:771 - File exists - Creating the final cgroup 13(lxc.payload.test) failed
lxc test 20210601123159.675 ERROR    cgfsng - cgroups/cgfsng.c:cgroup_tree_create:831 - File exists - Failed to create payload cgroup 13(lxc.payload.test)
lxc test 20210601123159.675 ERROR    cgfsng - cgroups/cgfsng.c:__cgroup_tree_create:771 - File exists - Creating the final cgroup 13(lxc.payload.test-1) failed
lxc test 20210601123159.675 ERROR    cgfsng - cgroups/cgfsng.c:cgroup_tree_create:831 - File exists - Failed to create payload cgroup 13(lxc.payload.test-1)
lxc test 20210601123159.675 ERROR    cgfsng - cgroups/cgfsng.c:__cgroup_tree_create:771 - File exists - Creating the final cgroup 13(lxc.payload.test-2) failed
lxc test 20210601123159.675 ERROR    cgfsng - cgroups/cgfsng.c:cgroup_tree_create:831 - File exists - Failed to create payload cgroup 13(lxc.payload.test-2)
lxc test 20210601123159.675 ERROR    cgfsng - cgroups/cgfsng.c:__cgroup_tree_create:771 - File exists - Creating the final cgroup 13(lxc.payload.test-3) failed
lxc test 20210601123159.675 ERROR    cgfsng - cgroups/cgfsng.c:cgroup_tree_create:831 - File exists - Failed to create payload cgroup 13(lxc.payload.test-3)
lxc test 20210601123159.685 WARN     conf - conf.c:lxc_map_ids:3007 - newuidmap binary is missing
lxc test 20210601123159.689 WARN     conf - conf.c:lxc_map_ids:3013 - newgidmap binary is missing
lxc test 20210601123159.697 WARN     conf - conf.c:lxc_map_ids:3007 - newuidmap binary is missing
lxc test 20210601123159.702 WARN     conf - conf.c:lxc_map_ids:3013 - newgidmap binary is missing
lxc test 20210601123159.703 WARN     cgfsng - cgroups/cgfsng.c:fchowmodat:1296 - No such file or directory - Failed to fchownat(43, memory.oom.group, 999900000, 0, AT_EMPTY_PATH | AT_SYMLINK_NOFOLLOW )
lxc test 20210601123159.786 ERROR    utils - utils.c:safe_mount:1198 - Permission denied - Failed to mount "proc" onto "/var/snap/lxd/common/lxc//proc"
lxc test 20210601123159.787 ERROR    conf - conf.c:lxc_mount_auto_mounts:782 - Permission denied - Failed to mount "proc" on "/var/snap/lxd/common/lxc//proc" with flags 14
lxc test 20210601123159.787 ERROR    conf - conf.c:lxc_setup:3636 - Failed to setup first automatic mounts
lxc test 20210601123159.787 ERROR    start - start.c:do_start:1265 - Failed to setup container "test"
lxc test 20210601123159.787 ERROR    sync - sync.c:sync_wait:36 - An error occurred in another process (expected sequence number 5)
lxc test 20210601123159.787 WARN     network - network.c:lxc_delete_network_priv:3623 - Failed to rename interface with index 0 from "eth0" to its initial name "veth50a35656"
lxc test 20210601123159.787 ERROR    lxccontainer - lxccontainer.c:wait_on_daemonized_start:869 - Received container state "ABORTING" instead of "RUNNING"
lxc test 20210601123159.788 ERROR    start - start.c:__lxc_start:2073 - Failed to spawn container "test"
lxc test 20210601123159.788 WARN     start - start.c:lxc_abort:1017 - No such process - Failed to send SIGKILL via pidfd 44 for process 18904
lxc test 20210601123200.857 WARN     conf - conf.c:lxc_map_ids:3007 - newuidmap binary is missing
lxc test 20210601123200.903 WARN     conf - conf.c:lxc_map_ids:3013 - newgidmap binary is missing
lxc test 20210601123200.908 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_remove:473 - Permission denied - Failed to destroy 13(lxc.payload.test-4)
lxc test 20210601123200.912 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_remove:473 - Permission denied - Failed to destroy 14(lxc.payload.test-4)
lxc test 20210601123200.914 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_remove:473 - Permission denied - Failed to destroy 15(lxc.payload.test-4)
lxc test 20210601123200.915 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_remove:473 - Permission denied - Failed to destroy 16(lxc.payload.test-4)
lxc test 20210601123200.917 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_remove:473 - Permission denied - Failed to destroy 17(lxc.payload.test-4)
lxc test 20210601123200.918 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_remove:473 - Permission denied - Failed to destroy 18(lxc.payload.test-4)
lxc test 20210601123200.920 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_remove:473 - Permission denied - Failed to destroy 19(lxc.payload.test-4)
lxc test 20210601123200.921 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_remove:473 - Permission denied - Failed to destroy 20(lxc.payload.test-4)
lxc test 20210601123200.922 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_remove:473 - Permission denied - Failed to destroy 21(lxc.payload.test-4)
lxc test 20210601123200.923 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_remove:473 - Permission denied - Failed to destroy 22(lxc.payload.test-4)
lxc test 20210601123200.923 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_remove:473 - Permission denied - Failed to destroy 23(lxc.payload.test-4)
lxc test 20210601123200.924 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_remove:473 - Permission denied - Failed to destroy 24(lxc.payload.test-4)
lxc test 20210601123200.925 WARN     cgfsng - cgroups/cgfsng.c:cgroup_tree_remove:473 - Permission denied - Failed to destroy 25(lxc.payload.test-4)
lxc 20210601123200.111 ERROR    af_unix - af_unix.c:lxc_abstract_unix_recv_fds_iov:207 - Connection reset by peer - Failed to receive response
lxc 20210601123200.112 ERROR    commands - commands.c:lxc_cmd_rsp_recv_fds:129 - Failed to receive file descriptors
```

I cannot follow that "file exists" because that's a fresh setup and so there should not exists same files.
Even more irritating are the "Permission denied" messages, because i thnk the mosaic setup has created all required stuff ?

Maybe i dont see the forrest because of all the trees ?

**Comment by turtle0x1** [comment]
Thanks for the detailed report!

> Maybe i dont see the forrest because of all the trees ?

I mean you say your using APT, but the error references `/snap` so something is wrong, what does `snap list` output?

**Comment by kimjohans** [comment]
> inside the mosaic container i have my text container

i executed the logs etc from within the mosaic container.

**Comment by turtle0x1** [comment]
so on the host where you did `apt intall lxd` if you run `snap list | grep lxd` does it return any output?

**Comment by kimjohans** [comment]
Nothing to hide here ;)

`snap list`

returned:

```
Name               Version                     Rev    Tracking         Publisher     Notes
core18             20210507                    2066   latest/stable    canonical✓    base
core20             20210429                    1026   latest/stable    canonical✓    base
gnome-3-28-1804    3.28.0-19-g98f9e67.98f9e67  145    latest/stable    canonical✓    -
gtk-common-themes  0.1-52-gb92ac40             1515   latest/stable    canonical✓    -
rpi-imager         1.6.2                       184    latest/stable    popey         -
snapd              2.50                        11841  latest/stable    canonical✓    snap
```

**Comment by turtle0x1** [comment]
O i see (I think), this probably a nesting issue - to be clear you are saying;

 - One host
 - LXD Installed
 - Created a container called LXDMosaic
 - Installed LXD in the LXDMosaic container
 - Trying to start a container / VM in the LXDMosaic container doesn't work (?)

If this is the case i think you should be able to run `lxc config set lxdMosaic security.nesting true` on your PC, reboot the `lxdMosaic` container and then try running `lxc start test` should get you were you need to go (?)

**Comment by kimjohans** [comment]
Ok. Thanks, that brought one step forward, but now the networking is suddenly struggeling.

![image](https://user-images.githubusercontent.com/43292439/120330367-07de9f00-c2ed-11eb-8f3c-ec90d8a16270.png)

But listing the network seems to be quite ok:

On the host:
```
lxc network list
+--------+----------+---------+---------------+---------------------------+-------------+---------+
|  NAME  |   TYPE   | MANAGED |     IPV4      |           IPV6            | DESCRIPTION | USED BY |
+--------+----------+---------+---------------+---------------------------+-------------+---------+
| enp1s0 | physical | NO      |               |                           |             | 0       |
+--------+----------+---------+---------------+---------------------------+-------------+---------+
| lxcbr0 | bridge   | NO      |               |                           |             | 0       |
+--------+----------+---------+---------------+---------------------------+-------------+---------+
| lxdbr0 | bridge   | YES     | 10.183.2.1/24 | fd42:495f:e3e6:8a6f::1/64 |             | 2       |
+--------+----------+---------+---------------+---------------------------+-------------+---------+
| virbr0 | bridge   | NO      |               |                           |             | 0       |
+--------+----------+---------+---------------+---------------------------+-------------+---------+
```

Inside the mosaic container:```

root@lxdMosaic:~# lxc network list
+--------+--------+---------+-------------+---------+
|  NAME  |  TYPE  | MANAGED | DESCRIPTION | USED BY |
+--------+--------+---------+-------------+---------+
| lxcbr0 | bridge | NO      |             | 0       |
+--------+--------+---------+-------------+---------+
| lxdbr0 | bridge | YES     |             | 3       |
+--------+--------+---------+-------------+---------+
```

**Comment by turtle0x1** [comment]
Unfortunately i'm not an expert all the way down, you may have to ask on the LXD forums as this is a nested LXD issue not LXDMosaic!

As for `lxc network list` vs `networks` its probably that `lxc network list` applies some filters to hide additional networks client side - the LXD API returns them so I show them!
