### ISSUE TITLE
minor but annoying UI/UX issues

### ISSUE THREAD

**Issue by aivanise** [turtle0x1/LxdMosaic#393]
~In all entry fields like images, profiles, etc there is an autocompletion, but there is no way of seeing all available options, i have to know at least part of the name, OK for me, but my users are bitching ;)~ ACK but alot of work and I want to close this issue off as I've cleared the main things. Can always revisit later.

~In Cloud Config, what is the point of an image when you have to specify it again once you are deploying the config?~ (a71973a059098fe3e6331416a6dace774117febf)

~When deploying cloud config there are two entry boxes for profiles. If i enter nothing in the first one, no profiles are applied, fair enough. But if I enter 'default' in the first one I get 'at least one instance profile relies on a root disk', which is correct as this is a zfs filesystem, see screenshot~
![image](https://user-images.githubusercontent.com/3426040/121339777-2103d300-c91f-11eb-801c-2afdad6d015e.png)

~Only if I leave the first profile box empty and enter default in the second one it works as expected. This confuses both me and my users immensely ;)~

~When deploying cloud config, a profile is created with a cryptic name like 2tisW82PqXj8 but it never gets deleted once the machine is destroyed, so I end up with bunch of junk profiles with zero usage that I have to later clean up manually.~ When deploying cloud config in the new version (0.14.0-RC1 and up) the `user.user-data` is applied directly to the instance which  prevents the junk profiles. You can now get terminal feedback and ill make a "delete instance" button appear after completion but  that requires some other ground work first.

**Comment by turtle0x1** [comment]
Im not sure how to work around the profile drop downs, its not like a "select" option where there can only be one input as they can choose multiple profiles so im not sure how to handle that case - ill have a think.

Deployments are really old & I never really ended up using them so Ill have to review as there is another issue with them aswell #379 

I have some holiday tomorrow & some of Friday so ill take a look then!

**Comment by aivanise** [comment]
Just to clarify, I'm not talking about the Deployments section at all (although that one has an error on entry too), but about deploying cloud configs, in the 'Cloud Config' section.

**Comment by Simon-L** [comment]
There are a few other things that could be mentioned here, I suggest to keep these referenced in this issue?
- I'm surprised I haven't seen anyone else around here complain about that: URLs and routing in the webapp!
It would help to have the route shown in the url, for easier history browsing, for better back/forward functionality and overall ease of use in my opinion. So the images section would be `https://example.com/#images`, container `cont` dashboard would be `https://example.com/#dashboard/cont`
- Bug in the dashboard when clicking a vm _first_ in the sidebar, it doesn't update the view. Workaround: click on a container first, the view shows the stats, then click a vm, the view is updated to show the vm.

**Comment by turtle0x1** [comment]
@aivanise 


>When deploying cloud config there are two entry boxes for profiles. If i enter nothing in the first one, no profiles are applied, fair enough. But if I enter 'default' in the first one I get 'at least one instance profile relies on a root disk', which is correct as this is a zfs filesystem
> [screenshot]
> Only if I leave the first profile box empty and enter default in the second one it works as expected. This confuses both me and my users immensely ;)

` Profile Name (Optional)` is the name given to the profile that contains the `cloud-config` as `user.user-data` whereas `additional profiles` is existing profiles on the selected host (select the profiles with a root disk & network, the `cloud-config` profile has neither a network or root disk for the instance) .

**Comment by turtle0x1** [comment]
@aivanise, @Simon-L

I have fixed the bugs in this list that I can duplicate and fixed the other UI/UX problems.

If you have more feedback please open a new issue.

Thanks for your input :smile:
