### ISSUE TITLE
Toggle user admin status

### ISSUE THREAD

**Issue by aivanise** [turtle0x1/LxdMosaic#394]
I don't see an option to delete a user? Make user an admin?

Also, If users are synced from LDAP, do users later deleted from LDAP also get deleted from LxdMosaic user database?

**Comment by turtle0x1** [comment]
Making a user an admin can go in but it should be used with care as it gives all access to hosts & settings.

Deleting users isn't on the horizon as it will either A) have to wipe the audit logs B) update all the audit logs to a "fake" user id that will have to be defined somewhere.

**Comment by abelgomez** [comment]
Dumb question (I don't want to test it in my current setup if you're saying that users can't be deleted 🙂): can users be disabled? at the very least, I think that should be implemented (e.g., in the case of someone leaving the organization).

**Comment by turtle0x1** [comment]
No but ill add disabling login

I know LDAP with AD attributes supports a user disabled field / mechanism which could be used to block LDAP users (not sure about standard LDAP though) & a custom column would have to go in for users in our database.
