### ISSUE TITLE
Underlying System Access

### ISSUE THREAD

**Issue by thePinochleKid** [turtle0x1/LxdMosaic#397]
Hi,

Your software is amazing and just when I have had problems, things get fixed.  One issue that I see that would be really nice is if you could provide (if the API supports it) a way to drop onto a console for the underlying server.  It may not be possible but would be really helpful, especially when you need to make a quick change to the underlying server and you could just do that from the web interface cli instead of having to get the server info, ssh in, etc.

Thanks!
~tPK

**Comment by turtle0x1** [comment]
Hey, im glad your enjoying it!

Unfortunately we can't easily as LXD doesn't expose an API to-do it, so it would require either additional software on the host or LXDMosaic acting as an SSH proxy.

There would be other advantages like being able to-do `zfs send` based backups but quite a large time requirement and has strong security implications.
