### ISSUE TITLE
Image Consistency Between Hosts

### ISSUE THREAD

**Issue by thePinochleKid** [turtle0x1/LxdMosaic#398]
Turtle0x1,

One thing that is cumbersome on the LXD side is when you have multiple stand alone hosts and you want to have the same image at both hosts (see picture below).  In my case, each of those have a different version, which can be a bit cumbersome and can lead to one host trying to pull an image from another when creating new containers.

![image](https://user-images.githubusercontent.com/51836458/122305099-ea542c80-cecb-11eb-804f-47323a72be43.png)

Therefore, is it possible to list only the images that are available to the current host (user configurable) or would it be possible to somehow show the difference between a local (to the machine) and remote (to the machine) image so that you can pick the one you intend if you show all of the "known" hosts.

Thanks!
~tPK

**Comment by thePinochleKid** [comment]
Or, alternatively would it be possible to make sure that they sync up so that picking the correct OS (in this case debian) would already have the newest one queued up.
~tPK

**Comment by turtle0x1** [comment]
Hey, sorry for the very long delay in a response I think the following fixes (a7667d2eac02de49bad3d328fbf9bd15a5c4b14f 7ecea9f442718ae3b7063e783197cf0a3b6a7229) will address your issue

![images](https://user-images.githubusercontent.com/12494629/140793843-2f487527-4d58-4bd0-9d09-0a2062a69900.png)

If you still use this and feel it doesn't fix your issue please re-open :smile:
