### ISSUE TITLE
Unable to delete User

### ISSUE THREAD

**Issue by nikhilreddie** [turtle0x1/LxdMosaic#399]
There is no option to delete User

**Comment by turtle0x1** [comment]
I want to-do a release tonight & this is more complicated than first appears due to audit constraints & poor forgein keys. 

Moving to 0.15.0.

**Comment by turtle0x1** [comment]
Going to work on this now, what i'm going todo is;

 - Add some columns like "User_Deleted", "User_Deleted_Date", "User_Deleted_By"
 - Preserve ldap id (to prevent accidental re-import)
 - Rename user "Deleted User"
 - Optional tick box to drop user audit logs
 - Optional tick box to drop user backup schedules

This should have the desired impact.
