### ISSUE TITLE
I can't login by admin

### ISSUE THREAD

**Issue by Talor12** [turtle0x1/LxdMosaic#411]
I have install latest version lxdmosaic. Now I can't login by admin.

mysql> use LXD_Manager;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> update `Users` set `User_Password` = NULL where User_ID = 1;
ERROR 1048 (23000): Column 'User_Password' cannot be null
mysql> update `Users` set`User_Password` = '' where User_ID = 1;
Query OK, 1 row affected (0.07 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> \q

I am trying by set blank password.

![image](https://user-images.githubusercontent.com/86604736/123632675-0647be80-d83a-11eb-8753-a0690d87768a.png)

**Comment by turtle0x1** [comment]
You cant have a blank password, that's not allowed!

**Comment by Talor12** [comment]
mysql> use LXD_Manager;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> update `Users` set`User_Password` = 'admin' where User_ID = 1;
Query OK, 1 row affected (0.05 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> \q
Bye
  same now

**Comment by turtle0x1** [comment]
Im so confused as to whats going on here. 

First set the password back to blank.

```
update Users set User_Password = '' where User_ID = 1
```

And then run first run following the instructions on screen.

The error in the first screen is saying that you need to enter a new admin password on the right hand side!

**Comment by Talor12** [comment]
1st
mysql> use LXD_Manager;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> update Users set User_Password = '' where User_ID = 1;
Query OK, 1 row affected (0.30 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> \q

![image](https://user-images.githubusercontent.com/86604736/123634615-7b1bf800-d83c-11eb-9376-73f1d4cb3b9a.png)

when password set  blank it shows give admin password

**Comment by turtle0x1** [comment]
Yep see the highlighted input on the right hand side -  you need to enter the admin password there.

**Comment by Talor12** [comment]
![image](https://user-images.githubusercontent.com/86604736/123635032-f7164000-d83c-11eb-855a-278a0107610c.png)
 
It gives this output but i have returned back then it show the GUI. Is it ok?

**Comment by turtle0x1** [comment]
No idea how you have ended up at the url `/n` path. If it said it setup successfully try going back to your IP address and see if it loads successfully! 

If not is it possible to re-install from scratch? Got in abit of a mess here and im not sure whats going on!

**Comment by Talor12** [comment]
No web loaded successfully. I have another issue about ur daily backup script. If i run the script manually it works fine but when i have set it by crontab the script doesn't work, could u help?

**Comment by turtle0x1** [comment]
Id prefer to get you pivoted over to LXDMosaic as that does what the script does, but I guess i could take a look.

As others have said it does seem that the cron user can't see the LXC binary, try changing the script where it says `lxc` to `/snap/bin/lxc` (assuming your using the snap version) and see if that works?

**Comment by Talor12** [comment]
my file permission
-rwxr-xr-x 1 root root 726 Mar 29 12:14 daily.sh

crontab -e
38 09 * * * /home/daily.sh

It shows in log file “/home/daily.sh: line 9: lxc: command not found”


Here is the script

root@NTDACLXDP02:/home# cat daily.sh
#!/usr/bin/env bash
#set -ex

exec >> /var/log/backup.log
exec 2>&1


BACKUP_DIR=/mnt/Image
HOSTS=($(lxc list -c n --format csv))

for HOST in "${HOSTS[@]}"
do
  # Check if the backup key is set
  backupKeySet=$(lxc config get ${HOST} user.daily-backup)
  # Returned empty so it doesn't need to be backed up
  if [ -z "${backupKeySet}" ]; then
    echo "skipping ${HOST}"
    continue
  fi

  echo "backing up ${HOST} ..."
  # Add your backup code here
BACKUP_NAME=${HOST}-$(date +"%Y-%m-%d_%H-%M-%S")
lxc snapshot ${HOST} auto-backup
lxc publish ${HOST}/auto-backup --alias ${BACKUP_NAME}
lxc image export ${BACKUP_NAME} ${BACKUP_DIR}/${BACKUP_NAME}.tar.gz
lxc image delete ${BACKUP_NAME}
lxc delete ${HOST}/auto-backup
done

**Comment by Talor12** [comment]
@turtle0x1 any idea?

**Comment by turtle0x1** [comment]
As stgraber said on the forum try changing `lxc` to `/snap/bin/lxc` E.G

```
#!/usr/bin/env bash
#set -ex

exec >> /var/log/backup.log
exec 2>&1


BACKUP_DIR=/mnt/Image
HOSTS=($(/snap/bin/lxc list -c n --format csv))

for HOST in "${HOSTS[@]}"
do
  # Check if the backup key is set
  backupKeySet=$(/snap/bin/lxc config get ${HOST} user.daily-backup)
  # Returned empty so it doesn't need to be backed up
  if [ -z "${backupKeySet}" ]; then
    echo "skipping ${HOST}"
    continue
  fi

  echo "backing up ${HOST} ..."
  # Add your backup code here
BACKUP_NAME=${HOST}-$(date +"%Y-%m-%d_%H-%M-%S")
/snap/bin/lxc snapshot ${HOST} auto-backup
/snap/bin/lxc publish ${HOST}/auto-backup --alias ${BACKUP_NAME}
/snap/bin/lxc image export ${BACKUP_NAME} ${BACKUP_DIR}/${BACKUP_NAME}.tar.gz
/snap/bin/lxc image delete ${BACKUP_NAME}
/snap/bin/lxc delete ${HOST}/auto-backup
done
```

**Comment by turtle0x1** [comment]
@Talor12 going to close this as you have opended a new thread on the forum & we have fixed the LXDMosaic issue.
