### ISSUE TITLE
Spice VGA not working

### ISSUE THREAD

**Issue by Wolfo-Gaming** [turtle0x1/LxdMosaic#426]
**Describe the bug**
When connecting to VM via spice i get a black screen and if i look into the web console i can see that it says connection refused. Other parts of lxdmosaic are working fine.

**To Reproduce**
1. Go to your VM
2. Click on Terminal
3. click on open in new window
4. See black screen and error in web console

**Expected behavior**
A console that is able to be used

**Screenshots**
https://gyazo.com/2e7fa75da790da2ccb7419dcc95a4c6f

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by turtle0x1** [comment]
What OS is in the VM? Does it work with other OS's?

**Comment by Wolfo-Gaming** [comment]
The VM is running windows 10, i can check if it does the same on other oses

**Comment by turtle0x1** [comment]
Hmm, I haven't tried windows 10 personally - maybe ill have to it a shot later; for example see working ubuntu screenshot!

![ubuntu](https://user-images.githubusercontent.com/12494629/130437613-dd17c88a-739f-42c1-91a4-411023499467.png)

**Comment by Wolfo-Gaming** [comment]
okay i can confirm that it doesnt work on ubuntu either
is there any way to fix this?

**Comment by turtle0x1** [comment]
You running in snap or a container?

**Comment by Wolfo-Gaming** [comment]
snap

**Comment by turtle0x1** [comment]
Snap is still abit of mystery to me, anything interesting in `journalctl -u snap.lxdmosaic.lxdmosaic-node`?

**Comment by Wolfo-Gaming** [comment]
`aug 23 11:31:30 wolfo-virtual-machine systemd[1]: Started Service for snap application lxdmosaic.lxdmosaic-node.
aug 23 11:34:35 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]: (node:348333) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored i>
aug 23 11:34:35 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]: (Use `node --trace-deprecation ...` to show where the warning was created)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]: /snap/lxdmosaic/132/lxdmosaicNode/node/VgaTerminals.js:60
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:                   this.instanceSockets[hostId][project][instance][userId].controlSocket.close()
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:                                                                           ^
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]: TypeError: Cannot read property 'controlSocket' of undefined
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at WebSocket.<anonymous> (/snap/lxdmosaic/132/lxdmosaicNode/node/VgaTerminals.js:60:75)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at WebSocket.emit (events.js:326:22)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at WebSocket.emitClose (/snap/lxdmosaic/132/lxdmosaicNode/node_modules/express-ws/node_modules/ws/lib/websocket.js:172:10)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at TLSSocket.socketOnClose (/snap/lxdmosaic/132/lxdmosaicNode/node_modules/express-ws/node_modules/ws/lib/websocket.js:781:15)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at TLSSocket.emit (events.js:326:22)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at net.js:673:12
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at Socket.done (_tls_wrap.js:564:7)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at Object.onceWrapper (events.js:421:26)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at Socket.emit (events.js:314:20)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at TCP.<anonymous> (net.js:673:12)
aug 23 11:40:27 wolfo-virtual-machine systemd[1]: snap.lxdmosaic.lxdmosaic-node.service: Main process exited, code=exited, status=1/FAILURE
aug 23 11:40:27 wolfo-virtual-machine systemd[1]: snap.lxdmosaic.lxdmosaic-node.service: Failed with result 'exit-code'.
aug 23 11:40:27 wolfo-virtual-machine systemd[1]: snap.lxdmosaic.lxdmosaic-node.service: Scheduled restart job, restart counter is at 1.
aug 23 11:40:27 wolfo-virtual-machine systemd[1]: Stopped Service for snap application lxdmosaic.lxdmosaic-node.`

**Comment by Wolfo-Gaming** [comment]
```aug 23 11:31:30 wolfo-virtual-machine systemd[1]: Started Service for snap application lxdmosaic.lxdmosaic-node.
aug 23 11:34:35 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]: (node:348333) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored i>
aug 23 11:34:35 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]: (Use `node --trace-deprecation ...` to show where the warning was created)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]: /snap/lxdmosaic/132/lxdmosaicNode/node/VgaTerminals.js:60
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:                   this.instanceSockets[hostId][project][instance][userId].controlSocket.close()
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:                                                                           ^
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]: TypeError: Cannot read property 'controlSocket' of undefined
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at WebSocket.<anonymous> (/snap/lxdmosaic/132/lxdmosaicNode/node/VgaTerminals.js:60:75)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at WebSocket.emit (events.js:326:22)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at WebSocket.emitClose (/snap/lxdmosaic/132/lxdmosaicNode/node_modules/express-ws/node_modules/ws/lib/websocket.js:172:10)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at TLSSocket.socketOnClose (/snap/lxdmosaic/132/lxdmosaicNode/node_modules/express-ws/node_modules/ws/lib/websocket.js:781:15)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at TLSSocket.emit (events.js:326:22)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at net.js:673:12
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at Socket.done (_tls_wrap.js:564:7)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at Object.onceWrapper (events.js:421:26)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at Socket.emit (events.js:314:20)
aug 23 11:40:27 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[348333]:     at TCP.<anonymous> (net.js:673:12)
aug 23 11:40:27 wolfo-virtual-machine systemd[1]: snap.lxdmosaic.lxdmosaic-node.service: Main process exited, code=exited, status=1/FAILURE
aug 23 11:40:27 wolfo-virtual-machine systemd[1]: snap.lxdmosaic.lxdmosaic-node.service: Failed with result 'exit-code'.
aug 23 11:40:27 wolfo-virtual-machine systemd[1]: snap.lxdmosaic.lxdmosaic-node.service: Scheduled restart job, restart counter is at 1.
aug 23 11:40:27 wolfo-virtual-machine systemd[1]: Stopped Service for snap application lxdmosaic.lxdmosaic-node.```

**Comment by turtle0x1** [comment]
Okay I can confirm the `controlSocket` issue. 

Is the node service currently down? `systemctl status snap.lxdmosaic.lxdmosaic-node`

Does running `systemctl restart snap.lxdmosaic.lxdmosaic-node` bring it back? And fix the issue?

**Comment by Wolfo-Gaming** [comment]
```● snap.lxdmosaic.lxdmosaic-node.service - Service for snap application lxdmosaic.lxdmosaic-node
     Loaded: loaded (/etc/systemd/system/snap.lxdmosaic.lxdmosaic-node.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-08-23 13:20:28 CEST; 10min ago
   Main PID: 401734 (node)
      Tasks: 11 (limit: 37555)
     Memory: 25.8M
     CGroup: /system.slice/snap.lxdmosaic.lxdmosaic-node.service
             └─401734 /snap/lxdmosaic/132/bin/node /snap/lxdmosaic/132/lxdmosaicNode/node/events.js

aug 23 13:20:28 wolfo-virtual-machine systemd[1]: Stopped Service for snap application lxdmosaic.lxdmosaic-node.
aug 23 13:20:28 wolfo-virtual-machine systemd[1]: Started Service for snap application lxdmosaic.lxdmosaic-node.
aug 23 13:20:32 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[401734]: (node:401734) [DEP0123] DeprecationWarning: Setting the TLS ServerName to an IP address is not permitted by RFC 6066. This will be ignored i>
aug 23 13:20:32 wolfo-virtual-machine lxdmosaic.lxdmosaic-node[401734]: (Use `node --trace-deprecation ...` to show where the warning was created)``` it seems to be still running

**Comment by Wolfo-Gaming** [comment]
Okay i got a vm where the screen seems to be working, but the input doesnt?

**Comment by turtle0x1** [comment]
Hmm odd,

The inputs not perfect but it did appear to work on chrome, i'm at work so I cant investigate to much, is this on the windows VM?

**Comment by Wolfo-Gaming** [comment]
no, its on another ubuntu vm

**Comment by turtle0x1** [comment]
Does it have enough memory? I found 2GB VM's were very slow.

It may have even crashed again on the `controlSocket` issue and just be frozen, as I said ill take a look later :smile:

**Comment by Wolfo-Gaming** [comment]
It does have enough memory, i guess ill just wait until you have taken a look at it :)

**Comment by Wolfo-Gaming** [comment]
Update on this, Me being me remade your vga code. i dont know exactly what i did diffrent to you but mine works fine with the input. my guess is that something is not going right in your code.

**Comment by turtle0x1** [comment]
Go re-write the thing yourself then  :smile:

**Comment by Wolfo-Gaming** [comment]
> Go re-write the thing yourself then 😄

I did https://github.com/Hye-Ararat/Ararat

**Comment by turtle0x1** [comment]
Great, looks like you have alot of duplicate work ahead of you because you couldn't be bothered to fix an issue you were having   :smile:
