### ISSUE TITLE
non admin users should not be able to create new projects

### ISSUE THREAD

**Issue by aivanise** [turtle0x1/LxdMosaic#429]
non admin users should not be able to create new project, as they will not have access to it anyway

**Comment by turtle0x1** [comment]
This is done but be aware master branch is "unstable" at the current time as im upgrading to Boostrap 5  & making UI / UX improvements.

Cherry pick this if you need it quick.

**Comment by aivanise** [comment]
no worries, thank you. This is not causing real harm, only a clutter of empty projects.
