### ISSUE TITLE
Instance_Metric_Values db table automatic trimming

### ISSUE THREAD

**Issue by aivanise** [turtle0x1/LxdMosaic#459]
My Instance_Metric_Values table grew in 6 months to 50mio rows and 13 gigs in size and I have less than 70 hosts. I suppose i can trim it with something like delete from Instance_Metric_Values where IMV_Date<now()-interval 30 day?

maybe it is a good idea to have automatic trimming implemented with configurable retention period and a sensible default? something like 60 days?

**Comment by turtle0x1** [comment]
ACK, while you're at it please check your setting for `Project Analytics History` in the admin settings!

**Comment by aivanise** [comment]
i don't see that setting, is this something new on 0.14? Still running 0.13.0.

**Comment by turtle0x1** [comment]
I must of renamed it in 0.14.0, its what drives most of the available graphs for projects data (which play a heavier role in 0.14.0)

If you had 1000's of projects it would also grow very quickly like the instances projects table, but `-1 day` is sensible enough!

**Comment by aivanise** [comment]
But what does it mean "-1 day". As I've opened the issue, I truncated the table (it was too big for trimming) and there is definitely more than one day in there. 

mysql> select min(IMV_Date) from Instance_Metric_Values;
+---------------------+
| min(IMV_Date)       |
+---------------------+
| 2021-12-10 06:54:07 |
+---------------------+
1 row in set (0.00 sec)

mysql> select max(IMV_Date) from Instance_Metric_Values;
+---------------------+
| max(IMV_Date)       |
+---------------------+
| 2021-12-12 14:32:15 |
+---------------------+
1 row in set (0.00 sec)

mysql>

**Comment by turtle0x1** [comment]
Sorry, I was giving an additional warning about keeping an eye on the table `Project_Analytics` which is controlled by the setting `Project Analytics storage`. The `Project_Analytics` table can fill up as fast as `Instance_Metric_Values` can, if you have lots of hosts & projects.

`-1 day` gets translated to a SQL query like `DELETE FROM Project_Analytics WHERE PA_Date_Created < NOW - (SETTING VALUE)`.

**Comment by aivanise** [comment]
Is that query periodically executed from somewhere? Because if it is, it is obviously not working for me.
