### ISSUE TITLE
Webui renders malformed

### ISSUE THREAD

**Issue by lhorace** [turtle0x1/LxdMosaic#46]
**Describe the bug**
The Webui will render malformed when it has no connection to it's websocket

**To Reproduce**
1. Block port 3000
2. Visit the webui

**Expected behavior**
An appropriate error, otherwise the page is completely broken and unresponsive. 

"Unable to connect to backend"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ElementaryOS (Ubuntu 18.04)
 - Browser: Firefox 66.0.1
 - Version 5.0

**Additional context**
n/a

**Comment by turtle0x1** [comment]
The latest commit should fix this issue, the page will also continue to work without the socket!

![Screenshot from 2019-03-29 18-07-00](https://user-images.githubusercontent.com/12494629/55253556-9e1a6480-524d-11e9-8733-725b154d2d12.png)
