### ISSUE TITLE
List of servers in the dashboard list is not ordered by alias name

### ISSUE THREAD

**Issue by rkelleyrtp** [turtle0x1/LxdMosaic#462]
**Describe the bug**
The list of servers in the Dashboard (left side) is not ordered via alphabetical names.  I added 4 servers via the naming convention (alias) of "Prod Server x" where x is 1, 2, 3, or 4.  Like this:

Prod Server 1
Prod Server 2
Prod Server 3
Prod Server 3

After the servers were added, the order they appear in the list:
Prod Server 4
Prod Server 3
Prod Server 2
Prod Server 1

In another instance, the servers were listed as 
 --> Admin Server 3
 --> Admin Server 1
 --> Admin Server 2

**Comment by turtle0x1** [comment]
This one is do-able ill get in before the next release
