### ISSUE TITLE
turn off binary log in installation script

### ISSUE THREAD

**Issue by aivanise** [turtle0x1/LxdMosaic#465]
Just noticed that mysql server that gets installed by ubuntu using the install script ( https://raw.githubusercontent.com/turtle0x1/LxdMosaic/master/examples/install_with_clone.sh
)  has binary log turned on. No idea why did they go with this on by default as having the binlog on depends on one's individual backup strategy and very few people actually use it with this kind of app, so I guess binlog should be turned off as it just fills the disk unnecessarily.

/etc/mysql/mysql.conf.d/binlog.cnf should contain

[mysqld]
disable_log_bin

**Comment by turtle0x1** [comment]
I've not run into an issue with this before, is it an "at scale" issue? I have no problem disabling it / recommending its disabled but id just like to understand why.

Is it the instance metrics churn causing a load problem?

**Comment by aivanise** [comment]
Its is mostly a disk space issue, by default mysql keeps those logs for 30 days and in my case I have ended up with almost 2GB of binary logs, which is a lot, considering that everything else, OS, database, application itself, etc. put together do not take more than 2.5GB.

**Comment by turtle0x1** [comment]
Thanks for the feedback, insight, debugging, and fix.

Based on my reading, I'm torn. I see how its kinda useless but I see how it could be useful for audit / tracing purposes.

I'm going to mirror what [LXD does](https://linuxcontainers.org/lxd/docs/master/production-setup/) and document that in prod you may want it disabled.
