### ISSUE TITLE
Deployments not working as user

### ISSUE THREAD

**Issue by iigrc** [turtle0x1/LxdMosaic#466]
When logged in as a user cannot open Deployments.

Loggin as user
Click on Deployments

Error "Trying to access host with no allowed projects /var/www/LxdMosaic/src/classes/Tools/User/GetUserProject.php 42" is shown, and nothing happens.

 - OS: Linux Mint 20.2 Uma
 - Browser: Chrome 96.0.4664.93 (Official Build) (64-bit)
 - Version (lxdmosaic): v0.14.0-rc2

**Comment by turtle0x1** [comment]
Ack, will look tonight
