### ISSUE TITLE
Administrating user settings doesn't open drop down menu

### ISSUE THREAD

**Issue by iigrc** [turtle0x1/LxdMosaic#467]
When administrating users as admin the drop-down menu doesn't work, neither clicking on the users name.

Login as admin

Go to Admin Settings on the top right
Choose Users
Next to each user there is blue drop-down settings menu that does nothing, same as clicking on the users name, the only thing that works on that page is the plus button to add a new user

OS: Linux Mint 20.2 Uma
Browser: Chrome 96.0.4664.93 (Official Build) (64-bit)
Version (lxdmosaic): v0.14.0-rc2

**Comment by turtle0x1** [comment]
Ack, will fix tonight
