### ISSUE TITLE
Node using 100% CPU

### ISSUE THREAD

**Issue by turtle0x1** [turtle0x1/LxdMosaic#470]
Further investigation for me and the 100% cpu from events.js is caused by pm2 continually restarting and this block of code:
```

if(!fs.existsSync(process.env.CERT_PATH)){
    console.log("waiting 10 seconds to see if a certificate gets created");
}

var startDate = new Date();

while (!fs.existsSync(process.env.CERT_PATH)) {
    var seconds = (new Date().getTime() - startDate.getTime()) / 1000;
    if(seconds > 10){
        break;
    }
}

if(!fs.existsSync(process.env.CERT_PATH)){
    console.log("couldn't read certificate file");
    process.exit(1);
}
```

There must be a better async way of doing this?

_Originally posted by @DragonEmbers in https://github.com/turtle0x1/LxdMosaic/issues/213#issuecomment-1033102290_

**Comment by turtle0x1** [comment]
@DragonEmbers thanks for taking the time to report this.

Please can you include what OS & architecture you get this on? Installing from the default script I dont get this issue.

**Comment by DragonEmbers** [comment]
Debian Bullseye amd64 (LXC containerised)

I haven't had the time to track down what's causing the problem just yet but I'll update if/when I do

**Comment by DragonEmbers** [comment]
It would appear that debian doesn't generate the snakeoil certificates by default anymore. Manually generate them by running:

```
sudo make-ssl-cert generate-default-snakeoil
```

**Comment by turtle0x1** [comment]
@DragonEmbers thanks a lot for you investigation, do you think you could open a PR against [this file](https://github.com/turtle0x1/LxdMosaic/blob/master/examples/install_with_clone.sh) with the fix?

**Comment by turtle0x1** [comment]
Fixed in https://github.com/turtle0x1/LxdMosaic/commit/ef1f1576f01075bb9060aa7c0f6e5a7e1629d77e
