### ISSUE TITLE
Short SSL validity of the client certificate

### ISSUE THREAD

**Issue by githubDante** [turtle0x1/LxdMosaic#478]
Currently the client certificate is generated for a period of one year:

https://github.com/turtle0x1/LxdMosaic/blob/57461b3392202a29dfb415eff7a263cc0c6fe68b/src/classes/Tools/Hosts/GenerateCert.php#L82

This lead to problems when the certificate expires, such as: 
 - LXDMosaic cannot communicate with the LXD host anymore
 - the host cannot be deleted if automatic backups are scheduled for any of the containers 

The easiest solution is the certificate to be generated for a longer period (e.g. 5-10 years).

**Comment by aivanise** [comment]
Heh, lxc client by default generates client certs valid for 10 years which horrifies me, I was about to request some functionality from lxd people to have some kind of policy to be able to make the server reject certificates valid for too long and in case they refuse to have a cronjob just deleting all certs with expiry date too far in the future.

I think it would be best to have this as a configurable parameter. It would be also nice to have something more informative as a CN, not 127.0.0.1 as it is now ;)

That being said, what would be the way to handle expired certificates now? Delete and readd all hosts? Something less invasive?  ;)

**Comment by turtle0x1** [comment]
@githubDante welcome :)

I agree with @aivanise on this one and think 365 days is a sane-ish default, the expiry / renewal process needs to be better.

Do you need a one time script to correct the issue or was this spotted in advance? I've got something nearing completion if its a real problem now :smile:  

@aivanise I'll look at changing the CN to LXDMosaic, those particular lines [haven't changed since the first commit to a public repo](https://github.com/turtle0x1/LxdMosaic/commit/4d805b61c880f07519f7617eea961a078d415803) :D

**Comment by githubDante** [comment]
> That being said, what would be the way to handle expired certificates now? Delete and readd all hosts? Something less invasive?

It is possible the client certificate to be replaced with a new one. The certificates are stored in src/sensitiveData/certs/ in the form <LXD host IP address>.{cert,key,combined}.


- #### Create a new client certificate (replace the address with the actual IP address of your LXD host)

```
cd /var/www/LxdMosaic/src/sensitiveData/certs/
openssl req -x509 -newkey rsa:2048 -keyout 192.168.168.1.key -out 192.168.168.1.cert -sha256 -days 1825 -nodes
```
- #### Create the .combined file (this one is actually used by LXDMosaic)
`
cat 192.168.168.1.cert > 192.168.168.1.combined && cat 192.168.168.1.key >> 192.168.168.1.combined
`
- #### JSON data generation
```
cat <<EOF
{"certificate": "`cat 192.168.168.1.cert | sed '/^-----/d' | sed -z 's/\n//g'`",
"name": "LXDMosaic-NewClientCert",
"projects": ["default"],
"restricted": true,
"token": true,
"type": "client",
}
EOF
```
- #### On the LXD host save the generated JSON data to a file (e.g. /tmp/lxc_new_cert.json) and add the new certificate with cURL
```
curl -H 'Content-Type: application/json' -X POST -d @/tmp/lxc_new_cert.json --unix-socket  /var/lib/lxd/unix.socket http:8443/1.0/certificates
```
- #### LXDMosaic will work as before after that

**Comment by turtle0x1** [comment]
@githubDante that's better than my temporary script for sure!

**Comment by turtle0x1** [comment]
Don't forget to reload the node app (it caches the file contents) `pm2 restart all`

**Comment by turtle0x1** [comment]
With #483 closed im closing this, thanks for brining up the problem :smile:
