### ISSUE TITLE
Apache complete hange after attempting to add a server

### ISSUE THREAD

**Issue by lhorace** [turtle0x1/LxdMosaic#48]
**Describe the bug**
Adding a server breaks the ui.

**To Reproduce**
1. Click on Add Server
2. Fill out the form with working configuration
3. Click Add

**Expected behavior**
Server added to the list

**Actual behvaior**
Nothing happens, additionally clicking on ui elements will sometimes fail to render the page correctly. Notwithstanding page will hang on refresh. Only restarting apache2 would clear this state.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ElementaryOS
 - Browser Firefox 66
 - Version 5.0

**Additional context**
n/a

**Comment by lhorace** [comment]
I took the initiative and ran `node /var/www/LxdMosaic/node/events.js` but got nothing. And I was able to reproduce this issue in `Chromium 73.0.3683.75`. Caveat with Chromium though, after awhile, I receive a connection timed out notification. So this might be part enhancement; the form should have some feedback that it's doing something, and cancel whatever it's doing in the background when you exit the form?

**Comment by turtle0x1** [comment]
sorry been out, thats interesting just for sanity is your

 - LXD server running
 - all lxd ports accessable over the network
 -  what did you put in the sever ip field 

Is there any interesting logs in `/var/log/apache2/error.log`?

**Comment by turtle0x1** [comment]
the reason node fails is because after adding the sever code is executed it calls a node endpoint that refreshes all the operation sockets in node

**Comment by lhorace** [comment]
* Yes
* Yes, but not at the time and was a remote LXD instance.
* Hostname

It's very easy to reproduce, add any IP that doesn't route to any host and password, and click add. What's happening in the background is, either the browser or node, is attempting to connect to the LXD instance (TCP SYN). In Firefox it hangs, in Chromium you'll get connection timed out notification though the page is unresponsive. You'll notice that in Wireshark dump.

**Comment by turtle0x1** [comment]
Thanks for your feedback, I have found the problem, I have added a timeout of 2 seconds to the specific request which should through a warning when the host can't be accessed over the network!

**Comment by lhorace** [comment]
the form should have some feedback that it's doing something, and cancel whatever it's doing in the background when you exit the form?

What about this?

**Comment by turtle0x1** [comment]
when a exception gets throw it will bubble up and send a response to the client

ill add a spinning cog to the button while the request is running but i wont cancel the request when the user hides the modal 

the latest commit drasticly improves the situation i emplore you to try it a see it meets your request (baring in mind i wont cancel the request if the modal is closed)

**Comment by lhorace** [comment]
ill add a spinning cog to the button

Thanks, that would be useful

    i wont cancel the request when the user hides the modal

Wouldn't a better alternative, prevent the modal from hiding while it's doing something?

    the latest commit drasticly improves the situation

Will do! Though I taking a break from computer for now.

Cheers!

**Comment by lhorace** [comment]
Yeah, LGTM, though like me, people might misleadingly think nothing is going on, occidentally hitting Add button more than once. Exiting out and potentially get caught off guard. 

Cheers
