### ISSUE TITLE
Update container stats and state

### ISSUE THREAD

**Issue by lhorace** [turtle0x1/LxdMosaic#50]
**Is your feature request related to a problem? Please describe.**
Seems to me, navigating away and returning to container dashboard is necessary to pull currents stats. And, it would be nice the container state is not lost, see image below:

![Screenshot from 2019-03-31 16 19 52](https://user-images.githubusercontent.com/12678456/55294507-fd54b200-53d0-11e9-94d7-39583158cc10.png)

**Describe the solution you'd like**
Container stats are updated in realtime. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

Cheers

**Comment by turtle0x1** [comment]
that select box doesnt show the current state it changes it, the container title shows its state

which stats are you talking about ? memory usage ?

**Comment by lhorace** [comment]
that select box doesnt show the current state it changes it, the container title shows its state

Nvm.

    the container title shows its state

This is the curial part, it doesn't. Change the container state, the only feedback you get is in **operations** column that it's starting a continaer. The title remains the same which leaves the impression the container failed to start.

    which stats are you talking about ? memory usage ?

Yes real time stats, but honesty after some thinking, those a luxury items I can do without.

**Comment by turtle0x1** [comment]
thats weird the icon should update after the op completes in the title ill take a look 

lxd offers no websocket for real time container stats so id have to fire ajax requests every x seconds to update, i may open a request to lxd team
 and see what the response is !

**Comment by lhorace** [comment]
thats weird the icon should update after the op completes in the title ill take a look

I'll test again and make sure and let you know tomorrow. It didn't update here, perhaps I didn't wait long enough. Dunno.

Cheers.

**Comment by lhorace** [comment]
Hello,

Back with my test and it appears to work as expected. Must have been a fluke at the time and perhaps misjudge due to my experience with the other LXD WebUI.

**Comment by turtle0x1** [comment]
Im going to close this as there isn't much I can do because there is no real time socket for container information and it does update when you change state!
