### ISSUE TITLE
fatal error in snap lxdmosaic.lxdmosaic-cron

### ISSUE THREAD

**Issue by mtermer** [turtle0x1/LxdMosaic#502]
Hello,

**lxdmosaic.lxdmosaic-cron** has issue in snap:

Fatal error: Class Symfony\Component\DependencyInjection\Exception\ExceptionInterface cannot implement previously implemented interface Throwable in /snap/lxdmosaic/221/htdocs/vendor/symfony/dependency-injection/Exception/ExceptionInterface.php on line 22

**To Reproduce**

snap run lxdmosaic.lxdmosaic-cron

**Expected behavior**
It should run cron

**Desktop (please complete the following information):**
 - OS: Almalinux 8.5
 - snapd: 2.55.3-1.el8
 - Version: "0+git.e96c68c 2022-05-15"

**Comment by turtle0x1** [comment]
Ack, will investigate today

**Comment by turtle0x1** [comment]
Pretty sure its PHP 7.3 causing the error, trying to rebuild SNAP locally to PHP 7.4  but seem to be arguing with LXD / SNAP today.

Will keep issues updated as I progress

**Comment by turtle0x1** [comment]
Got the snap building successfully locally but doesn't seem to produce a `.snap` file, if I dont get a response [on the forum](https://forum.snapcraft.io/t/snapcraft-build-destructive-mode-doesnt-output-snap/30179) as to why ill push to edge. There is a few users on edge and i'd quite like to test it locally first.

**Comment by mtermer** [comment]
I've updated snap to latest/candidate: 0+git.36168ef 2022-05-24 (222) and it works.
