### ISSUE TITLE
Alias for hosts

### ISSUE THREAD

**Issue by lhorace** [turtle0x1/LxdMosaic#51]
**Is your feature request related to a problem? Please describe.**
Hello o/,

I have two hosts currently:

```
alvmsrv.lhprojects.int
10.0.3.61
```

I sometimes find myself hard of remembering names and it would be convenient if I could set aliases. One more thing, I wish the search feature could be improve a bit, eg keep a listing of most recent terms?

Cheers

**Comment by turtle0x1** [comment]
Alias for hosts is fine ill add that, the search lists your going to need to be more specific

**Comment by lhorace** [comment]
![Screenshot from 2019-04-02 09 22 06](https://user-images.githubusercontent.com/12678456/55405816-dc9f7000-5528-11e9-8c07-e18290ee5a11.png)

Having recent items here (eg, the last 5 searches) would be faster than looking up terms, at least for me. I get disappointed every time when I'm expecting a drop down list instead of a search box.

**Comment by turtle0x1** [comment]
Please run 

```
cd /var/www/LxdMosaic
git pulll 
mysql < sql/host_alias.sql
```

**Comment by lhorace** [comment]
I had a chance to sit down and test this feature and LGTM. Thanks!
