### ISSUE TITLE
Error 500 - Failed to retrieve network informat (truncated...)

### ISSUE THREAD

**Issue by KRobert74** [turtle0x1/LxdMosaic#522]
No detail view to container or vm.

I go to dashboard, expand the server and click on a container.
Then I get the following error:

Server error: `GET https://192.168.41.32:8443/1.0/resources` resulted in a `500 Internal Server Error` response: {"type":"error","status":"","status_code":0,"operation":"","error_code":500,"error":"Failed to retrieve network informat (truncated...) /var/www/LxdMosaic/vendor/php-http/guzzle6-adapter/src/Promise.php 127

<img width="893" alt="Screenshot" src="https://user-images.githubusercontent.com/82312733/173383177-9dcaf7a2-2f95-431e-9cfc-7879631f8e2d.png">

System configuration:

I run LXD Version 5.2 on raspberry pi 4B (arm64).
lxdMosaic v0.14.1

I have the following network configuration:

root@piserver2:~# lxc network list
+---------+----------+---------+------+------+-------------+---------+-------+
|  NAME   |   TYPE   | MANAGED | IPV4 | IPV6 | DESCRIPTION | USED BY | STATE |
+---------+----------+---------+------+------+-------------+---------+-------+
| eth0    | physical | NO      |      |      |             | 6       |       |
+---------+----------+---------+------+------+-------------+---------+-------+
| eth0.1  | vlan     | NO      |      |      |             | 2       |       |
+---------+----------+---------+------+------+-------------+---------+-------+
| eth0.42 | vlan     | NO      |      |      |             | 4       |       |
+---------+----------+---------+------+------+-------------+---------+-------+
| wlan0   | physical | NO      |      |      |             | 0       |       |
+---------+----------+---------+------+------+-------------+---------+-------+

**Comment by KRobert74** [comment]
I tried to find a log file but without success.
Where are error messages stored?

If I could find the script which send the request, I can try to debug.

I can edit files without problems. I have basic programming skills.

I'm connecting with http to the host running lxd.
I'm concern that the problem appears since lxd 5.x. 
Because with lxd 4.x all runs without problems.

**Comment by turtle0x1** [comment]
Sorry in my delay in getting back been buried at work recently.

Its odd because the error is coming from LXD not from LXDMosaic.

If your still around could you run `lxc query /1.0/resources` on your PI? See if it produces the same error? I'm not sure it will but interesting none the less (of course I may have been fixed upstream since this was opened)

**Comment by turtle0x1** [comment]
No response in 21 == close, sorry.

Re-open if still a problem :smile:
