### ISSUE TITLE
Snap Setting to change IP address.

### ISSUE THREAD

**Issue by v3ss0n** [turtle0x1/LxdMosaic#527]
**Is your feature request related to a problem? Please describe.**
Currently lxdmosiac binds to 0.0.0.0 by default which is  dangerous
**Describe the solution you'd like**
Any setting to change address would be helpful.

**Describe alternatives you've considered**
Not sure its a good practice to change Ipaddress of httpd.conf inside snap directory.

**Comment by turtle0x1** [comment]
Interestingly someone tried to get this through the nextcloud SNAP (the basis for this SNAP) [here](https://github.com/nextcloud-snap/nextcloud-snap/pull/416) but it never got through.

I guess I could just cherry-pick those changes, im not sure why they didn't accept it.

Quite low priority for me, might take a look this weekend might not - could work around with firewall rules i'm pretty sure!

**Comment by v3ss0n** [comment]
Following best practice would be just start LXDMosiac / ApacheHttpd at localhost
Since this should be fronted via Nginx , with some kind of auth anyways.

**Comment by turtle0x1** [comment]
I some what take your point but what kind of auth would you use? HTTP Basic or something far more complicated?  Is there an auth provider NGINX integrates with that would be of value for you?

Remember LXDMosaic is entirely permission and requires auth for all requests except 1 or 2 routes for some assets on the login page.

Also LXD + LXDMosaic could be installed in a bundled image together and im not sure I would want to put the task of setting up a proxy onto the average user.

**Comment by v3ss0n** [comment]
I am now setting up inside lxd  by running bash file and plan to communicate master lxd tru network , its a better/secure option .
