### ISSUE TITLE
Add the network address to the instances list

### ISSUE THREAD

**Issue by FherStk** [turtle0x1/LxdMosaic#531]
Dear LxdMosaic team,

Could be possible to add the instance's network address to the instances list, next to the instance name, as "lxc list" command does?
![image](https://user-images.githubusercontent.com/324326/186870646-2db25a62-0caf-4d84-951c-9a50e688be8e.png)

Also, I would like to be able to make this page as the default one for my user (the URL does not change, so the overview is loaded by default when using bookmarks).

Thanks a lot in advance.
Fher

**Comment by turtle0x1** [comment]
Yeah, will take a look over the weekend as this isn't to hard :smile:
