### ISSUE TITLE
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Host_Alias' in 'field list'

### ISSUE THREAD

**Issue by khokooli** [turtle0x1/LxdMosaic#54]
when i try to add server i get this error 
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Host_Alias' in 'field list'

**Comment by turtle0x1** [comment]
Please run 

```
cd /var/www/LxdMosaic
git pulll 
mysql < sql/host_alias.sql
```

**Comment by turtle0x1** [comment]
Im going to close this as im pretty sure its an upgrade issue at this point please re-open if not
