### ISSUE TITLE
Shell doesn't work when lxdmosaic is run on a port other than 443 through a tunnel

### ISSUE THREAD

**Issue by BL4Z3-CSGO** [turtle0x1/LxdMosaic#540]
Hello, my setup looks like this:
I have lxdmosaic running on Debian on a local server though a tunnel (frp) set up on a VPS.
The VPS is already running a webserver so I am putting the tunnel on port 444.
Now the issue is that, although everything else seems to work, the shell does not start (this screen:)
![image](https://user-images.githubusercontent.com/58826968/189497332-38acb293-a74f-481b-8f79-ca6c21308ae9.png)
This is because although all other URLs are being generated correctly, the WebSocket URLs seem to miss the :444 to specify the port so the requests just go to my normal webserver.

**Comment by turtle0x1** [comment]
>  This is because although all other URLs are being generated correctly, the WebSocket URLs seem to miss the :444 to specify the port so the requests just go to my normal webserver.

Shouldn't matter, its all proxied by apache and should follow the existing root, but maybe  there is a dodgy URL.

So you installed on Debian and changed the port to 444 in the apache config? Ill try to replicate now-ish...

**Comment by CyborgDE** [comment]
Hello,

I have the same problem with the port.
I try to use the edge channel, but this version will not start the Webserver. I have not found any log with an error ...

What can I do ?

Thank you.
