### ISSUE TITLE
Renew client certificate of host

### ISSUE THREAD

**Issue by 4tnetse** [turtle0x1/LxdMosaic#542]
**Is your feature request related to a problem? Please describe.**
When adding a host a client cert is generated and added to the LXD trust list. This certificate is valid for only 1 year.
When it expired you need to remove the host and add it again. There is no other, user-friendly, way to get a new valid certificate.
But by deleting the host you also lose the user-project access mapping (and the hostid changes).

**Describe the solution you'd like**
Auto-renew the client cert or have a renew client cert button next to the host config box.

**Comment by turtle0x1** [comment]
If the certificate hasn't already expired, you can do that in the admin view already in the latest versions (click the 3 dots then "Renew Certificate").

If it has expired you do need to manually fix it, there are the steps here https://github.com/turtle0x1/LxdMosaic/issues/478#issuecomment-1065976493

I suppose I could add a "Renew with password" but i'm not super keen on doing that at this time.

Thanks for using LXDMosaic for a year :smile:
