### ISSUE TITLE
support for new "Ready" state introduced in lxd 5.5

### ISSUE THREAD

**Issue by aivanise** [turtle0x1/LxdMosaic#547]
since lxd 5.5 there is a new state "Ready", described here: https://discuss.linuxcontainers.org/t/lxd-instance-ready-state/14657

right now lxdmosaic considers containers in READY state as down, which makes them more or less uncontrolable and that is a pain

please handle a ready state to be the same as running, maybe a different icon would be nice too

thank you

**Comment by turtle0x1** [comment]
You're welcome to have a brose through this https://fontawesome.com/v5/search?o=r&m=free to find an icon you think would work, if you find one comment it here and ill update the code :smile:

**Comment by aivanise** [comment]
I was really tempted to suggest dumpster-fire :), but I think play-circle is the best, looks a bit different, but similar enough so that there is no confusion https://fontawesome.com/v5/icons/play-circle?s=solid&f=classic

**Comment by aivanise** [comment]
speaking of icons, while you are there maybe you can replace the generic tux icon for centos boxes (from my other ticket :) with a centos one https://fontawesome.com/v5/icons/centos?s=&f=brands

**Comment by turtle0x1** [comment]
Changed in https://github.com/turtle0x1/LxdMosaic/commit/74d067c7ca9a10eba406f729666e97cf5d9e6e17 :smile:

**Comment by aivanise** [comment]
there hasn't been a release since september and I really need this fix, how safe is it to upgrade to master right now?

**Comment by turtle0x1** [comment]
Take a snapshot / backup then do;

```
# Make sure to read release notes on github for this release.
cd /var/www/LxdMosaic

git fetch

git checkout master

npm i

composer install --no-dev

vendor/bin/phinx migrate -e mysql

# Restart node server - be careful may interupt console sessions
pm2 restart all

#Ubuntu
systemctl restart apache2
```
