### ISSUE TITLE
Issue with assign profile in container

### ISSUE THREAD

**Issue by zyr3x** [turtle0x1/LxdMosaic#548]
**Describe the bug**
Mosiac doesn't add additional profile in already exist container

**To Reproduce**
1. Click on lxd server
2. Click on container
3. Add profile
"Not found. /snap/lxdmosaic/247/htdocs/vendor/dhope0000/lxd/src/HttpClient/Plugin/LxdExceptionThower.php 47"
state:"error"

**Expected behavior**
Profile added secussefull

**Screenshots**
![image](https://user-images.githubusercontent.com/392449/197383764-314786ed-81ae-4cdc-bde1-0ed1c59b80ac.png)

Lxdmosiac snap 247, 256
LXD 5.6

**Comment by turtle0x1** [comment]
This could be this https://github.com/lxc/lxd/issues/11083 upstream bug or problem with LXDMosaic.

Is the profile in a project called `Shopware5` or is the project name something else?

**Comment by zyr3x** [comment]
Hi @turtle0x1 . Profile name doesn’t matter. It happened with any profiles after creating container. Profiles is impossible to add

**Comment by zyr3x** [comment]
All profiles show like on screen. Profile_name?project=profile_name

**Comment by turtle0x1** [comment]
So then I think its todo with the above linked issue, lets wait for them to add the upstream fix I guess.

**Comment by zyr3x** [comment]
looks ok now
