### ISSUE TITLE
Unavailable to deploy cloud config on servers

### ISSUE THREAD

**Issue by zyr3x** [turtle0x1/LxdMosaic#549]
**Describe the bug**
The server is impossible to select for deploy config

**To Reproduce**
1. Go to 'Cloud Config'
2. Select already done config
3. Click to deploy

**Screenshots**
![image](https://user-images.githubusercontent.com/392449/201016486-65004e88-1125-4482-b564-23c9ed4a9797.png)

**Comment by turtle0x1** [comment]
Odd, this in a clustered setup?
