### ISSUE TITLE
SNAP: Self signed certs aren't linked to the live folder

### ISSUE THREAD

**Issue by k9943004** [turtle0x1/LxdMosaic#554]
**Describe the bug**
Version --stable has no problem, but version --edge does not listen. (444)

**To Reproduce**
# snap refresh lxdmosaic --stable
# snap refresh lxdmosaic --edge
444 port Listen fail

**Expected behavior**

`
[root@LXD-server ~]# snap refresh lxdmosaic --stable
snap "lxdmosaic" has no updates available
[root@LXD-server ~]# ss -antp
State        Recv-Q    Send-Q                Local Address:Port                   Peer Address:Port     Process
LISTEN       0         128                         0.0.0.0:81                          0.0.0.0:*         users:(("httpd",pid=27196,fd=3),("httpd",pid=27101,fd=3),("httpd",pid=27100,fd=3),("httpd",pid=27099,fd=3),("httpd",pid=27098,fd=3))
LISTEN       0         128                         0.0.0.0:22                          0.0.0.0:*         users:(("sshd",pid=1065,fd=5))
LISTEN       0         128                         0.0.0.0:444                         0.0.0.0:*         users:(("httpd",pid=27196,fd=4),("httpd",pid=27101,fd=4),("httpd",pid=27100,fd=4),("httpd",pid=27099,fd=4),("httpd",pid=27098,fd=4))
ESTAB        0         36                    192.168.0.242:22                    192.168.0.148:11693     users:(("sshd",pid=1782,fd=5),("sshd",pid=1767,fd=5)) 
LISTEN       0         128                            [::]:22                             [::]:*         users:(("sshd",pid=1065,fd=7))
LISTEN       0         128                               *:3000                              *:*         users:(("node",pid=26829,fd=18))
LISTEN       0         128                               *:8443                              *:*         users:(("lxd",pid=3245,fd=8))
ESTAB        0         0            [::ffff:192.168.0.242]:8443         [::ffff:192.168.0.148]:35855     users:(("lxd",pid=3245,fd=25))

[root@LXD-server ~]# snap refresh lxdmosaic --edge
lxdmosaic (edge) 0+git.341a5f80 from Daniel Hope (turtle0x1) refreshed
[root@LXD-server ~]# ss -antp
State        Recv-Q    Send-Q                Local Address:Port                   Peer Address:Port     Process
LISTEN       0         128                         0.0.0.0:22                          0.0.0.0:*         users:(("sshd",pid=1065,fd=5))
ESTAB        0         36                    192.168.0.242:22                    192.168.0.148:11693     users:(("sshd",pid=1782,fd=5),("sshd",pid=1767,fd=5))
ESTAB        0         0                     192.168.0.242:46246                185.125.188.59:443       users:(("snapd",pid=25600,fd=16))
TIME-WAIT    0         0                     192.168.0.242:444                   192.168.0.148:36075    
TIME-WAIT    0         0                     192.168.0.242:444                   192.168.0.148:36071    
TIME-WAIT    0         0                     192.168.0.242:444                   192.168.0.148:36073    
LISTEN       0         128                            [::]:22                             [::]:*         users:(("sshd",pid=1065,fd=7))
LISTEN       0         128                               *:3000                              *:*         users:(("node",pid=27540,fd=18))
LISTEN       0         128                               *:8443                              *:*         users:(("lxd",pid=3245,fd=8))
ESTAB        0         0            [::ffff:192.168.0.242]:8443         [::ffff:192.168.0.148]:35855     users:(("lxd",pid=3245,fd=25))

`

`[root@LXD-server ~]# snap refresh lxdmosaic --edge
lxdmosaic (edge) 0+git.341a5f80 from Daniel Hope (turtle0x1) refreshed
[root@LXD-server ~]# snap set lxdmosaic ports.http=81 ports.https=444
[root@LXD-server ~]# ss -antp
State     Recv-Q    Send-Q                  Local Address:Port                    Peer Address:Port     Process
LISTEN    0         128                           0.0.0.0:22                           0.0.0.0:*         users:(("sshd",pid=1065,fd=5))
ESTAB     0         36                      192.168.0.242:22                     192.168.0.148:11693     users:(("sshd",pid=1782,fd=5),("sshd",pid=1767,fd=5))
ESTAB     0         0                       192.168.0.242:45794                 185.125.188.54:443       users:(("snapd",pid=25600,fd=16))
LISTEN    0         128                              [::]:22                              [::]:*         users:(("sshd",pid=1065,fd=7))
LISTEN    0         128                                 *:3000                               *:*         users:(("node",pid=29324,fd=18))
LISTEN    0         128                                 *:8443                               *:*         users:(("lxd",pid=3245,fd=8))
ESTAB     0         0              [::ffff:192.168.0.242]:8443          [::ffff:192.168.0.148]:35855     users:(("lxd",pid=3245,fd=25))

[root@LXD-server ~]# snap info lxdmosaic
name:      lxdmosaic
summary:   A web interface to manage multiple instances of LXD
publisher: Daniel Hope (turtle0x1)
store-url: https://snapcraft.io/lxdmosaic
license:   unset
description: |
  Features
    - Terminal Access
    - User control
    - Proxy device management
    - Container management
    - Virtual machine management
    - Auto connects to LXD SNAP socket
commands:
  - lxdmosaic.disable-https
  - lxdmosaic.enable-https
services:
  lxdmosaic.apache:         simple, enabled, **inactive**
  lxdmosaic.lxdmosaic-cron: oneshot, enabled, inactive
  lxdmosaic.lxdmosaic-node: simple, enabled, active
  lxdmosaic.php-fpm:        simple, enabled, active
snap-id:      OhvWa07xDBjF78L0rwdPYwDOr7jsulZM
tracking:     latest/edge
refresh-date: today at 18:55 KST
channels:
  latest/stable:    0+git.c6f53f3f 2022-09-06 (247) 113MB -
  latest/candidate: 0+git.c6f53f3f 2022-09-06 (247) 113MB -
  latest/beta:      ↑
  latest/edge:      0+git.341a5f80 2022-12-06 (258) 113MB -
installed:          0+git.341a5f80            (258) 113MB -
[root@LXD-server ~]# snap refresh lxdmosaic --stable`

`
[root@LXD-server ~]# systemctl restart snap.lxdmosaic.apache
[root@LXD-server ~]# sudo snap logs lxdmosaic
2022-12-06T19:22:39+09:00 lxdmosaic.apache[50167]: AH00526: Syntax error on line 17 of /snap/lxdmosaic/258/conf/ssl.conf:
2022-12-06T19:22:39+09:00 lxdmosaic.apache[50167]: SSLCertificateFile: file '/var/snap/lxdmosaic/258/certs/live/cert.pem' does not exist or is empty
2022-12-06T19:22:39+09:00 systemd[1]: snap.lxdmosaic.apache.service: Main process exited, code=exited, status=1/FAILURE
2022-12-06T19:22:39+09:00 systemd[1]: snap.lxdmosaic.apache.service: Failed with result 'exit-code'.
2022-12-06T19:22:39+09:00 systemd[1]: snap.lxdmosaic.apache.service: Service RestartSec=100ms expired, scheduling restart.
2022-12-06T19:22:39+09:00 systemd[1]: snap.lxdmosaic.apache.service: Scheduled restart job, restart counter is at 5.
2022-12-06T19:22:39+09:00 systemd[1]: Stopped Service for snap application lxdmosaic.apache.
2022-12-06T19:22:39+09:00 systemd[1]: snap.lxdmosaic.apache.service: Start request repeated too quickly.
2022-12-06T19:22:39+09:00 systemd[1]: snap.lxdmosaic.apache.service: Failed with result 'exit-code'.
2022-12-06T19:22:39+09:00 systemd[1]: Failed to start Service for snap application lxdmosaic.apache.

`

**Comment by k9943004** [comment]
I did it by editing the hosts file.

[root@LXD-server lxdmosaic]# cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 LXD-server
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
[root@LXD-server lxdmosaic]#

**Comment by turtle0x1** [comment]
Nice fix but it needs to be addressed properly for new installs, re-opening.

**Comment by k9943004** [comment]
> Nice fix but it needs to be addressed properly for new installs, re-opening.

When installing from scratch, an error occurs in apache even if you install with option "--edge".

**Comment by turtle0x1** [comment]
Please leave this open, its an issue that needs to be addressed.

**Comment by turtle0x1** [comment]
Fixed here 5f52c12d0f4e342962e884fb0c5dafb74f90210e
