### ISSUE TITLE
"create instance from snapshot"  still loading

### ISSUE THREAD

**Issue by k9943004** [turtle0x1/LxdMosaic#555]
"create instance from snapshot" still loading

**To Reproduce**

0. I ran the below command beforehand.
#snap set lxd criu.enable=true
#systemctl restart snap.lxd.daemon

1. Current installed version : --edge 

2. create vm or conatiner
3. snapshot create
4. "create instance from snapshot" still loading
5. New Name [new name insert] -> RESTORING.....
6. fail

**Screenshots**
![image](https://user-images.githubusercontent.com/5757446/206393900-ee66b78a-b579-4bf6-afbe-f64f6976552c.png)

**Additional context**
Whether it's VM or Container, it doesn't behave the same.

**Comment by k9943004** [comment]
Please review the issue.

This is my system information.
[root@LXD-server ~]# cat /etc/redhat-release
Rocky Linux release 8.7 (Green Obsidian)
[root@LXD-server ~]# uname -a
Linux LXD-server 4.18.0-425.3.1.el8.x86_64 #1 SMP Wed Nov 9 20:13:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@LXD-server ~]#

**Comment by turtle0x1** [comment]
I am very happy to help but please remember this is an open source project with no funding / sponsorship, things are fixed "as and when".

If you need something fixed on your timeline please consider reaching out over email and we can reach some arrangement.
