### ISSUE TITLE
WebUI breaks if a server goes offline

### ISSUE THREAD

**Issue by lhorace** [turtle0x1/LxdMosaic#56]
**Describe the bug**
I'm having a problem where the WebUI would randomly end up in inconsistent state. The dashboard section would either show a combination of other sections or all sections on the same page. The problem is compounded because there's no indication why the page is failing to properly render, though https://github.com/turtle0x1/LxdMosaic/commit/a6a3ed85d668c80ff1006332f04ff9e8c330c91d is implemented. Looking at wireshark dump, I'm seeing TCP RESET, what appears to be after a transaction, nothing in `pm2-root logs`. Though when it's failing, I'm getting `JS TypeError` in the web console. I don't have a screen shot or the web console output now but will include it when the problem re-appears again.

**Expected behaviour**
To always work.

**Screenshots**
Will include it when the problem re-appears again

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox 
 - Version 66.0.2

**Comment by turtle0x1** [comment]
Cool include some screenshots is it after long periods of use ?

**Comment by lhorace** [comment]
I just had a chance today, the last time I access it was end of last month. It's running on my Desktop and I had a few reboots, network leaving and going since then. I thought it was corrupted image at first, restored from snapshot, no change. Reinstall and as soon as I added a second node, the problem re-appeared. Refreshing the page to attempt to debug the problem, it would partially render completely, then malformed, then suddenly on the last refresh the page rendered properly and seem to be working.

**Comment by lhorace** [comment]
Interestingly I just discovered that the operations pane is now empty, so I can't tell if tasks were completed, e.g. snaphots. What should I look for to help debug this? Figuring what's going here may lead to why problems where occurring earlier?

![operations-empty](https://user-images.githubusercontent.com/12678456/55921703-e92c6400-5bcb-11e9-9b78-339816af542f.png)

**Comment by lhorace** [comment]
While investigating another problem, I've discovered this in my LXD logs:

```
Apr 10 15:54:48 alvmsrv lxd[627]: t=2019-04-10T15:54:48-0400 lvl=warn msg="Rejecting request from untrusted client" ip=10.0.3.2:36200
Apr 10 15:55:22 alvmsrv lxd[627]: t=2019-04-10T15:55:22-0400 lvl=warn msg="Rejecting request from untrusted client" ip=10.0.3.2:36210
Apr 10 15:55:26 alvmsrv lxd[627]: t=2019-04-10T15:55:26-0400 lvl=warn msg="Rejecting request from untrusted client" ip=10.0.3.2:36216
Apr 10 15:55:26 alvmsrv lxd[627]: t=2019-04-10T15:55:26-0400 lvl=warn msg="Rejecting request from untrusted client" ip=10.0.3.2:36218
```

This could have lead to earlier problems, but I'm not seeing anything new since. I'm going to see if it's reproducible if I shutdown one node.

**Comment by lhorace** [comment]
Yes, it's very easy to reproduce this behaviour, at least with a minimum of 2 nodes, if one node goes down, you can't manager any node.

![dashboard-notworking](https://user-images.githubusercontent.com/12678456/55923315-f9940d00-5bd2-11e9-9ab5-4f3e36741b25.png)

**Comment by turtle0x1** [comment]
do you have a weak connection to your hosts ?

**Comment by lhorace** [comment]
Not that I'm aware of, one node is running on the same machine as LxdMosaic while the other is running on a different machine albeit on the same LAN. The caveat though, the local LXD is using a VLAN bridge, so it has to make a hop through the Firewall/Router. However one node going down, e.g. updating the kernel, shouldn't really bring down the WebUi down no? 

While we on this topic, this seems related, I'm having problems with Xterm. For approximately 30 seconds, reproducible every time, Xterm would stop responding. Looking at wireshark right before Xterm becomes unresponsive, LxdMosaic sends TLS Encryption Alert (see https://osqa-ask.wireshark.org/questions/38050/tlsv1-record-layer-encrypted-alert), then FIN, ACK with RST, lastly with TCP Retransmission.  I'm looking into enabling LXD debug, though like before, nothing in the logs from LxdMosaic.

**Comment by turtle0x1** [comment]
Okay there is quite a few different bugs going on here,

> Yes, it's very easy to reproduce this behaviour, at least with a minimum of 2 nodes, if one node goes down, you can't manager any node.

This I can fix later on this evevning the solution for the time being will either be to re-connect the server or delete it

If you need to delete it
```
mysql -u root 
use `LXD_Manager`;
select * from `Hosts`;
delete from `Hosts` where `Host_ID`  = The host you want to delete
```

> For approximately 30 seconds, reproducible every time, Xterm would stop responding. 

We have been noticing this when using xterm after an extended period I think its todo with the websocket how do you cause it break ?

**Comment by lhorace** [comment]
> This I can fix later on this evevning the solution for the time being will either be to re-connect the server or delete it

You could have it reconnect in the background and indicate the node is down, I would oppose to deleting it automatically. Temporary down-time is bound to happen. 

> We have been noticing this when using xterm after an extended period I think its todo with the websocket how do you cause it break ?

I could open a separate issue if you'd like? The time between Xterm connecting and becoming unresponsive is approximately 30 to 35 seconds. I can either just leave the cursor blanking for that time period or repeating any character till it fails. The interesting bit here, this is only appear to happen with just the local node. Here's a output of LXD monitor https://gist.github.com/703666fb9351b940b4308437dbc3c593. 

I follow the linuxcontainer forums and I've read through a couple threads relating to LXD having trouble with MTU, though I have the default 1500 on all my interfaces.

**Comment by turtle0x1** [comment]
If a server go's offline you will now not be able to use it, if you can test this when you can that would be great, there is a problem that cron can only run ever 1 minute so if a host goes down at for example 00:00:01 then if a user tries to do something until 00:01:00 it will still cause a crash but if they dont they will come back to a pop saything their server has gone offline, 

You can now use the ui while a server is offline it will show you the down host E.G;

![Screenshot_2019-04-12 LXD Mosaic](https://user-images.githubusercontent.com/12494629/56067888-ba052680-5d74-11e9-9bdf-70c2ecf4739f.png)

I may expand and capture it in another way later but this should do 

If you can find time to test at some point please run;

```
cd /var/www/LxdMosaic
git pull
mysql < sql/host_online.sql
crontab -l | { cat; echo "*/1 * * * * php /var/www/LxdMosaic/src/cronJobs/hostsOnline.php"; } | crontab -
```

**Comment by lhorace** [comment]
>  then if a user tries to do something until 00:01:00 it will still cause a crash

I honestly think, this still could be done better, it just doesn't look professional to have a broken page. I've forked the project and I can have a look at this when I have some spare time.

For the most part, it looks good to me.

**Comment by turtle0x1** [comment]
you are right but cron can only handle 1 minute intervals, so unless there is websocket for a heartbeat then im not sure how else to go about it

**Comment by lhorace** [comment]
What I'm thinking probably won't require much work and it won't need to check for LXD status.
