### ISSUE TITLE
Can you add a custom web port setting?

### ISSUE THREAD

**Issue by jgc9527** [turtle0x1/LxdMosaic#565]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by turtle0x1** [comment]
Heya

Sorry on holiday, this is possible in both the SNAP installation and via the script (by simply changing the apache config).

Without running the webserver as root its unlikely any web interface can change this.

Going to close but if you need advice on how to change the apache config just comment here (without re-opening) and ill help :smile:
