### ISSUE TITLE
Support token authentication

### ISSUE THREAD

**Issue by scubamuc** [turtle0x1/LxdMosaic#570]
**Describe the bug**
unable to reconnect host after reinstalling lxdmosaic snap

**To Reproduce**
remove and purge lxdmoaic snap from remote backup system
1. `sudo snap remove --purge lxdmosaic`
then followed steps:
> ## LXDMOSAIC Mosaic GUI Container Manager
> 
> Mit dem LXD-Mosaic Container Manager wird eine grafische Oberfläche als "Webseite" verfügbar gemacht um die LXC Container und VM's zu verwalten und auf den jeweiligen Servern ein oder aus zu schalten.
> 
> * LXD-Mosaic als Snap installieren
> 
>   sudo snap install lxdmosaic
> * LXC Hosts hinzufügen
> 
>   Damit Container und VM's zwischen unterschiedlichen LXC-Server hin und her verschoben und kopiert werden können, muss LXD über das Netzwerk erreichbar sein. Folgende Befehle sollten auf allen Hosts ausgeführt werden:
> 
>   lxc config set core.https_address \[::\] # LXD über IPV4 & IPV6 freigeben
> * LXC vertrautes Passwort
> 
>   lxc config set core.trust_password PASSWORT # passwort für LXDMosaic
> 
>   Das vertraute Passwort ist ein Schlüssel der auf allen Hosts vergeben werden muss damit die LXD-Mosaic GUI auf entfernte Hosts zugreifen kann/darf um Container vertrauensvoll auszutauschen. Dies verhält sich ähnlich wie ein SSH-Schlüssel.

**Expected behavior**
Easily add client to Web UI

**Screenshots**
![grafik](https://github.com/user-attachments/assets/df5e7232-bd21-4d64-a598-1ef452d8ff00)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Browser Firefox 129.0

**Additional context**
I'm obviously overlooking something... I've done this probably 50x and it always worked as documented in my wiki. I can't see the forest for all the trees 🫣 Please assist.

**Comment by turtle0x1** [comment]
I'd have to confirm but it looks like LXD/incus has dropped support for password authentication and you'll have to go the cert route instead of the password route :smile: 

Is this Incus as opposed to LXD?

**Comment by scubamuc** [comment]
@turtle0x1, nope-- lxd snap only.

Assuming lxdmosaic will only support lxd, I refrained from using incus.
I did play around with the "official" LXD UI though, that was some time ago but disabled that in favour of lxdmosaic. 

The issue only arose  when I removed the lxdmosaic snap and reinstalled it due to unsolvable connection issue after it had been running fine for at least 4 years. my setup is as [described here](https://github.com/scubamuc/). 

I'm able to complete all actions between PRODUCTION and BACKUP servers the LXD-CLI way... but it would be great to have lxdmosaic working again for remote actions via web interface and for lxd training purposes. At the moment each server has its own `localhost` instance of lxdmosaic running instead of both instances connected in one maintenance lxdmosaic GUI.

Please let me know if I can assist in testing or any information required.

**Comment by turtle0x1** [comment]
Sounds exciting, im glad your enjoying it :smile: 

Looks like LXD has changed the setup process to require tokens and deprecated the trust password setup (https://github.com/canonical/lxd/blob/96043b1ad3e5c61092b30977ae7344fd90793f0b/lxd/certificates.go#L439).

It looks like I'll have to add the new authentication method and deploy a new SNAP release.

> Could you guide me on that? I would need to test and document for training purposes

I was mistaken, I thought I allowed uploading certs but its actually socket authentication its support. If LXDMosaic is only managing one server and they are both SNAP, socket communication might be a better option anyway? I believe LXDMosaic SNAP still automatically gets the LXD plug, but honestly its been a while and im fuzzy on the exact configuration (at work currently, cant deep dive till later sorry).

**Comment by scubamuc** [comment]
@turtle0x1,
>cant deep dive till later sorry..

No need to be sorry, no rush either... thanks! 🤿👌

**Comment by turtle0x1** [comment]
The technical issue with the software has been addressed but as for your requests for docs and a new SNAP release please track #573 & #574 - I may ask you try the edge version before I bump to master as quite a lot of changes since a SNAP release, if your open to that? :smile:

**Comment by scubamuc** [comment]
@turtle0x1 thanks for getting to the bottom of this :+1: 

> I may ask you try the edge version before I bump to master as quite a lot of changes since a SNAP release, if your open to that? 

Sure I'm open to testing! I may need some guidance, but I'm quick to learn. I'll gladly share my docs too...
