### ISSUE TITLE
Fix snap build

### ISSUE THREAD

**Issue by turtle0x1** [turtle0x1/LxdMosaic#574]
SNAP no longer builds, fix its issue (probably apache version lagging)

**Comment by turtle0x1** [comment]
This was fixed in 78e018b6cdaec1546493be5a2371a5926dcf73da and can be closed.

@scubamuc if you want to test this you can switch to the edge snap channel on a new server `sudo snap refresh lxdmosaic --edge` or install it on a new one with `sudo snap install lxdmosaic --edge`.

When setting up your LXD server you set it to listen on the network as usual;

```sh
lxc config set core.https_address :8443
```

Instead of setting a "trust password" you create a token;

```
 lxc config trust add --name lxdmosaic
```

You copy this token and then when setting up LXDMosaic you paste this token instead of the "trust password".

This seems mandatory on LXD 6+ so I will update the docs, but probably alot of old versions kicking about still so the software supports both.

**Comment by scubamuc** [comment]
1. prepare testing environment LXD0:
    ![grafik](https://github.com/user-attachments/assets/42272ff4-7595-4727-ba8b-98381f4d68b6)

2. duplicate above process for LXD1:
    ![grafik](https://github.com/user-attachments/assets/baf27963-b21d-41a3-a775-913e5ed55a9c)

3. visit lxdmosaic in browser using IP of LXD1 (https://192.168.2.158)
    ERROR: site not responding, check LXD0, site not responding

@turtle0x1 what am I missing?

**Comment by turtle0x1** [comment]
Nothing its linked to this mysterious error report https://github.com/turtle0x1/LxdMosaic/issues/554

In which the user never reported the fix :sweat: Investigating...

**Comment by scubamuc** [comment]
@turtle0x1, don't sweat, relax and get a cup of tea... 

I have a question too though, is it necessary to run `lxd init` in the testing environment? as I understand `lxd init` at least `lxd init --minimal` is needed to issue `lxc config set core.https_address :8443`, or will it work without `lxd init`? Same goes for the certificate?

I did notice however, running LXD inside an LXC container on LXD requires `security.nesting` so that the containered container has root access to the host OS... sounds funny, but that's how it works I guess 👌

**Comment by turtle0x1** [comment]
I mean I didnt take it to the point of actually launching a container, once LXDMosaic connects its all i need to make sure we can connect (but I did it all without SNAP) :smile: 

The SNAP launch issue was introduced here 89beeba9fdfa2e0dd0d95e75dbefe76e32cc3c6f  because I changed certs paths, its as boring as it sounds and even more frurstarting to debug!

If you really want to hack around it on ubuntu you can do the following (but I will fix the actual problem, eventually);

```bash
# switch to root
sudo su - 

# Link self signed certs to live
ln -s /var/snap/lxdmosaic/current/certs/self-signed /var/snap/lxdmosaic/current/certs/live

# restart service
snap restart lxdmosaic

# just incase you already have a webserver already active, move lxdmosaic SNAP ports
sudo snap set lxdmosaic ports.http=81 ports.https=444

# go to https://localhost:444 in your browser, accept cert error and the token process should work
```

**Comment by scubamuc** [comment]
@turtle0x1 
> If you really want to hack around it on ubuntu you can do the following...

no, not really 🤓, I'm doing the suggested and getting a cup of tea....

**Comment by turtle0x1** [comment]
That should be fixed in this one if you want to run `sudo snap refresh lxdmosaic --edge` or the install command

**Comment by scubamuc** [comment]
@turtle0x1 
> That should be fixed...

👍 i'll continue testing...

**Comment by scubamuc** [comment]
` # snap refresh lxdmosaic --edge `

open UI in browser: ✅ success

complete first start:
1. 
![grafik](https://github.com/user-attachments/assets/566bf889-5559-45ab-b167-a23c8fbe9cd8)

2.
![grafik](https://github.com/user-attachments/assets/39bc8c9d-76f0-4887-89f4-9691356b0408)

3.
![grafik](https://github.com/user-attachments/assets/c46cce5c-4a56-4605-b101-46702fda683f)

**Comment by scubamuc** [comment]
Setting up host manually:
1.
![grafik](https://github.com/user-attachments/assets/1d3fb495-37d9-4eb0-96e3-1d8204a7c699)

2.
![grafik](https://github.com/user-attachments/assets/ef26349a-2fb7-46a4-8a76-b0ae57daeeac)

3.
![grafik](https://github.com/user-attachments/assets/52a01e4a-8803-46d9-832e-45920687be83)

4.
![grafik](https://github.com/user-attachments/assets/fdf2a431-fc37-48d5-8c95-fcf2faaa97bf)


connecting with snap socket works fine

**Comment by turtle0x1** [comment]
Is it the space at the end of the copy paste? I should probably `trim()` that

**Comment by scubamuc** [comment]
@turtle0x1 thanks for the heads up... i'll try that again.
> Is it the space at the end of the copy paste?

> I should probably trim() that
might prevent noob issues like this 🤓

**Comment by turtle0x1** [comment]
Pushed trim fix (will be `snap refresh blah`), am interested in you saying socket doesn't work can you open a separate issue for that please? (unless it was noise)

**Comment by scubamuc** [comment]
` # snap refresh lxdmosaic --edge ` on LXD0 and LXD1

get token for LXD1
![grafik](https://github.com/user-attachments/assets/9bb2db0c-6cdd-4308-bb59-2539edaa9902)


1. on LXD0 add LXD1
![grafik](https://github.com/user-attachments/assets/8ad62bfa-b6a0-4c45-9215-b14acfc59c03)

2. on LXD0 token of LXD1 fails
![grafik](https://github.com/user-attachments/assets/eee477f6-81b4-41dd-9a81-632eaff5e8cf)

issue persists, token not valid

**Comment by scubamuc** [comment]
@turtle0x1 
> am interested in you saying socket doesn't work can you open a separate issue for that please? (~~unless it was noise~~)

done!

**Comment by scubamuc** [comment]
@turtle0x1, I'm getting the feeling I'm doing something totaly wrong... if so, please guide me as I don't want to waste your time with dumb user issues. 🫣

**Comment by scubamuc** [comment]
double check ping LXD1 from LXD0
![grafik](https://github.com/user-attachments/assets/7d0b5a74-dcf9-4c05-858e-377cdc01e68f)

double check ping LXD0 from LXD1
![grafik](https://github.com/user-attachments/assets/d8ea4e7f-e669-4b93-bcf2-37dbefeb5ad0)

its not a network issue!

double check `lxc config set core.https_address :8443` this is different... 

I remember doing this according to my docs:

`  lxc config set core.https_address \[::\] `

**Comment by scubamuc** [comment]
> [This things a temperamental little slut](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpDn2EPwS6SqAaSR5gKy0xOAsGWLZH9t_WAQ&s)
> 
> Will investigate, saw similar in testing but it was transitory

at your service sir... 🤓

**Comment by scubamuc** [comment]
standing by for further testing and bug squashing... don't you just love SNAP? 🤣

**Comment by turtle0x1** [comment]
Its quite hard to duplicate this, it may be that your re-using a token that you've already used (they expire after first use as I understand it).

If you wanna go through it over video chat / teamviewer / something you can find my email from the git logs and i'll lend a hand :smile:

**Comment by scubamuc** [comment]
yeah, that's cool... I'd hate to think I'm wasting your time doing stupid user errors. 👍
I'm only available after office hours though. are we in the same time-zone? CET 14:30

**Comment by turtle0x1** [comment]
Im London so its close enough :)

**Comment by scubamuc** [comment]
> London so its close enough

👍 (Munich...)

>you can find my email from the git logs

nope, dunno how. but we'll find a way.
