### ISSUE TITLE
ct not found after rename

### ISSUE THREAD

**Issue by lhorace** [turtle0x1/LxdMosaic#58]
**Describe the bug**
You'll get a `Not found` error after renaming a CT.

**To Reproduce**
1. Create a CT
2. Rename CT
3. Change state

**Expected behavior**
Able to modify CT state and settings

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 66

**Comment by turtle0x1** [comment]
Please pull and test if you can :)

**Comment by lhorace** [comment]
Will do when I want work on it. Right now I am resting.

**Comment by lhorace** [comment]
LGTM!
