### ISSUE TITLE
Manage Clusters

### ISSUE THREAD

**Issue by turtle0x1** [turtle0x1/LxdMosaic#6]
Clusters were introduced in LXD 3.0+  so we need to  able to manage them on hosts that are 3.0 + you can read about the  api [here](https://github.com/lxc/lxd/blob/master/doc/rest-api.md#10cluster) and will need a new end point in the [connector library](https://github.com/turtle0x1/php-lxd/)

**Comment by sergeyjsg** [comment]
Hello! Any progress on this? I believe there is no UI at all in the universe that can manage LXC cluster (proxmox does not counts). Good opportunity for the project!

**Comment by turtle0x1** [comment]
Hey, no there isnt but i dont use clustering so i need some input as to what it should do differently 

Let me know!

**Comment by turtle0x1** [comment]
closed in 79eeb315e25c948e47aa3ab6c739c7532aa27a25
