### ISSUE TITLE
Deployments

### ISSUE THREAD

**Issue by turtle0x1** [turtle0x1/LxdMosaic#65]
**Is your feature request related to a problem? Please describe.**
Im going to implement a "deployment" creator this will take a group of cloud configs and allow you to deploy containers based on them, 

for example you might create a "deployment" containing cloud configs for;

 - a msql container
 - a apache2 container
 - a redis container

It should include; 

- [x]  A dashboard showing deployments containers including
   - The overall mem usage 
   - The containers in the deployment
- [x]  Deployment stop / start (all containers in the deployment)
- **X**  specify a container boot order 
  - This will come later
- [x]  deploy x number of each type of container

What it wont include; 
 - Autoload load balancing between nodes E.G
   - If you run a web server farm behind a load balancer it won't modify the LB to point at your new web servers 
 - Attempts at networking 
   - This should come from the profiles there are too many ways to configure LXD's networking to make any auto attempt
 - Anything else that's to complex

If you have any ideas just pile them in here

**Comment by lhorace** [comment]
Is this similar to Dockerfile? I haven't had a chance to experiment with `cloud configs`, until I do, not much I can say here. It sounds pretty interesting.

Also, this sounds like clustering?

**Comment by turtle0x1** [comment]
cloud config (or cloud init) is used to install packages and run any commands you need to setup a container when its created, its similar to a docker-compose file

its like clustering a set of containers as an application 

@bmullan you seem to be everywhere when it comes to LXD do you have any thoughts?

**Comment by bmullan** [comment]
Cloud-init was introduced by Canonical about 9 yrs ago to facilitate ubuntu deployment into the AWS cloud.

It was based on work by an early AWS adooter & ubuntu user named Eric Hammond (Alestic).

Cloud Init solved the deployment problem in AWS where you might spin up lots of AWS instances but each time had to manually ssh into each to:

apt-get update. 
apt-get upgrade. 
open certain ports. 
install the same initial software. 
etc. 

So yeah supporting a cloud init concept is a good idea for containers for the very same reasons

One thing I'd suggest might be implementing some form to create them by the user entering just the commands they want to run

User names the form 

And when saved it becomes part of a table of checkbox cloud-init's that can be chained together & applied to a new deployment.

**Comment by turtle0x1** [comment]
Thanks for the history quite interesting! 

Do you have any ideas in terms of the idea I was proposing as Ive seen you comment on some of the other projects like LxdDock

**Comment by bmullan** [comment]
@turtle0x1 I thought I did comment?  :-) 

Cloud-Init is a great idea for Mosaic and if you can implement it ... you should.

My suggestions from the previous comment were (if possible):

- One thing I'd suggest might be implementing some form/template to create them by the Mosaic User entering just the commands they want to run (not editing/creating an entire cloud-init file
- Then the User names the form/template
- When saved, the form/template becomes part of a "table" of checkbox cloud-init's that can be "chained together" in a certain order of execution & applied to a new deployment.

That is of course if its possible to do the above.

BTW... you are making great progress on enhancing Mosaic !!

Brian

**Comment by lhorace** [comment]
> not editing/creating an entire cloud-init file

Might be a good idea to do both to avoid limitations where possible, as a cursory glance at cloud-init,  you can do more than simply commands. Could be wrong.

**Comment by bmullan** [comment]
@lhorace you aren't wrong.   Cloud Init can do quite complex things if you configure it so.
Cloud Init file is limited in maximum "size" though but that may not apply to this LXD use-case as 
I the referenced comment #1 below suggests.   I guess experimenting with a larger Cloud Init file
would tell us if LXD has a problem with say a 32,000 byte (or larger) Cloud Init:  

> https://cloudinit.readthedocs.io/en/latest/topics/format.html
> 
> Content found to be gzip compressed will be uncompressed. The uncompressed data will then be used as if it were not compressed. This is typically useful because user-data is limited to ~16384 [1] bytes.  
> 
> [1] See your cloud provider for applicable user-data size limitations…

**Comment by turtle0x1** [comment]
If you want to expirement you can either try it out actually in lxd mosaic under `Cloud Configs` and then `Deploy` button to a container or on the cli `lxc profile set YOUR_PROFILE_NAME user.user-data - < your_yaml.yml` followed by `lxc launch ubuntu: c1 -p default -p YOUR_PROFILE_NAME`

**Comment by bmullan** [comment]
Stephane Graber replied back on the LXD forum that there is NO size limit for cloud-init on LXD

**Comment by turtle0x1** [comment]
https://github.com/yyyar/gobetween/wiki/Discovery looks pretty prommising as a helpful tool (thanks for sharing @bmullan )

**Comment by turtle0x1** [comment]
Hey guys if you get some time could you please give this ago #72

**Comment by bmullan** [comment]
I'll try it this week as I should have some time to experiment a little..

**Comment by turtle0x1** [comment]
This has been merged now

**Comment by lhorace** [comment]
I've been off-the-computer and swamped with todo lists, so my priority list is swamped. Sorry I didn't have a chance to experiment. I do plan to experiment in the future.
