### ISSUE TITLE
Producing version numbers?

### ISSUE THREAD

**Issue by lhorace** [turtle0x1/LxdMosaic#66]
**Is your feature request related to a problem? Please describe.**
I like to keep a separate snapshots for each release, in cases where things break, I can later revert to a working version.

For now, I'll go by commits, though I still have to track down what changed.

**Describe the solution you'd like**
Include release version if possible

**Describe alternatives you've considered**
Commits.

**Comment by turtle0x1** [comment]
once i finish #65 (which btw if you have any comments on id be glad to here them) ill tag version 0.2

**Comment by lhorace** [comment]
> once i finish #65 ... ill tag version 0.2
Sure.

about #65, I'll have to sit down, read it, and think about it. I'm not too sure what it actually does, though, I can test a PR on another system to offer any valuable comment.

**Comment by turtle0x1** [comment]
i have updated it, it should be clearer now

**Comment by turtle0x1** [comment]
Just tagged version 0.2.0 and ill keep doing this in the future
