### ISSUE TITLE
Rearrange and resize widgets.

### ISSUE THREAD

**Issue by lhorace** [turtle0x1/LxdMosaic#67]
**Is your feature request related to a problem? Please describe.**
![widget-small](https://user-images.githubusercontent.com/12678456/56099633-85f94500-5edd-11e9-9a8f-68dec867d1f7.png)

As you can see, I'm not able to resize or rearrange widgets to avoid scrolling.

**Describe the solution you'd like**
Ability to rearrange and resize widgets.

**Comment by turtle0x1** [comment]
This isn't on my immediate to-do list, i look at any PR but ill leave it open for future

**Comment by lhorace** [comment]
This is on my todo list, btw, great work for 0.3.0. Are you using bootstrap, jquery?

**Comment by turtle0x1** [comment]
Thanks yeah I'm using bootstrap and jquery! [split.js](https://split.js.org/) looked quite interesting

**Comment by lhorace** [comment]
Awesome, next time I have sometime, I'll look at code and stick to API!

**Comment by lhorace** [comment]
One thing, what's the easiest way to test? How do you test? Do I need the backend?

**Comment by lhorace** [comment]
I really really really don't want to touch NodeJS

**Comment by turtle0x1** [comment]
Luckily there is no node involved :)

By far the easiest way is to run the install script on your local machine, but this will setup everything as root & **it will also add lots of packages to your system** (not really a problem but it may be to you)! 

Once its installed you can add the `/var/www/LxdMosaic` folder to your ide (VS code, atom or whatever) and develop away (you should be able to go into your browser and do https://localhost but if you already have apache setup you will need to add lxd.local to your hosts file and use https://lxd.local 

If all goes well you should be able to just make changes to the code refresh the page and see them
