### ISSUE TITLE
Rename snapshots from Webui.

### ISSUE THREAD

**Issue by lhorace** [turtle0x1/LxdMosaic#68]
**Is your feature request related to a problem? Please describe.**
It would be nice to rename snapshots from ui in cases where one makes a mistake.

**Describe alternatives you've considered**
Rename snapshot from cli.

**Comment by turtle0x1** [comment]
Please `git pull` and give it a test whenever you get a chance

**Comment by lhorace** [comment]
Hello there, fyi, LGTM!
