### ISSUE TITLE
Two applications possibly useful to Mosaic

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdMosaic#69]
Just thought I'd pass these two along in case they are of interest to you and your project.

This looks to be a nice tool to create an LXD image server:   
https://github.com/Avature/lxd-image-server

and this looks like a great way to manage SSH cert access to many servers/containers:  
https://github.com/gravitational/teleport  
https://gravitational.com/teleport

Don't know if they would be useful to Mosaic but thought I'd make you aware of them?

Brian

**Comment by turtle0x1** [comment]
Thanks for sharing the links, 

The first once looks interesting but, im not sure I will do an image based approach it might involve some complex call backs with verifying cloud config ran successfully (they also don't play well with another idea I have down the line)
