### ISSUE TITLE
No version detected for CentOS containers

### ISSUE THREAD

**Issue by trenb** [turtle0x1/LxdMosaic#79]
**Describe the bug**
I run on CentOS, and your interface seems unable to figure out the version the containers are running. Am I missing something in the config of my containers? I had migrated my containers from OpenVZ to LXD, and started originally with an image from LXD, which I replaced the rootfs of. 

**To Reproduce**
1. Run a CentOS container
2. Look at it in mosaic

**Expected behavior**
It would be nice if it could either show the version, or just not show anything for the version.

**Screenshots**
<img width="1008" alt="Screen Shot 2019-05-04 at 9 23 38 AM" src="https://user-images.githubusercontent.com/4175714/57181918-64d9a380-6e4e-11e9-8ddc-5e1717e799bc.png">

**Comment by turtle0x1** [comment]
If you do 

```
cd /var/www/LxdMosaic`
git pull
```

This should be fixed

**Comment by trenb** [comment]
Thanks! Love this console by the way, thank you for your hard work!
