### ISSUE TITLE
No host listed for containers

### ISSUE THREAD

**Issue by trenb** [turtle0x1/LxdMosaic#80]
**Describe the bug**
None of the containers list the host they're running on. It's just blank.

**To Reproduce**
1. Select a container
2. Look at Container Details
3. Host field is blank

**Expected behavior**
It should list the host it's running on

**Screenshots**
<img width="484" alt="Screen Shot 2019-05-04 at 9 32 36 AM" src="https://user-images.githubusercontent.com/4175714/57182056-e7169780-6e4f-11e9-8941-51e247c12822.png">

**Comment by turtle0x1** [comment]
A git pull will fix this,

If your enjoying the app please consider giving it a star :) 

Thanks

**Comment by trenb** [comment]
Thanks again for the quick fix! Star given! I think there's only one more issue I see. I'll see if I can contribute instructions for getting this running on CentOS 7 this week.

**Comment by turtle0x1** [comment]
Yeah it be great if you could provide instructions (even better would be a script) for centos the example that works on ubuntu is [here](https://github.com/turtle0x1/LxdMosaic/blob/master/examples/install_with_clone.sh)

**Comment by trenb** [comment]
Yeah, I used your script to figure out packages and locations of things. I'll take a stab at making a centos version of your script this week.
