### ISSUE TITLE
"Storage" is misspelt as "Stroage" in the code and web interface

### ISSUE THREAD

**Issue by trenb** [turtle0x1/LxdMosaic#81]
**Describe the bug**
Spelling error.

**To Reproduce**
1. On the top navigation bar, Storage is spelt as "Stroage". Also, doing a grep through the code shows the same misspelling.

**Screenshots**
```
[root@mosaic LxdMosaic]# grep -r Stroage *
src/views/boxes/storage.php:function loadStroageView()
src/views/boxes/storage.php:                            loadStroageView();
src/views/modals/storage/createPool.php:                loadStroageView();
src/views/index.php:              <i class="fas fa-hdd"></i> Stroage </a>
src/views/index.php:    loadStroageView();
```

**Comment by turtle0x1** [comment]
Good spot :)

**Comment by trenb** [comment]
Thanks for all these super fast fixes! I think that's it for the things I noticed. If I find more, I'll log more tickets!
