### ISSUE TITLE
Centos 7 or Curl 7.29.0 breaks lxd mosaic

### ISSUE THREAD

**Issue by trenb** [turtle0x1/LxdMosaic#84]
**Describe the bug**
Added a second LXD host to interface

**To Reproduce**
1. Add a second host to LXD mosaic

**Screenshots**
<img width="1422" alt="Screen Shot 2019-05-07 at 11 57 10 AM" src="https://user-images.githubusercontent.com/4175714/57325665-6362e200-70bf-11e9-99c1-fa5c80cc92ad.png">

This is reproducible for me. If I look at the pm2 logs, all I see is this:
```
{"host":"https:\/\/lxd-a01.XXXX.lan:8443","offline":true}
{"host":"https:\/\/lxd-a01.XXXX.lan:8443","offline":false}
``` 
And there's no mention of the second host I added. Looking at the mysql database, both hosts are entered correctly.
```
root@localhost:LXD_Manager> select * from Hosts;
+---------+-------------------------------+---------------------------+-----------------------+----------------------+-------------+------------+
| Host_ID | Host_Url_And_Port             | Host_Cert_Path            | Host_Cert_Only_File   | Host_Key_File        | Host_Online | Host_Alias |
+---------+-------------------------------+---------------------------+-----------------------+----------------------+-------------+------------+
|       1 | https://lxd-a01.XXXX.lan:8443 | lxd-a01.XXXX.lan.combined | lxd-a01.XXXX.lan.cert | lxd-a01.airg.lan.key |           1 | NULL       |
|       2 | https://lxd-b01.XXXX.lan:8443 | lxd-b01.XXXX.lan.combined | lxd-b01.XXXX.lan.cert | lxd-b01.airg.lan.key |           1 | NULL       |
+---------+-------------------------------+---------------------------+-----------------------+----------------------+-------------+------------+
```
I ran into this issue on a previous version of this software, but with the latest version, I'm still having this problem. Any suggestions on debugging this further?

**Comment by trenb** [comment]
And if I remove the second host I added, the interface works fine again:
```
root@localhost:LXD_Manager> delete from Hosts where Host_ID=2;
Query OK, 1 row affected (0.002 sec)
```

**Comment by turtle0x1** [comment]
Can you refresh the page with dev tools open and show me the result of the get request I haven't got my other server online right now

**Comment by trenb** [comment]
Actually, I have a bit more debug for you. If I try to run the fleet analytics cron, I get the following error:
```
# php /var/www/LxdMosaic/src/cronJobs/fleetAnalytics.php
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://lxd-b01.XXXX.lan:8443/1.0/storage-pools` resulted in a `403 Forbidden` response:
{"error":"not authorized","error_code":403,"type":"error"}


 in /var/www/LxdMosaic/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /var/www/LxdMosaic/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /var/www/LxdMosaic/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /var/www/LxdMosaic/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /var/www/LxdMosaic/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /var/www/LxdMosaic/vendor/guzzlehttp/guzzle/src/Handler/CurlMultiHandler.php(98): Guzz in /var/www/LxdMosaic/vendor/dhope0000/lxd/src/HttpClient/Plugin/LxdExceptionThower.php on line 38
```
I'm using the correct password. And yes, both hosts are online.

**Comment by turtle0x1** [comment]
Interesting what version of LXD are the hosts using ?

Have you modified any certificates locations etc ? 

Im going boot up my other server now

**Comment by trenb** [comment]
LXD 3.11 on both hosts. And no, I haven't modified any of the certs. All I have to do to break things is just add a second LXD host.

**Comment by trenb** [comment]
Sorry, how do I get you the results of GetOverviewController? I'm not an expert in the dev console in Chrome.

**Comment by trenb** [comment]
As well, as soon as I remove the second host, fleetAnalytics.php no longer errors out.

**Comment by turtle0x1** [comment]
Hey so I can't duplicate this, can you open developer tools in your browser (shift + ctrl + i) and show me the response for `GetOverviewController` 

Also on lxd-b01 can you run `sudo lxc config trust list` and check the certificate was added

**Comment by trenb** [comment]
Here's the response for GetOverviewController when I add the second host:
```
{"state":"error","message":"LXD client certificate is not trusted."}
```

**Comment by trenb** [comment]
Here's the config trust for lxd-a01:
```
+--------------+-------------+-----------------------------+-----------------------------+
| FINGERPRINT  | COMMON NAME |         ISSUE DATE          |         EXPIRY DATE         |
+--------------+-------------+-----------------------------+-----------------------------+
| 7869ee9c30bd | 127.0.0.1   | May 7, 2019 at 7:06pm (UTC) | May 6, 2020 at 7:06pm (UTC) |
+--------------+-------------+-----------------------------+-----------------------------+
| ab6e8136a784 | 127.0.0.1   | May 7, 2019 at 7:27pm (UTC) | May 6, 2020 at 7:27pm (UTC) |
+--------------+-------------+-----------------------------+-----------------------------+
| b1db2ca72369 | 127.0.0.1   | May 6, 2019 at 3:45pm (UTC) | May 5, 2020 at 3:45pm (UTC) |
+--------------+-------------+-----------------------------+-----------------------------+
```
and for b01:
```
+--------------+-----------------------+-----------------------------+-----------------------------+
| FINGERPRINT  |      COMMON NAME      |         ISSUE DATE          |         EXPIRY DATE         |
+--------------+-----------------------+-----------------------------+-----------------------------+
| 86e21c088e70 | 127.0.0.1             | May 7, 2019 at 7:05pm (UTC) | May 6, 2020 at 7:05pm (UTC) |
+--------------+-----------------------+-----------------------------+-----------------------------+
| 8d2eb7bb6ac0 | 127.0.0.1             | May 7, 2019 at 6:54pm (UTC) | May 6, 2020 at 6:54pm (UTC) |
+--------------+-----------------------+-----------------------------+-----------------------------+
| c2802fd2ff69 | root@lxd-a01.airg.lan | May 7, 2019 at 6:01pm (UTC) | May 4, 2029 at 6:01pm (UTC) |
+--------------+-----------------------+-----------------------------+-----------------------------+
```

**Comment by trenb** [comment]
So why is adding a host, not trusting the certificate?

**Comment by turtle0x1** [comment]
Can you try adding the host by IP instead of dns name

**Comment by trenb** [comment]
Adding via IP breaks exactly the same way. And if I add either one of these on their own, everything works. It's only when I have more than 1 host defined does this break.

**Comment by trenb** [comment]
It looks like the certs are being copied to the mosaic host:
```
# ls -la
total 56
drwxr-xr-x 2 apache apache 4096 May  7 19:36 .
drwxr-xr-x 3 root   root   4096 May  6 14:39 ..
-rw-r--r-- 1 apache apache 1452 May  7 19:36 192.168.100.221.cert
-rw-r--r-- 1 apache apache 3156 May  7 19:36 192.168.100.221.combined
-rw-r--r-- 1 apache apache 1704 May  7 19:36 192.168.100.221.key
-rw-r--r-- 1 apache apache 1452 May  7 19:35 192.168.107.209.cert
-rw-r--r-- 1 apache apache 3156 May  7 19:35 192.168.107.209.combined
-rw-r--r-- 1 apache apache 1704 May  7 19:35 192.168.107.209.key
-rw-r--r-- 1 apache apache 1452 May  7 19:27 lxd-a01.XXXX.lan.cert
-rw-r--r-- 1 apache apache 3156 May  7 19:27 lxd-a01.XXXX.lan.combined
-rw-r--r-- 1 apache apache 1704 May  7 19:27 lxd-a01.XXXX.lan.key
-rw-r--r-- 1 apache apache 1452 May  7 19:05 lxd-b01.XXXX.lan.cert
-rw-r--r-- 1 apache apache 3156 May  7 19:05 lxd-b01.XXXX.lan.combined
-rw-r--r-- 1 apache apache 1704 May  7 19:05 lxd-b01.XXXX.lan.key
```

**Comment by turtle0x1** [comment]
LxdMosaic generates the certificate and deploys it to the lxd instance, 

this is going sound silly but are you sure there is no way the DNS could accidentally route the wrong host ? Its proving difficult to replicate this,

When you did it by IP did you clear out the hosts table completely ?

**Comment by trenb** [comment]
No, DNS is functioning correctly here. Like I said, I can add either host INDIVIDUALLY, and the interface works. As soon as I add a second host, the interface breaks.

And yes, I cleared out the Hosts table in MySQL before re-adding the hosts as IPs.

**Comment by turtle0x1** [comment]
Can edit `src/classes/Model/Client/LxdClient.php` and completely remove the lines 

```
        if ($checkCache && isset($this->clientBag[$hostDetails["Host_Url_And_Port"]])) {
            return $this->clientBag[$hostDetails["Host_Url_And_Port"]];
        }
```

**Comment by trenb** [comment]
No difference.

**Comment by turtle0x1** [comment]
Can you try 

`curl --cert lxd-b01.XXXX.lan.combined  -skv https://localhost:8443/1.0/storage-pools`

**Comment by trenb** [comment]
Okay, so this is a bit strange. After updating the URL to specify port 8443 (default LXD port), I get not authorized:
```
# curl --cert lxd-b01.XXXX.lan.combined -skv https://lxd-b01.XXXX.lan:8443/1.0/storage-pools
* About to connect() to lxd-b01.XXXX.lan port 8443 (#0)
*   Trying 192.168.100.221...
* Connected to lxd-b01.XXXX.lan (192.168.100.221) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* warning: certificate file name "lxd-b01.XXXX.lan.combined" handled as nickname; please use "./lxd-b01.XXXX.lan.combined" to force file name
* skipping SSL peer certificate verification
* NSS: client certificate not found: lxd-b01.XXXX.lan.combined
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=root@lxd-b01.XXXX.lan,O=linuxcontainers.org
*       start date: May 07 16:57:42 2019 GMT
*       expire date: May 04 16:57:42 2029 GMT
*       common name: root@lxd-b01.XXXX.lan
*       issuer: CN=root@lxd-b01.XXXX.lan,O=linuxcontainers.org
> GET /1.0/storage-pools HTTP/1.1
> User-Agent: curl/7.29.0
> Host: lxd-b01.XXXX.lan:8443
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Content-Type: application/json
< X-Content-Type-Options: nosniff
< Date: Tue, 07 May 2019 20:01:06 GMT
< Content-Length: 60
<
{"error":"not authorized","error_code":403,"type":"error"}
```
But if I specify the path for the certificate it works:
```
# curl --cert ./lxd-b01.XXXX.lan.combined -skv https://lxd-b01.XXXX.lan:8443/1.0/storage-pools
* About to connect() to lxd-b01.XXXX.lan port 8443 (#0)
*   Trying 192.168.100.221...
* Connected to lxd-b01.XXXX.lan (192.168.100.221) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate from file
*       subject: E=info@opensauce.systems,CN=127.0.0.1,OU=Dev,O=Open Sauce Systems,L=Cowes,ST=Isle Of Wight,C=UK
*       start date: May 07 19:05:12 2019 GMT
*       expire date: May 06 19:05:12 2020 GMT
*       common name: 127.0.0.1
*       issuer: E=info@opensauce.systems,CN=127.0.0.1,OU=Dev,O=Open Sauce Systems,L=Cowes,ST=Isle Of Wight,C=UK
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=root@lxd-b01.XXXX.lan,O=linuxcontainers.org
*       start date: May 07 16:57:42 2019 GMT
*       expire date: May 04 16:57:42 2029 GMT
*       common name: root@lxd-b01.XXXX.lan
*       issuer: CN=root@lxd-b01.XXXX.lan,O=linuxcontainers.org
> GET /1.0/storage-pools HTTP/1.1
> User-Agent: curl/7.29.0
> Host: lxd-b01.XXXX.lan:8443
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 07 May 2019 20:03:41 GMT
< Content-Length: 132
<
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":["/1.0/storage-pools/zfs"]}
```

**Comment by trenb** [comment]
This also works when I use IP:
```
# curl --cert ./192.168.100.221.combined -skv https://192.168.100.221:8443/1.0/storage-pools
* About to connect() to 192.168.100.221 port 8443 (#0)
*   Trying 192.168.100.221...
* Connected to 192.168.100.221 (192.168.100.221) port 8443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate from file
*       subject: E=info@opensauce.systems,CN=127.0.0.1,OU=Dev,O=Open Sauce Systems,L=Cowes,ST=Isle Of Wight,C=UK
*       start date: May 07 19:36:15 2019 GMT
*       expire date: May 06 19:36:15 2020 GMT
*       common name: 127.0.0.1
*       issuer: E=info@opensauce.systems,CN=127.0.0.1,OU=Dev,O=Open Sauce Systems,L=Cowes,ST=Isle Of Wight,C=UK
* SSL connection using TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: CN=root@lxd-b01.XXXX.lan,O=linuxcontainers.org
*       start date: May 07 16:57:42 2019 GMT
*       expire date: May 04 16:57:42 2029 GMT
*       common name: root@lxd-b01.XXXX.lan
*       issuer: CN=root@lxd-b01.XXXX.lan,O=linuxcontainers.org
> GET /1.0/storage-pools HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 192.168.100.221:8443
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Tue, 07 May 2019 20:15:07 GMT
< Content-Length: 132
<
{"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":["/1.0/storage-pools/zfs"]}
```

**Comment by turtle0x1** [comment]
I temporarily replicated this but can't do it again still trying

**Comment by trenb** [comment]
Let me know if you need any more information!

**Comment by turtle0x1** [comment]
See I the only way I could duplicate this is with a DNS (or conflicting ip) error no amount of killing hosts / combinations of domain names could break it , are you 100% sure that the ips don't conflict or some dns cache causes the servers to be confused ? 

Because its adding the host successfully and then trying the wrong server with the wrong certificate, 

Could you change `src/classes/Model/Client/LxdClient.php` and replace the contents of `getANewClient` so it looks like:

```php
    public function getANewClient($hostId, $checkCache = true, $setProject = true)
    {
        $hostDetails = $this->getDetails->getAll($hostId);

        if (empty($hostDetails)) {
            throw new \Exception("Couldn't find info for this host", 1);
        }

        if ($checkCache && isset($this->clientBag[$hostDetails["Host_Url_And_Port"]])) {
            return $this->clientBag[$hostDetails["Host_Url_And_Port"]];
        }

        $certPath = $this->createFullcertPath($hostDetails["Host_Cert_Path"]);
        $config = $this->createConfigArray($certPath);
        var_dump($config);
        var_dump($hostDetails["Host_Url_And_Port"]);
        $client = $this->createNewClient($hostDetails["Host_Url_And_Port"], $config);
        $client->setProject($this->session->get("host/$hostId/project", "default"));
        return $client;
    }

```
Then refresh the page and from network tools again show the contents of the response

**Comment by trenb** [comment]
Here you go!
```
array(2) {
  ["verify"]=>
  bool(false)
  ["cert"]=>
  array(2) {
    [0]=>
    string(67) "/var/www/LxdMosaic/src/sensitiveData/certs/192.168.100.221.combined"
    [1]=>
    string(0) ""
  }
}
string(28) "https://192.168.100.221:8443"
array(2) {
  ["verify"]=>
  bool(false)
  ["cert"]=>
  array(2) {
    [0]=>
    string(67) "/var/www/LxdMosaic/src/sensitiveData/certs/192.168.107.209.combined"
    [1]=>
    string(0) ""
  }
}
string(28) "https://192.168.107.209:8443"
{"state":"error","message":"LXD client certificate is not trusted."}
```

**Comment by trenb** [comment]
And no, there's no conflicting IPs. These hosts were just built in the past week. The IPs are unique. As are the DNS names. The fact it doesn't work via IP or DNS seems to rule out DNS as the issue.

**Comment by turtle0x1** [comment]
Can we arrange privately to have me dial into your network (perhaps team viewer?) in the interest in tracking down this bug and improving the library ?

**Comment by trenb** [comment]
No, but I can give you access to my private server where I have the same problem. :)

**Comment by turtle0x1** [comment]
Cool either works can you private message me on https://discuss.linuxcontainers.org/ with connection details ?

**Comment by trenb** [comment]
I'm feeling stupid, but I can't figure out where to send a private message. I've created an account. Can you point me in the right direction please? :)

**Comment by turtle0x1** [comment]
If you click your user icon, then click the envelope, the click new message and my username is turtle0x1 :)

**Comment by turtle0x1** [comment]
Ah you might not have permissions to as your a new user can  you email me on goaway321@protonmail.com

**Comment by trenb** [comment]
Got it! email sent!

**Comment by turtle0x1** [comment]
Its a curl bug with centos or curl version 7.29.0 (or maybe even php) but closing the connection fixes the issue,

Apply the fix to `src/classes/Model/Client/LxdClient.php` and change `createConfigArray` to look like this as a temporary work around 

```php
    public function createConfigArray($certLocation)
    {
     	$certPath = realpath($certLocation);

        if ($certPath === false) {
            throw new \Exception("Certificate has gone walk abouts", 1);
        }

	return [
            'verify' => false,
            'cert' => [
                $certPath,
                ''
            ],
            'headers' => ['Connection' => 'close'], // Or simply add this to the request object
        ];
    }
```

**Comment by trenb** [comment]
I made that change, but it still seems broken on my system at work.


On May 7, 2019 at 3:28:44 PM, turtle0x1 (notifications@github.com) wrote:

Its a curl bug with centos or curl version 7.29.0 (or maybe even php) but
closing the connection fixes the issue,

Apply the fix to src/classes/Model/Client/LxdClient.php and change
createConfigArray to look like this as a temporary work around

    public function createConfigArray($certLocation)    {
$certPath = realpath($certLocation);
        if ($certPath === false) {            throw new
\Exception("Certificate has gone walk abouts", 1);        }
    return [            'verify' => false,            'cert' => [
          $certPath,                ''            ],
'headers' => ['Connection' => 'close'], // Or simply add this to the
request object        ];    }

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/turtle0x1/LxdMosaic/issues/84#issuecomment-490277817>,
or mute the thread

**Comment by trenb** [comment]
I get this error from your change:

PHP Fatal error:  Uncaught RuntimeException: Failed to start the session
because headers have already been sent by
"/var/www/LxdMosaic/src/classes/Model/Client/LxdClient.php" at line 35. in
/var/www/LxdMosaic/vendor/symfony/http-foundation/Session/Storage/NativeSessionStorage.php:145


On May 7, 2019 at 3:28:44 PM, turtle0x1 (notifications@github.com) wrote:

Its a curl bug with centos or curl version 7.29.0 (or maybe even php) but
closing the connection fixes the issue,

Apply the fix to src/classes/Model/Client/LxdClient.php and change
createConfigArray to look like this as a temporary work around

    public function createConfigArray($certLocation)    {
$certPath = realpath($certLocation);
        if ($certPath === false) {            throw new
\Exception("Certificate has gone walk abouts", 1);        }
    return [            'verify' => false,            'cert' => [
          $certPath,                ''            ],
'headers' => ['Connection' => 'close'], // Or simply add this to the
request object        ];    }

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/turtle0x1/LxdMosaic/issues/84#issuecomment-490277817>,
or mute the thread

**Comment by trenb** [comment]
I copied the file from my system and it works. I must be tired, because
this diff doesn't make sense to me why this wouldn't be working with my
file.

# diff LxdClient.php LxdClient.php.TREN
34a35,36
>         var_dump($config);
>         var_dump($hostDetails["Host_Url_And_Port"]);
59,63c61
< //            'debug'=>true,
<   //          'Connection' => 'close',
<     //         CURLOPT_FORBID_REUSE => true,
<       //          CURLOPT_FRESH_CONNECT => true,
<      'headers' => ['Connection' => 'close'], // Or simply add this to the
request object
---
>         'headers' => ['Connection' => 'close'], // Or simply add this to
the request object


On May 7, 2019 at 3:28:44 PM, turtle0x1 (notifications@github.com) wrote:

Its a curl bug with centos or curl version 7.29.0 (or maybe even php) but
closing the connection fixes the issue,

Apply the fix to src/classes/Model/Client/LxdClient.php and change
createConfigArray to look like this as a temporary work around

    public function createConfigArray($certLocation)    {
$certPath = realpath($certLocation);
        if ($certPath === false) {            throw new
\Exception("Certificate has gone walk abouts", 1);        }
    return [            'verify' => false,            'cert' => [
          $certPath,                ''            ],
'headers' => ['Connection' => 'close'], // Or simply add this to the
request object        ];    }

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/turtle0x1/LxdMosaic/issues/84#issuecomment-490277817>,
or mute the thread

**Comment by turtle0x1** [comment]
any var_dumps or any of the debugging steps?

**Comment by trenb** [comment]
I'm going to try updating curl tomorrow. Thanks for your help today! I'll update the ticket with the results of my test!

**Comment by turtle0x1** [comment]
Remove the `var_dumps()` thats why its failing

**Comment by trenb** [comment]
I upgraded to curl 7.64.1 (and supporting libraries) with no change. The patch is still required. Is there any negative to this patch being applied to Ubuntu as well as CentOS?

**Comment by turtle0x1** [comment]
potentially much slower access ill work up a patch tonight, will you be providing a centos install script? if not its a pretty risky patch (as im sure a small number of people will mannually install this on centos) and i cant test it without a centos install script

**Comment by trenb** [comment]
Gotcha. Let me work on that then.

**Comment by trenb** [comment]
Alright, I forked your repo and created the centos7 install script. I do *not* have your patch installed to fix the issue with multiple hosts.

Please pull ```https://github.com/trenb/LxdMosaic``` and use examples/install_with_clone_centos7.sh - I spun up my CentOS 7 container via ```lxc launch images:centos/7/amd64 testmosaic1```, curl the file and run it via bash.

**Comment by turtle0x1** [comment]
okay downloading the image now, ive thought of how to selectively apply the fix to centos only

**Comment by turtle0x1** [comment]
Can you open a PR so i can comment please

**Comment by trenb** [comment]
https://github.com/turtle0x1/LxdMosaic/pull/85 created

**Comment by turtle0x1** [comment]
I have pushed a fix for this would you mind testing it ?

**Comment by trenb** [comment]
I reverted my LxdClient.php and pulled. I can confirm that things are working. Nice fix, though if you want to expand this to support RHEL and CentOS, use ```/etc/redhat-release``` instead of ```/etc/centos-release```
