### ISSUE TITLE
[Question] How is Fleet memory is calculated?

### ISSUE THREAD

**Issue by lhorace** [turtle0x1/LxdMosaic#90]
Do you collect statics from all LXD instances and than average out the highest? One LXD instance has 16GB while the other has 7GB, so I am bit perplexed how that's handled? Also, how could I deduced from that graph which CT is using what? Also, is that showing capacity?

Cheers

**Comment by turtle0x1** [comment]
As you can see here https://github.com/turtle0x1/LxdMosaic/blob/master/src/cronJobs/fleetAnalytics.php i use the LXD end point getResources and just sum up the returns  it doesnt store it on a container by container basis

**Comment by turtle0x1** [comment]
Gunna close this as i have answered it, if you want a specific feature open another issue :smile:
