### ISSUE TITLE
README entry for Ubuntu needs to change "centos" to "ubuntu"

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdMosaic#91]
In your Github README file under UBUNTU looks like a cut & paste goof as it says:

\# Launch a **centos 7** container
lxc launch ubuntu: lxdMosaic
\# Connect to **centos** console

Just thought I'd let you know so newbies don't get confused :-)

**Comment by turtle0x1** [comment]
Thanks man :smile:
