### ISSUE TITLE
Minor edit needed in README.md

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdMosaic#92]
In the README.md file it  currently says:

> Installation  
>   
> The preferred installation method is using a ubuntu container.  
> Install script
>  
> Warning this installs apache, docker, mysql-server, php, git and other dependencies its best to run in a container or an empty VM to avoid cluttering your system
>  
> In examples you will find an bash script called install_with_clone.sh this will handle the installation of dependencies and setup this program.
> 
> It handles the cloning of the repository so you can just do;
> 
> **Ubuntu**
> 
> \# Launch a ubuntu 7 container

Remove the "7" as I think the line was a cut & paste from CentOS 7 line

**Comment by turtle0x1** [comment]
would you mind make a pull request for this im on mobile right now? :)

**Comment by bmullan** [comment]
Not to sound dumb but I've never done that "process" before.   I guess i do
a pull, make the edit but then what?

**Comment by bmullan** [comment]
I "think" I got it done...
Brian

**Comment by turtle0x1** [comment]
spot on thank you very much :smile:
