### ISSUE TITLE
Restoring a Snapshot menu should add another option to Restore a Remote Host

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdMosaic#96]
**Is your feature request related to a problem? Please describe.**
Currently the Restore Snapshot menu only has options for:  
- Restore to Origin
- Create Container
- Rename Snapshot

**Describe the solution you'd like**
I think there should be a menu option to Restore the Snapshot as a NEW container to a Remote Host!

This would save a lot of the manual steps required now where the User has to first restore the Snapshot to a New container name on the Same Host.   Then click on that New Container name and COPY it to the Remote Host.

**Comment by bmullan** [comment]
@turtle0x1 just another dumb question but how do I get the updated lxdmosaic so I could test this for you?

**Comment by turtle0x1** [comment]
If go into the container console and execute

```
cd /var/www/LxdMosaic/
git fetch
git checkout restore-snapshot-to-host 
git pull
```

That should give you the latest branch and when your done (and i have merged this)

```
cd /var/www/LxdMosaic/
git checkout master
git pull
```

:smile:

**Comment by bmullan** [comment]
Ok on a Ubuntu 18.04 VM I created an LXD container lxdmosaic:

> # Launch a ubuntu container
> lxc launch ubuntu: lxdMosaic
> # Connect to ubuntu console
> lxc exec lxdMosaic bash
> # Download the script
> curl https://raw.githubusercontent.com/turtle0x1/LxdMosaic/master/examples/install_with_clone.sh >> installLxdMosaic.sh
> # Then give the script execution permissions
> chmod +x installLxdMosaic.sh
> # Then run bellow to setup the program
> ./installLxdMosaic.sh

Then in that container:

> cd /var/www/LxdMosaic/
> git fetch
> git checkout restore-snapshot-to-host 
> git pull

Just for good measure I rebooted both the Container & the VM

However, now when I try to access the https://IP_lxdmosaic:3000

I connect and get the screen that says:

>  Yay all went well you can click **Here** to back to the application

 But unlike in the past where when I click on **Here** I'd get presented with the 
LXDMosaic screen now I get I get the attached as the browser fails to connect.

https://192.168.122.69/
![mosaic1](https://user-images.githubusercontent.com/1682855/60690175-36e6fe80-9e93-11e9-85fa-dabeb9b59d90.png)

**Comment by bmullan** [comment]
@turtle0x1 
Ok I just tried this with 2 VMs.  Both Ubuntu 18.04
I created an LXD container on VM 1 then used LXDMosaic to take a snapshot of it called cn1-snap0

The i clicked on the cn1-snap0 name and now see the new menu where I can select to enter **Target Host** and **New Container Name**.

I do that and specify ciab2 (the over Ubuntu VM) and when I click **Create Container** I get a red box in the upper right of the screen that says **Not Found!**

Note: that from a terminal on the **1st Server** I can **successfully** copy the snapshot to the **2nd server - ciab2** and name that new LXD container **cn1**

> **lxc copy cn1/cn1-snap0 ciab2:cn1**

**Comment by turtle0x1** [comment]
Thanks, ill setup a second lxd server get it fixed tonight!

**Comment by bmullan** [comment]
Its 3:30am here but I'll also double check what I did later as well

Thanks

**Comment by turtle0x1** [comment]
This is done!

**Comment by bmullan** [comment]
How do I get the update so I can test it too

**Comment by turtle0x1** [comment]
In the container with lxd mosaic

```
cd /var/www/LxdMosaic
git checkout master
git pull 
composer update
```

**Comment by bmullan** [comment]
Ok thx

**Comment by bmullan** [comment]
Ok... it does copy the container to the new LXD host now **but...** the original container name was CN1 and I entered the new Container name as CN1 also.

However, when LXDMosaic was done copying the Snapshot to the new LXD Host I refreshed the screen and **both the original container and the new container were renamed somehow to "default"** instead  of CN1

**Comment by bmullan** [comment]
![mosaic1](https://user-images.githubusercontent.com/1682855/60819770-2b832400-a16e-11e9-95cf-110fbf10b095.png)

**Comment by turtle0x1** [comment]
You are in the projects view !

**Comment by bmullan** [comment]
I see that now thx.  I'll try it again
