### ISSUE TITLE
Need Menu options to Delete a server and to Change the IP  of a existing Server

### ISSUE THREAD

**Issue by bmullan** [turtle0x1/LxdMosaic#99]
**Is your feature request related to a problem? Please describe.**
LXDMosaic has an option to ADD a Server but I don't see one to DELETE a Server or
to CHANGE the IP of a existing SERVER.

**Describe the solution you'd like**
There should be an menu option to DELETE a Server or to CHANGE the IP of an existing Server

**Comment by turtle0x1** [comment]
Good idea ill add this in later!
